import type { IndustryPack } from "../index.ts";

type ProjectPackInput = Pick<IndustryPack,
  "key" | "displayName" | "customerTypes" | "terminology" | "locationFields" | "assets" | "services" |
  "formSteps" | "jobChecklist" | "noncompletionReasons" | "workflows" | "reports" | "pricingTemplates" |
  "recommendationQuestions" | "productCapabilityRecommendations" | "recommendedConnectorCapabilities" | "inventoryDefaults" | "website"
>;

function projectPack(input: ProjectPackInput): IndustryPack {
  return {
    ...input,
    version: "1.0.0",
    recurrencePresets: [],
    defaultAutomations: [],
  };
}

/** Separate, profile-backed project workflows for measured installation and design businesses. */
export const CUSTOM_INSTALLATION_PACKS: readonly IndustryPack[] = [
  projectPack({
    key: "awning-installation", displayName: "Awning Installation",
    customerTypes: ["homeowner", "storefront", "restaurant", "commercial_property", "hoa"],
    terminology: { customer: "Customer", serviceLocation: "Property / Opening", job: "Awning Project", estimate: "Measured Proposal", fieldTechnician: "Measure / Install Crew", customerAsset: "Installed Awning", workArea: "Opening / Mounting Area" },
    locationFields: [
      { key: "opening_dimensions", label: "Opening width, projection, and drop", type: "text", customerVisible: true },
      { key: "mounting_surface", label: "Mounting surface and observed condition", type: "text" },
      { key: "access_and_lift", label: "Access, height, and lift needs", type: "text", sensitive: true },
      { key: "approval_status", label: "HOA, permit, or other approval status", type: "text" },
      { key: "motor_electrical_scope", label: "Motor and electrical coordination notes", type: "text" },
    ],
    assets: [{ key: "awning", label: "Installed awning", pluralLabel: "Installed awnings", fields: [
      { key: "style_and_model", label: "Style and product model", type: "text", customerVisible: true },
      { key: "fabric_frame_finish", label: "Fabric, frame, and finish", type: "text", customerVisible: true },
      { key: "motor_control", label: "Motor or control details", type: "text" },
      { key: "warranty_notes", label: "Product warranty notes", type: "text" },
    ] }],
    services: [
      { key: "new-awning", name: "New Awning Measure and Installation", kind: "one_time", defaultEnabled: true },
      { key: "awning-recover", name: "Awning Re-cover", kind: "one_time" },
      { key: "awning-repair", name: "Awning Repair or Adjustment", kind: "recovery" },
      { key: "awning-removal", name: "Awning Removal or Seasonal Storage", kind: "one_time" },
    ],
    formSteps: [
      { key: "project", label: "Describe the opening and awning", fields: ["building_type", "opening_dimensions", "style", "motorized"] },
      { key: "photos", label: "Share photos and arrange a measure", fields: ["opening_photos", "mounting_surface", "access_and_lift"] },
      { key: "approvals", label: "Confirm selections and approvals", fields: ["fabric_frame_finish", "approval_status", "electrical_scope"] },
      { key: "schedule", label: "Plan production and installation", fields: ["product_readiness", "install_window", "weather"] },
    ],
    jobChecklist: [
      { key: "approved-dimensions", label: "Confirm approved drawing and final check-measure", required: true },
      { key: "surface-and-anchors", label: "Record mounting surface and approved attachment plan", required: true },
      { key: "parts-and-access", label: "Confirm product, crew, lift, and site access readiness", required: true },
      { key: "install-and-test", label: "Install to product instructions and test agreed operation", required: true },
      { key: "finish-and-handoff", label: "Photograph finish, walkthrough, and warranty handoff", required: true },
    ],
    noncompletionReasons: [
      { key: "measure-or-drawing", label: "Measurement or drawing needs review", billableByDefault: false },
      { key: "product-delay", label: "Product or fabrication is delayed", billableByDefault: false },
      { key: "approval-pending", label: "Property approval is pending", billableByDefault: false },
      { key: "surface-review", label: "Mounting surface needs qualified review", billableByDefault: false },
      { key: "weather-or-access", label: "Weather, lift, or access prevents work", billableByDefault: false },
      { key: "trade-coordination", label: "Electrical or other trade coordination is pending", billableByDefault: false },
    ],
    workflows: {
      custom_install: ["inquiry", "measure", "design_and_quote", "drawing_approval", "approval_and_deposit", "check_measure", "fabrication", "site_ready", "installation_and_test", "walkthrough", "warranty_handoff"],
      recover_or_repair: ["inquiry", "condition_review", "scope_and_quote", "approval", "schedule", "repair_or_recover", "inspection", "closeout"],
    },
    reports: [
      { key: "measure-to-order", name: "Measure-to-order accuracy", coreMetric: "order_variance", dimensions: ["service", "product_model"] },
      { key: "production-and-install", name: "Production lead time and on-time installation", coreMetric: "schedule_variance", dimensions: ["service", "crew"] },
      { key: "rework-warranty", name: "Rework and warranty follow-up", coreMetric: "job_outcomes", dimensions: ["cause", "product_model"] },
    ],
    pricingTemplates: [
      { key: "awning-product", name: "Awning size and configuration", stage: "quantity", inputFields: ["width", "projection", "drop", "style", "fabric", "frame"], effect: "per_unit", requiresTenantAmount: true },
      { key: "motor-and-options", name: "Motor, controls, and options", stage: "add_on", inputFields: ["motor", "sensor", "controls"], effect: "add_fixed", requiresTenantAmount: true },
      { key: "site-and-trades", name: "Access, mounting, and trade scope", stage: "add_on", inputFields: ["surface", "reinforcement", "lift", "electrical", "permit_or_engineering"], effect: "add_fixed", requiresTenantAmount: true },
      { key: "fabrication-install", name: "Fabrication and installation", stage: "base", inputFields: ["fabrication", "delivery", "installation", "removal"], effect: "add_fixed", requiresTenantAmount: true },
    ],
    recommendationQuestions: [
      { key: "fabrication_model", prompt: "Do you fabricate awnings, resell products, or install customer-supplied products?", answerType: "enum", options: ["fabricate_or_resell", "install_only", "mixed"] },
      { key: "motorized_work", prompt: "Do you install motorized awnings?", answerType: "boolean" },
      { key: "recovery_service", prompt: "Do you offer re-cover, removal, or seasonal storage?", answerType: "boolean" },
      { key: "field_crew", prompt: "Do you schedule employees or regular installation crews?", answerType: "boolean" },
    ],
    productCapabilityRecommendations: [
      { featureKey: "estimate_management", recommendation: "normally_recommended", rationale: "Measured dimensions, product selections, surface conditions, and approvals shape a scoped quote." },
      { featureKey: "service_scheduling", recommendation: "normally_recommended", rationale: "Measure, check-measure, fabrication, and installation are separate milestones." },
      { featureKey: "field_job_tracking", recommendation: "normally_recommended", rationale: "Crews need current dimensions, surface notes, readiness, and closeout evidence." },
      { featureKey: "payment_collection", recommendation: "optional", rationale: "Deposit and final payment policies vary by operator and contract." },
      { featureKey: "inventory_tracking", recommendation: "optional", rationale: "Fabricators or stocking dealers may track product and hardware; install-only teams may order per job." },
    ],
    recommendedConnectorCapabilities: ["payments", "accounting", "calendar", "email", "sms", "storage"], inventoryDefaults: [],
    website: { template: "classic", sections: ["hero", "services", "project_gallery", "how_it_works", "measure_request", "contact"], signupSteps: ["project_type", "opening_photos", "approximate_dimensions", "measure_request", "contact"], heroHeadline: "Shade measured for your space", heroDescription: "Share the opening, product ideas, and site photos. We will review the conditions and confirm a measure before finalizing the proposal." },
  }),

  projectPack({
    key: "custom-closet-build-outs", displayName: "Custom Closet Build-Outs",
    customerTypes: ["homeowner", "builder", "designer", "organizer", "property_manager"],
    terminology: { customer: "Client", serviceLocation: "Property / Room", job: "Closet Project", estimate: "Design Proposal", fieldTechnician: "Designer / Install Team", customerAsset: "Closet System", workArea: "Closet / Storage Area" },
    locationFields: [
      { key: "room_type", label: "Room or storage area", type: "text", customerVisible: true },
      { key: "opening_measurements", label: "Opening and wall measurements", type: "text" },
      { key: "ceiling_and_walls", label: "Ceiling, wall, and floor conditions", type: "text" },
      { key: "access_and_occupancy", label: "Delivery access and room occupancy", type: "text", sensitive: true },
      { key: "removal_and_electrical", label: "Existing system, removal, and lighting notes", type: "text" },
      { key: "approved_revision", label: "Approved layout revision", type: "text", customerVisible: true },
    ],
    assets: [],
    services: [
      { key: "closet-system", name: "Custom Closet System", kind: "one_time", defaultEnabled: true },
      { key: "pantry-storage", name: "Pantry or Utility Storage", kind: "one_time" },
      { key: "mudroom-storage", name: "Mudroom or Entry Storage", kind: "one_time" },
      { key: "closet-refresh", name: "Closet Refresh or Reconfiguration", kind: "one_time" },
      { key: "closet-install", name: "Customer- or Dealer-Supplied System Installation", kind: "one_time" },
    ],
    formSteps: [
      { key: "space", label: "Tell us about the room and storage needs", fields: ["room_type", "photos", "storage_goals", "existing_system"] },
      { key: "measure", label: "Arrange a room measure", fields: ["opening_measurements", "ceiling_and_walls", "door_clearance"] },
      { key: "design", label: "Choose a layout, materials, and accessories", fields: ["layout_options", "finish", "drawers_and_accessories", "approved_revision"] },
      { key: "delivery", label: "Prepare for delivery and installation", fields: ["access_and_occupancy", "removal_and_electrical", "site_readiness"] },
    ],
    jobChecklist: [
      { key: "approved-layout", label: "Confirm client-approved layout and revision", required: true },
      { key: "verified-room", label: "Verify measurements, clearances, and wall conditions", required: true },
      { key: "components-ready", label: "Check ordered components, finish, and delivery condition", required: true },
      { key: "protect-and-install", label: "Protect the room and install the approved system", required: true },
      { key: "fit-and-punch", label: "Check fit, drawer and door operation, photos, and punch", required: true },
    ],
    noncompletionReasons: [
      { key: "design-revision", label: "Layout or selection revision needs approval", billableByDefault: false },
      { key: "measure-condition", label: "Measurement or room condition needs review", billableByDefault: false },
      { key: "parts-delay", label: "Components are missing, damaged, or delayed", billableByDefault: false },
      { key: "room-not-ready", label: "Room, access, or prior work is not ready", billableByDefault: false },
      { key: "fit-or-wall", label: "Fit or wall attachment needs review", billableByDefault: false },
    ],
    workflows: {
      dealer_or_shop: ["inquiry", "consult", "measure", "design_and_options", "proposal", "approval_and_deposit", "order_or_cut_list", "delivery_check", "install", "adjustment_and_punch", "closeout"],
      refresh_or_install: ["inquiry", "condition_review", "scope", "estimate", "approval", "schedule", "remove_or_reconfigure", "install", "walkthrough", "closeout"],
    },
    reports: [
      { key: "design-to-order", name: "Design approval to order timing", coreMetric: "project_age", dimensions: ["service", "room_type"] },
      { key: "parts-and-install", name: "Parts readiness and installation outcomes", coreMetric: "job_outcomes", dimensions: ["supplier", "crew"] },
      { key: "project-margin", name: "Project margin and punch work", coreMetric: "job_margin", dimensions: ["system_type", "service"] },
    ],
    pricingTemplates: [
      { key: "closet-layout", name: "Room, run, and component scope", stage: "quantity", inputFields: ["room_type", "wall_length", "sections", "drawers", "complexity"], effect: "per_unit", requiresTenantAmount: true },
      { key: "materials-finish", name: "System, material, finish, and accessories", stage: "add_on", inputFields: ["system", "material", "finish", "hardware", "accessories"], effect: "add_fixed", requiresTenantAmount: true },
      { key: "delivery-install", name: "Delivery, removal, and installation", stage: "add_on", inputFields: ["delivery", "access", "removal", "installation", "wall_repair"], effect: "add_fixed", requiresTenantAmount: true },
      { key: "project-minimum", name: "Project minimum", stage: "bounds", inputFields: ["project_type"], effect: "set_minimum", requiresTenantAmount: true },
    ],
    recommendationQuestions: [
      { key: "business_model", prompt: "Do you sell a catalog system, fabricate in-house, install for others, or combine these?", answerType: "enum", options: ["dealer", "shop_fabricator", "installer", "mixed"] },
      { key: "fabricates_in_shop", prompt: "Do you fabricate or cut components in your own shop?", answerType: "boolean" },
      { key: "multi_room_projects", prompt: "Do you regularly coordinate several rooms or active projects at once?", answerType: "boolean" },
      { key: "stocks_components", prompt: "Do you hold closet components or accessories between jobs?", answerType: "boolean" },
    ],
    productCapabilityRecommendations: [
      { featureKey: "estimate_management", recommendation: "normally_recommended", rationale: "Room measurements, component selections, price, and revision approval define the order." },
      { featureKey: "service_scheduling", recommendation: "normally_recommended", rationale: "Measure, order, delivery, installation, and punch need distinct dates." },
      { featureKey: "field_job_tracking", recommendation: "normally_recommended", rationale: "Installers need current layout revisions, room conditions, and punch records." },
      { featureKey: "invoicing", recommendation: "normally_recommended", rationale: "Custom orders and installation require a clear project billing record." },
      { featureKey: "payment_collection", recommendation: "normally_recommended", rationale: "Tenant-defined deposits and final payments can be recorded with project closeout." },
      { featureKey: "inventory_tracking", recommendation: "optional", rationale: "Useful for a shop or dealer that holds components; project purchasing may suit installers." },
      { featureKey: "time_tracking", recommendation: "optional", rationale: "Helpful for job costing where employees fabricate or install across projects." },
    ],
    recommendedConnectorCapabilities: ["payments", "accounting", "calendar", "email", "storage"], inventoryDefaults: [],
    website: { template: "classic", sections: ["hero", "closet_styles", "project_gallery", "design_process", "measure_request", "contact"], signupSteps: ["room_type", "room_photos", "storage_goals", "measure_request", "contact"], heroHeadline: "Storage designed around your room", heroDescription: "Share your room, storage goals, and finish ideas. We will measure and review a design before ordering or installing a system." },
  }),

  projectPack({
    key: "custom-furniture-refinishing", displayName: "Custom Furniture Refinishing",
    customerTypes: ["homeowner", "designer", "antique_dealer", "reseller", "hospitality_client"],
    terminology: { customer: "Owner / Client", serviceLocation: "Pickup Site / Workshop", job: "Restoration Job", estimate: "Piece-by-Piece Proposal", fieldTechnician: "Restorer / Finisher", customerAsset: "Customer-Owned Piece", workArea: "Workshop / Item Location" },
    locationFields: [
      { key: "pickup_address", label: "Pickup or service address", type: "text", sensitive: true },
      { key: "pickup_access", label: "Pickup access and handling notes", type: "text", sensitive: true },
      { key: "requested_finish", label: "Requested finish or restoration outcome", type: "text", customerVisible: true },
      { key: "approved_sample", label: "Approved finish sample reference", type: "text", customerVisible: true },
      { key: "storage_location", label: "Workshop storage location", type: "text" },
    ],
    assets: [{ key: "furniture_piece", label: "Furniture piece", pluralLabel: "Furniture pieces", fields: [
      { key: "piece_type", label: "Piece type", type: "text", customerVisible: true },
      { key: "dimensions_and_weight", label: "Dimensions and handling weight", type: "text" },
      { key: "material_and_construction", label: "Wood, veneer, and construction notes", type: "text" },
      { key: "condition_at_receipt", label: "Condition and existing damage at receipt", type: "text" },
      { key: "condition_photos", label: "Receipt condition photos", type: "media" },
      { key: "hardware_inventory", label: "Removed hardware or loose parts", type: "text" },
      { key: "owner_and_provenance", label: "Owner or provenance notes", type: "text", sensitive: true },
      { key: "service_history", label: "Prior restoration and service notes", type: "text" },
    ] }],
    services: [
      { key: "strip-refinish", name: "Strip and Refinish", kind: "one_time", defaultEnabled: true },
      { key: "furniture-repair", name: "Furniture Repair or Veneer Work", kind: "one_time" },
      { key: "custom-paint", name: "Custom Paint or Color Change", kind: "one_time" },
      { key: "antique-restoration", name: "Antique Restoration Assessment", kind: "one_time" },
      { key: "touch-up", name: "On-Site Touch-Up", kind: "one_time" },
      { key: "pickup-delivery", name: "Pickup and Delivery", kind: "add_on" },
    ],
    formSteps: [
      { key: "pieces", label: "Tell us about each piece", fields: ["piece_type", "dimensions", "quantity_in_set", "photos_all_sides"] },
      { key: "condition", label: "Describe condition and past treatment", fields: ["material_and_construction", "condition", "prior_finish", "damage_photos"] },
      { key: "finish", label: "Share the desired result", fields: ["requested_finish", "finish_reference", "repair_scope"] },
      { key: "logistics", label: "Plan inspection, pickup, or delivery", fields: ["pickup_address", "pickup_access", "timeline"] },
    ],
    jobChecklist: [
      { key: "tag-and-receive", label: "Tag each piece and record receipt condition and photos", required: true },
      { key: "inspect-and-scope", label: "Inspect construction and confirm approved scope", required: true },
      { key: "sample-approval", label: "Obtain approval of the finish sample before full treatment", required: true },
      { key: "process-and-cure", label: "Record repair, finish process, and product-specific cure status", required: true },
      { key: "inspect-and-release", label: "Inspect each piece, protect it, and record customer release or delivery", required: true },
    ],
    noncompletionReasons: [
      { key: "hidden-damage", label: "Hidden damage changes the approved scope", billableByDefault: false },
      { key: "sample-not-approved", label: "Finish sample needs client review", billableByDefault: false },
      { key: "material-unsuitable", label: "Material or prior coating needs specialist review", billableByDefault: false },
      { key: "parts-or-subcontract", label: "Hardware, repair part, or subcontract work is delayed", billableByDefault: false },
      { key: "cure-or-workload", label: "Product cure time or workshop capacity delays release", billableByDefault: false },
      { key: "pickup-access", label: "Pickup, delivery, or release access is unavailable", billableByDefault: false },
    ],
    workflows: {
      shop_refinishing: ["photo_or_in_person_inquiry", "item_inspection", "piece_level_estimate", "scope_approval", "tag_and_receive", "repair_and_prep", "finish_sample", "sample_approval", "refinish_and_cure", "quality_review", "ready_for_release", "pickup_or_delivery", "closeout"],
      onsite_touchup: ["inquiry", "photo_review", "site_assessment", "estimate", "approval", "schedule", "protect_and_touch_up", "customer_review", "closeout"],
    },
    reports: [
      { key: "shop-cycle-time", name: "Workshop stage aging and turnaround", coreMetric: "project_age", dimensions: ["piece_type", "service"] },
      { key: "piece-margin", name: "Labor, materials, and margin by piece", coreMetric: "job_margin", dimensions: ["piece_type", "finish_type"] },
      { key: "callbacks-and-custody", name: "Finish callbacks and custody incidents", coreMetric: "job_outcomes", dimensions: ["cause", "service"] },
      { key: "unclaimed-pieces", name: "Items awaiting pickup or delivery", coreMetric: "open_jobs", dimensions: ["storage_location", "customer_type"] },
    ],
    pricingTemplates: [
      { key: "piece-and-condition", name: "Piece type, size, and condition", stage: "quantity", inputFields: ["piece_type", "dimensions", "construction", "condition", "detail_level"], effect: "per_unit", requiresTenantAmount: true },
      { key: "repair-and-prep", name: "Stripping, repair, and preparation", stage: "add_on", inputFields: ["stripping", "veneer_repair", "hardware", "upholstery_subcontract"], effect: "add_fixed", requiresTenantAmount: true },
      { key: "finish-and-sample", name: "Finish, sample, and specialty materials", stage: "add_on", inputFields: ["finish_type", "color_sample", "coating", "special_material"], effect: "add_fixed", requiresTenantAmount: true },
      { key: "custody-and-delivery", name: "Pickup, delivery, packing, or storage", stage: "add_on", inputFields: ["pickup", "delivery", "packing", "storage"], effect: "add_fixed", requiresTenantAmount: true },
    ],
    recommendationQuestions: [
      { key: "work_location", prompt: "Do you work in a shop, on site, or both?", answerType: "enum", options: ["shop", "onsite", "both"] },
      { key: "pickup_delivery", prompt: "Do you take custody of customer pieces for pickup, delivery, or storage?", answerType: "boolean" },
      { key: "multi_piece_sets", prompt: "Do you regularly handle sets or multi-piece commissions?", answerType: "boolean" },
      { key: "spray_finishing", prompt: "Do you spray finishes in your own shop?", answerType: "boolean" },
    ],
    productCapabilityRecommendations: [
      { featureKey: "estimate_management", recommendation: "normally_recommended", rationale: "Each piece needs a condition- and repair-specific proposal with explicit scope." },
      { featureKey: "service_scheduling", recommendation: "normally_recommended", rationale: "Inspection, shop stages, cure time, and customer release form a queue." },
      { featureKey: "customer_notifications", recommendation: "normally_recommended", rationale: "Finish approval, stage updates, delays, and ready notices need clear communication." },
      { featureKey: "invoicing", recommendation: "normally_recommended", rationale: "Piece-level work and approved changes need a billing record." },
      { featureKey: "field_job_tracking", recommendation: "optional", rationale: "Useful for pickup, delivery, and on-site touch-up; shop-only work may need less field use." },
      { featureKey: "inventory_tracking", recommendation: "optional", rationale: "Larger shops may track finishes and repair materials while smaller shops buy per job." },
      { featureKey: "route_planning", recommendation: "optional", rationale: "A pickup and delivery crew may coordinate clustered stops; it is not needed for shop-only work." },
    ],
    recommendedConnectorCapabilities: ["payments", "email", "sms", "calendar", "accounting", "storage", "routing"], inventoryDefaults: [],
    website: { template: "classic", sections: ["hero", "services", "before_after_gallery", "how_it_works", "photo_estimate", "contact"], signupSteps: ["piece_photos", "piece_details", "condition_and_goal", "inspection_or_pickup", "contact"], heroHeadline: "Give well-loved furniture a considered new finish", heroDescription: "Send photos of each piece, its condition, and the finish you have in mind. We will review the details and confirm an inspection and scope." },
  }),

  projectPack({
    key: "custom-wallpaper-installation", displayName: "Custom Wallpaper Installation",
    customerTypes: ["homeowner", "interior_designer", "builder", "hospitality_client", "property_manager"],
    terminology: { customer: "Client", serviceLocation: "Property / Room", job: "Wallcovering Project", estimate: "Room-by-Room Proposal", fieldTechnician: "Wallcovering Installer", customerAsset: "Installed Wallcovering", workArea: "Room / Wall" },
    locationFields: [
      { key: "room_and_wall", label: "Room and wall identifier", type: "text", customerVisible: true },
      { key: "wall_measurements", label: "Wall width, height, and openings", type: "text" },
      { key: "surface_and_moisture", label: "Surface condition and moisture notes", type: "text" },
      { key: "existing_covering", label: "Existing wallcovering and removal scope", type: "text" },
      { key: "room_access", label: "Furniture, occupancy, and room access", type: "text", sensitive: true },
      { key: "approved_product_lot", label: "Approved product, pattern, and lot", type: "text", customerVisible: true },
    ],
    assets: [{ key: "wallcovering", label: "Installed wallcovering", pluralLabel: "Installed wallcoverings", fields: [
      { key: "brand_design_sku", label: "Brand, design, and product SKU", type: "text", customerVisible: true },
      { key: "lot_and_pattern", label: "Material lot and pattern repeat", type: "text" },
      { key: "installed_room", label: "Room and wall installed", type: "text" },
      { key: "adhesive_and_primer", label: "Adhesive and primer notes", type: "text" },
      { key: "care_and_warranty", label: "Care or warranty notes", type: "text" },
    ] }],
    services: [
      { key: "wallcovering-install", name: "Wallcovering Measure and Installation", kind: "one_time", defaultEnabled: true },
      { key: "custom-mural", name: "Mural or Feature Wall Installation", kind: "one_time" },
      { key: "wallcovering-removal", name: "Wallcovering Removal", kind: "one_time" },
      { key: "wall-preparation", name: "Wall Preparation or Priming", kind: "add_on" },
      { key: "seam-repair", name: "Seam Repair or Rehang", kind: "recovery" },
      { key: "commercial-wallcovering", name: "Commercial or Multi-Room Installation", kind: "one_time" },
    ],
    formSteps: [
      { key: "rooms", label: "List rooms and walls", fields: ["room_count", "wall_measurements", "photos_each_wall", "ceiling_height"] },
      { key: "surface", label: "Describe the wall surface and existing covering", fields: ["surface_and_moisture", "existing_covering", "prep_or_removal"] },
      { key: "material", label: "Share the selected material and pattern", fields: ["brand_design_sku", "pattern_repeat", "material_lot", "client_or_installer_supplied"] },
      { key: "readiness", label: "Plan room preparation and survey", fields: ["room_access", "other_trades", "survey_request"] },
    ],
    jobChecklist: [
      { key: "scope-and-product", label: "Confirm approved scope, product SKU, pattern, and lot", required: true },
      { key: "survey-and-readiness", label: "Verify dimensions, wall condition, and room readiness", required: true },
      { key: "protect-and-prepare", label: "Protect the room and complete only contracted preparation", required: true },
      { key: "hang-and-align", label: "Install using the selected product instructions and check seams", required: true },
      { key: "inspect-and-close", label: "Photograph completed walls and record acceptance and care notes", required: true },
    ],
    noncompletionReasons: [
      { key: "wall-not-ready", label: "Wall is wet, uncured, damaged, or otherwise not ready", billableByDefault: false },
      { key: "material-shortage", label: "Material is short, damaged, or lot-mismatched", billableByDefault: false },
      { key: "pattern-approval", label: "Pattern, proof, or substitution needs client approval", billableByDefault: false },
      { key: "prep-change", label: "Hidden surface condition changes preparation scope", billableByDefault: false },
      { key: "room-or-trade", label: "Room access or another trade prevents installation", billableByDefault: false },
    ],
    workflows: {
      residential: ["inquiry_and_photos", "room_survey", "proposal_and_scope", "product_and_lot_approval", "material_readiness", "room_preparation", "installation", "inspection_and_photos", "care_and_closeout"],
      commercial: ["bid_or_referral", "site_review", "room_sequence_and_quote", "sample_or_proof_approval", "material_order", "site_readiness", "phased_install", "walkthrough_and_punch", "closeout"],
    },
    reports: [
      { key: "survey-to-start", name: "Survey-to-install start time", coreMetric: "schedule_variance", dimensions: ["service", "material_type"] },
      { key: "material-variance", name: "Material waste and shortage", coreMetric: "material_variance", dimensions: ["product", "room"] },
      { key: "first-pass-quality", name: "First-pass acceptance and callbacks", coreMetric: "job_outcomes", dimensions: ["installer", "cause"] },
    ],
    pricingTemplates: [
      { key: "wall-area", name: "Room, wall area, and quantity", stage: "quantity", inputFields: ["wall_area", "room_count", "wall_height", "panel_count", "surface_complexity"], effect: "per_unit", requiresTenantAmount: true },
      { key: "material-pattern", name: "Material, pattern, and waste", stage: "add_on", inputFields: ["material_type", "pattern_repeat", "specialty_handling", "waste_allowance"], effect: "add_fixed", requiresTenantAmount: true },
      { key: "prep-and-removal", name: "Removal and wall preparation", stage: "add_on", inputFields: ["removal", "repair", "skim", "prime"], effect: "add_fixed", requiresTenantAmount: true },
      { key: "access-and-protection", name: "Height, access, protection, and travel", stage: "add_on", inputFields: ["ceiling_height", "access", "furniture_protection", "travel"], effect: "add_fixed", requiresTenantAmount: true },
    ],
    recommendationQuestions: [
      { key: "material_supply", prompt: "Do you install customer-supplied paper, supply materials, or both?", answerType: "enum", options: ["customer_supplied", "installer_supplied", "both"] },
      { key: "prep_and_removal", prompt: "Do you offer wall preparation or old-paper removal?", answerType: "boolean" },
      { key: "commercial_work", prompt: "Do you work with designers or commercial multi-room projects?", answerType: "boolean" },
      { key: "specialty_materials", prompt: "Do you install specialty papers or custom murals?", answerType: "boolean" },
    ],
    productCapabilityRecommendations: [
      { featureKey: "estimate_management", recommendation: "normally_recommended", rationale: "Wall condition, preparation, material, and pattern make each scope different." },
      { featureKey: "service_scheduling", recommendation: "normally_recommended", rationale: "Survey, material readiness, preparation, dry time, and installation affect the schedule." },
      { featureKey: "field_job_tracking", recommendation: "normally_recommended", rationale: "Installers need room, wall, product, and site-condition details." },
      { featureKey: "customer_notifications", recommendation: "normally_recommended", rationale: "Clients and designers need preparation, material, schedule, and change updates." },
      { featureKey: "inventory_tracking", recommendation: "optional", rationale: "Lot and roll tracking helps when the installer supplies or holds materials." },
      { featureKey: "payment_collection", recommendation: "optional", rationale: "Deposit and final-payment terms vary by installer and contract." },
      { featureKey: "route_planning", recommendation: "usually_unnecessary", rationale: "Room readiness and project sequencing matter more than dense daily routes." },
    ],
    recommendedConnectorCapabilities: ["calendar", "email", "sms", "payments", "accounting", "storage"], inventoryDefaults: [],
    website: { template: "classic", sections: ["hero", "services", "wallcovering_gallery", "how_it_works", "photo_quote_request", "contact"], signupSteps: ["room_and_wall_photos", "approximate_dimensions", "material_selection", "surface_and_prep", "quote_request"], heroHeadline: "Wallcovering installed with care for every detail", heroDescription: "Share each room, the wall condition, and your selected pattern. We will review preparation and material needs before confirming a project quote." },
  }),

  projectPack({
    key: "green-home-consultation", displayName: "Green Home Consultation",
    customerTypes: ["homeowner", "homebuyer", "landlord", "property_manager", "builder", "utility_program_participant"],
    terminology: { customer: "Homeowner / Client", serviceLocation: "Property", job: "Home Assessment", estimate: "Assessment Scope", fieldTechnician: "Assessor", customerAsset: "Home Energy Assessment", workArea: "Building System / Area" },
    locationFields: [
      { key: "building_type_age_area", label: "Building type, age, and area", type: "text" },
      { key: "heating_fuel", label: "Heating system and fuel", type: "text" },
      { key: "envelope_systems", label: "Known insulation, windows, and envelope details", type: "text" },
      { key: "comfort_concerns", label: "Comfort, moisture, or energy concerns", type: "text", customerVisible: true },
      { key: "utility_data_consent", label: "Utility data permission and source notes", type: "text", sensitive: true },
      { key: "site_access", label: "Occupied areas and assessment access", type: "text", sensitive: true },
    ],
    assets: [{ key: "home_assessment", label: "Home assessment", pluralLabel: "Home assessments", fields: [
      { key: "assessment_scope", label: "Assessment level and deliverable", type: "text", customerVisible: true },
      { key: "assessor_and_program", label: "Assessor credential or program", type: "text" },
      { key: "tests_performed", label: "Tests and field readings performed", type: "text" },
      { key: "assumptions_and_limits", label: "Report assumptions and limitations", type: "text", customerVisible: true },
      { key: "report_version", label: "Report date and version", type: "text", customerVisible: true },
      { key: "recommendations", label: "Prioritized recommendations", type: "text", customerVisible: true },
    ] }],
    services: [
      { key: "energy-walkthrough", name: "Home Energy Walkthrough", kind: "one_time", defaultEnabled: true },
      { key: "diagnostic-assessment", name: "Diagnostic Home Performance Assessment", kind: "one_time" },
      { key: "energy-score-report", name: "Home Energy Score or Rating Assessment", kind: "one_time" },
      { key: "energy-consultation", name: "Energy Modeling and Recommendations", kind: "one_time" },
      { key: "upgrade-verification", name: "Post-Upgrade Follow-Up or Verification", kind: "one_time" },
    ],
    formSteps: [
      { key: "goals", label: "Choose the kind of guidance you need", fields: ["customer_goal", "report_purpose", "energy_or_broader_scope"] },
      { key: "property", label: "Share property and system details", fields: ["building_type_age_area", "heating_fuel", "envelope_systems", "photos"] },
      { key: "records", label: "Provide available bills and program details", fields: ["utility_bills", "utility_data_consent", "program_or_payor"] },
      { key: "visit", label: "Prepare for the assessment visit", fields: ["site_access", "known_safety_concerns", "tests_requested"] },
    ],
    jobChecklist: [
      { key: "scope-and-credentials", label: "Confirm report purpose, service scope, and applicable assessor program", required: true },
      { key: "consent-and-records", label: "Record customer consent and property data source", required: true },
      { key: "field-evidence", label: "Record only selected tests, readings, photos, and assumptions", required: true },
      { key: "safety-and-referrals", label: "Record safety concerns, limitations, and referrals for out-of-scope conditions", required: true },
      { key: "review-and-deliver", label: "Review report and deliver recommendations with limitations", required: true },
    ],
    noncompletionReasons: [
      { key: "records-incomplete", label: "Utility data or required property records are incomplete", billableByDefault: false },
      { key: "access-unavailable", label: "Required rooms or systems are inaccessible", billableByDefault: false },
      { key: "unsafe-condition", label: "Observed condition needs qualified safety review", billableByDefault: false },
      { key: "program-review", label: "Program, credential, or report eligibility needs review", billableByDefault: false },
      { key: "test-condition", label: "Test conditions are unsuitable for the selected assessment", billableByDefault: false },
    ],
    workflows: {
      paid_assessment: ["inquiry", "scope_and_payor_review", "records_and_consent", "schedule_site_visit", "field_assessment", "analysis_and_report", "quality_review", "report_delivery", "recommendation_follow_up"],
      program_assessment: ["program_eligibility_review", "scope_and_credential_check", "data_collection", "site_visit", "selected_testing", "program_qa", "report_delivery", "upgrade_or_referral_follow_up"],
    },
    reports: [
      { key: "assessment-pipeline", name: "Assessment and report turnaround", coreMetric: "project_age", dimensions: ["service", "payment_source"] },
      { key: "assessment-completeness", name: "Assessment coverage and QA corrections", coreMetric: "job_outcomes", dimensions: ["assessor", "program"] },
      { key: "recommendation-followup", name: "Recommendations and follow-up", coreMetric: "follow_up_status", dimensions: ["measure_type", "service"] },
    ],
    pricingTemplates: [
      { key: "assessment-level", name: "Assessment scope and deliverable", stage: "base", inputFields: ["walkthrough", "diagnostics", "score_or_rating", "report", "follow_up"], effect: "add_fixed", requiresTenantAmount: true },
      { key: "home-complexity", name: "Home size and system complexity", stage: "quantity", inputFields: ["building_area", "building_type", "system_count", "property_complexity"], effect: "per_unit", requiresTenantAmount: true },
      { key: "travel-and-testing", name: "Travel, testing, and program support", stage: "add_on", inputFields: ["travel", "diagnostic_tests", "modeling", "program_documentation"], effect: "add_fixed", requiresTenantAmount: true },
      { key: "program-payment", name: "Customer fee or program contribution", stage: "promotion", inputFields: ["program_subsidy", "customer_contribution", "payment_source"], effect: "subtract_fixed", requiresTenantAmount: true },
    ],
    recommendationQuestions: [
      { key: "consultation_scope", prompt: "Do you focus on energy assessment, broader sustainability advice, or both?", answerType: "enum", options: ["energy_assessment", "broader_sustainability", "both"] },
      { key: "assessment_testing", prompt: "Do you perform instrumented diagnostic testing?", answerType: "boolean" },
      { key: "program_work", prompt: "Do you serve utility or rating programs with specific credentials and reports?", answerType: "boolean" },
      { key: "installs_upgrades", prompt: "Do you also install upgrades, or only assess and advise?", answerType: "enum", options: ["assess_and_advise", "also_install", "refer_only"] },
    ],
    productCapabilityRecommendations: [
      { featureKey: "estimate_management", recommendation: "normally_recommended", rationale: "Walkthrough, diagnostic, and program scopes have different deliverables and payors." },
      { featureKey: "service_scheduling", recommendation: "normally_recommended", rationale: "Occupied-home access and test conditions shape assessment visits." },
      { featureKey: "field_job_tracking", recommendation: "normally_recommended", rationale: "Assessors need dated property data, readings, photos, and limitations." },
      { featureKey: "customer_notifications", recommendation: "normally_recommended", rationale: "Clients need record requests, visit preparation, report status, and follow-up." },
      { featureKey: "invoicing", recommendation: "optional", rationale: "Independent paid work and program-funded assessments have different billing paths." },
      { featureKey: "payment_collection", recommendation: "optional", rationale: "Some services are paid by the owner while others are subsidized or free to the household." },
      { featureKey: "recurring_service_management", recommendation: "usually_unnecessary", rationale: "Follow-up after upgrades is separately scoped rather than an assumed recurring visit." },
    ],
    recommendedConnectorCapabilities: ["calendar", "email", "storage", "payments", "accounting", "crm_import"], inventoryDefaults: [
      { key: "assessment-equipment", name: "Assessment equipment and calibration record", unit: "item" },
    ],
    website: { template: "classic", sections: ["hero", "services", "assessment_process", "what_to_prepare", "assessment_request", "contact"], signupSteps: ["assessment_goal", "property_type", "known_systems", "report_or_program_purpose", "contact"], heroHeadline: "Understand your home's energy and improvement options", heroDescription: "Tell us about your property, goals, and report needs. We will confirm assessment scope, available programs, and the right visit before making recommendations." },
  }),

  projectPack({
    key: "home-bar-building", displayName: "Home Bar Building",
    customerTypes: ["homeowner", "interior_designer", "cabinet_shop", "remodeler", "general_contractor"],
    terminology: { customer: "Client", serviceLocation: "Property / Room", job: "Home Bar Project", estimate: "Design and Build Proposal", fieldTechnician: "Design / Build Team", customerAsset: "Installed Cabinetry / Appliance", workArea: "Bar Area / Room" },
    locationFields: [
      { key: "bar_type", label: "Dry, wet, or outdoor bar", type: "enum", options: ["dry", "wet", "outdoor", "mixed"], customerVisible: true },
      { key: "room_dimensions_access", label: "Room dimensions and delivery access", type: "text" },
      { key: "existing_utilities", label: "Existing utility and rough-in notes", type: "text" },
      { key: "appliance_specs", label: "Sink and appliance selections or cut sheets", type: "text", customerVisible: true },
      { key: "approved_drawing_revision", label: "Approved drawing revision", type: "text", customerVisible: true },
      { key: "trade_scope", label: "Included trades and responsibility notes", type: "text" },
      { key: "occupancy_and_access", label: "Occupancy and site access", type: "text", sensitive: true },
    ],
    assets: [{ key: "bar_installation", label: "Bar installation", pluralLabel: "Bar installations", fields: [
      { key: "cabinetry_and_finish", label: "Cabinetry and finish selections", type: "text", customerVisible: true },
      { key: "appliance_models", label: "Installed appliance models", type: "text" },
      { key: "warranty_handoff", label: "Product warranty handoff", type: "text" },
    ] }],
    services: [
      { key: "bar-cabinetry", name: "Custom Bar Cabinetry", kind: "one_time", defaultEnabled: true },
      { key: "dry-bar", name: "Dry Bar Build-Out", kind: "one_time" },
      { key: "wet-bar", name: "Wet Bar Design and Build Coordination", kind: "one_time" },
      { key: "outdoor-bar", name: "Outdoor Bar Build-Out", kind: "one_time" },
      { key: "bar-install", name: "Delivery and Installation", kind: "add_on" },
      { key: "bar-punch", name: "Punch or Adjustment Visit", kind: "recovery" },
    ],
    formSteps: [
      { key: "project", label: "Describe the room and bar use", fields: ["bar_type", "room_dimensions_access", "photos_or_plans", "design_goals"] },
      { key: "features", label: "Choose storage, appliances, and finish", fields: ["appliance_specs", "cabinetry_and_finish", "countertop", "lighting"] },
      { key: "trades", label: "Clarify trade and utility scope", fields: ["existing_utilities", "trade_scope", "designer_or_gc"] },
      { key: "review", label: "Arrange a measure and design review", fields: ["site_measure", "budget_range", "approved_drawing_revision"] },
    ],
    jobChecklist: [
      { key: "measure-and-design", label: "Confirm site measure, use, and approved layout revision", required: true },
      { key: "selections-and-scope", label: "Confirm cabinet, finish, appliance, and trade scope approvals", required: true },
      { key: "rough-in-ready", label: "Record rough-in and site readiness responsibility", required: true },
      { key: "delivery-and-install", label: "Check delivered items, protect the room, and record installation", required: true },
      { key: "trade-test-and-punch", label: "Record qualified trade handoff, walkthrough, and punch status", required: true },
    ],
    noncompletionReasons: [
      { key: "selection-change", label: "Client selection or drawing revision needs approval", billableByDefault: false },
      { key: "rough-in-not-ready", label: "Required rough-in or prior trade is not ready", billableByDefault: false },
      { key: "appliance-delay", label: "Appliance, material, or delivery is delayed", billableByDefault: false },
      { key: "site-access", label: "Room access, occupancy, or delivery is unavailable", billableByDefault: false },
      { key: "concealed-condition", label: "Concealed site condition changes approved scope", billableByDefault: false },
      { key: "trade-inspection", label: "Trade completion or inspection is outstanding", billableByDefault: false },
    ],
    workflows: {
      cabinetry_only: ["inquiry", "consult_and_measure", "design_and_selections", "estimate", "approval_and_deposit", "fabrication", "delivery", "installation", "walkthrough", "warranty_handoff"],
      wet_or_full_room: ["inquiry", "site_review", "design_and_scope", "trade_responsibility", "estimate_and_allowances", "drawing_approval", "rough_in", "fabrication_and_procurement", "delivery_and_install", "trade_connections", "punch_and_closeout"],
    },
    reports: [
      { key: "approval-and-lead-time", name: "Design approval and project lead time", coreMetric: "project_age", dimensions: ["bar_type", "service"] },
      { key: "trade-and-delivery-delays", name: "Trade and delivery schedule blockers", coreMetric: "schedule_variance", dimensions: ["cause", "responsible_party"] },
      { key: "changes-and-punch", name: "Change orders and punch outcomes", coreMetric: "job_outcomes", dimensions: ["service", "crew"] },
    ],
    pricingTemplates: [
      { key: "cabinetry-and-run", name: "Bar dimensions and cabinetry", stage: "quantity", inputFields: ["linear_length", "cabinet_count", "construction", "complexity"], effect: "per_unit", requiresTenantAmount: true },
      { key: "materials-and-top", name: "Finish, hardware, countertop, and glass", stage: "add_on", inputFields: ["material", "finish", "hardware", "countertop", "glass"], effect: "add_fixed", requiresTenantAmount: true },
      { key: "appliances-and-trades", name: "Appliances and qualified trade allowances", stage: "add_on", inputFields: ["appliances", "plumbing", "electrical", "lighting", "trade_allowance"], effect: "add_fixed", requiresTenantAmount: true },
      { key: "delivery-and-install", name: "Demolition, access, delivery, and installation", stage: "add_on", inputFields: ["demolition", "stairs_or_lift", "delivery", "installation"], effect: "add_fixed", requiresTenantAmount: true },
    ],
    recommendationQuestions: [
      { key: "project_scope", prompt: "Do you build cabinetry only or coordinate a full bar room?", answerType: "enum", options: ["cabinetry_only", "full_room", "both"] },
      { key: "wet_bar_work", prompt: "Do your projects include wet bars with plumbing coordination?", answerType: "boolean" },
      { key: "shop_fabrication", prompt: "Do you fabricate cabinetry in-house?", answerType: "boolean" },
      { key: "trade_subcontractors", prompt: "Do you coordinate outside trades on projects?", answerType: "boolean" },
    ],
    productCapabilityRecommendations: [
      { featureKey: "estimate_management", recommendation: "normally_recommended", rationale: "Measured cabinetry, allowances, trade scope, and approved changes need a clear proposal." },
      { featureKey: "service_scheduling", recommendation: "normally_recommended", rationale: "Design decisions, rough-ins, fabrication, delivery, and installation depend on one another." },
      { featureKey: "field_job_tracking", recommendation: "normally_recommended", rationale: "Site conditions, responsibility, change approvals, and punch need a dated job record." },
      { featureKey: "invoicing", recommendation: "normally_recommended", rationale: "Project billing and closeout need records aligned to the agreed scope." },
      { featureKey: "payment_collection", recommendation: "normally_recommended", rationale: "The business can record its own deposit, progress, and completion terms." },
      { featureKey: "inventory_tracking", recommendation: "optional", rationale: "A shop may hold cabinetry materials; many teams purchase per project." },
      { featureKey: "time_tracking", recommendation: "optional", rationale: "Useful when employees or in-house fabrication labor are costed by project." },
      { featureKey: "customer_self_service", recommendation: "optional", rationale: "Clients may share photos and approve selections while staff confirms measurements and site scope." },
    ],
    recommendedConnectorCapabilities: ["calendar", "email", "storage", "accounting", "payments", "sms"], inventoryDefaults: [],
    website: { template: "classic", sections: ["hero", "bar_styles", "project_gallery", "design_process", "measure_request", "contact"], signupSteps: ["bar_type", "room_photos_or_plans", "appliance_and_storage_goals", "measure_request", "contact"], heroHeadline: "A home bar designed for the way you entertain", heroDescription: "Share your room, cabinetry ideas, appliances, and trade needs. We will review dimensions and scope before confirming a custom proposal." },
  }),

  projectPack({
    key: "home-cinema-installation", displayName: "Home Cinema Installation",
    customerTypes: ["homeowner", "builder", "interior_designer", "architect", "av_integrator"],
    terminology: { customer: "Client", serviceLocation: "Property / Theater Room", job: "Cinema Project", estimate: "System Proposal", fieldTechnician: "AV Design / Install Team", customerAsset: "Installed AV System", workArea: "Theater / Media Room" },
    locationFields: [
      { key: "room_dimensions", label: "Room dimensions and seating layout", type: "text" },
      { key: "construction_stage", label: "Room construction or renovation stage", type: "text" },
      { key: "electrical_network", label: "Power, network, and rack location notes", type: "text" },
      { key: "lighting_and_windows", label: "Ambient light, windows, and shade notes", type: "text" },
      { key: "acoustic_scope", label: "Acoustic and room-treatment scope", type: "text" },
      { key: "plans_and_credentials", label: "Plans and system access notes", type: "text", sensitive: true },
      { key: "builder_coordination", label: "Builder and trade coordination contacts", type: "text" },
    ],
    assets: [{ key: "cinema_system", label: "Installed cinema system", pluralLabel: "Installed cinema systems", fields: [
      { key: "display_and_screen", label: "Display, projector, and screen details", type: "text", customerVisible: true },
      { key: "speaker_layout", label: "Speaker and channel layout", type: "text" },
      { key: "av_rack_and_wiring", label: "AV rack and wiring map reference", type: "text", sensitive: true },
      { key: "device_models_serials", label: "Device models and serials", type: "text" },
      { key: "calibration_handover", label: "Calibration and user handoff notes", type: "text", customerVisible: true },
      { key: "warranty_and_support", label: "Warranty and support notes", type: "text" },
    ] }],
    services: [
      { key: "cinema-consult", name: "Cinema Consultation and Room Review", kind: "add_on" },
      { key: "cinema-design", name: "Home Cinema System Design", kind: "one_time", defaultEnabled: true },
      { key: "cinema-prewire", name: "Prewire and Infrastructure Coordination", kind: "one_time" },
      { key: "cinema-install", name: "AV Equipment Installation and Integration", kind: "one_time" },
      { key: "calibration-handover", name: "System Setup, Calibration, and Handover", kind: "one_time" },
      { key: "cinema-support", name: "Support Visit or System Upgrade", kind: "recovery" },
    ],
    formSteps: [
      { key: "room-and-goals", label: "Describe the room and viewing goals", fields: ["room_dimensions", "room_use", "seating", "budget_range"] },
      { key: "system", label: "Share equipment and system preferences", fields: ["display_type", "speaker_layout", "control_preferences", "equipment_supplied"] },
      { key: "site", label: "Tell us about construction and infrastructure", fields: ["construction_stage", "electrical_network", "lighting_and_windows", "builder_coordination"] },
      { key: "design-review", label: "Arrange a room and system design review", fields: ["plans_and_photos", "acoustic_scope", "consultation_request"] },
    ],
    jobChecklist: [
      { key: "approved-system", label: "Confirm approved room plan, equipment, and scope revision", required: true },
      { key: "site-and-wiring", label: "Record site readiness and agreed wiring or trade handoff", required: true },
      { key: "equipment-and-install", label: "Check delivered equipment and record installation progress", required: true },
      { key: "configure-and-verify", label: "Record agreed system setup, calibration, and function checks", required: true },
      { key: "train-and-handoff", label: "Demonstrate agreed controls and provide system and warranty handoff", required: true },
    ],
    noncompletionReasons: [
      { key: "design-decision", label: "Client equipment or design decision is pending", billableByDefault: false },
      { key: "room-construction", label: "Room construction or treatment is not ready", billableByDefault: false },
      { key: "equipment-delay", label: "Equipment or material is missing or delayed", billableByDefault: false },
      { key: "trade-dependency", label: "Builder, electrical, or other trade work is pending", billableByDefault: false },
      { key: "scope-change", label: "Approved system or room scope has changed", billableByDefault: false },
      { key: "access-or-test", label: "Access or agreed system testing is unavailable", billableByDefault: false },
    ],
    workflows: {
      room_upgrade: ["inquiry", "consultation", "room_review", "system_options", "proposal_and_approval", "equipment_order", "site_ready", "install_and_configure", "calibration", "user_handover", "support_follow_up"],
      dedicated_theater: ["lead", "room_design", "budget_and_scope", "plan_approval", "builder_coordination", "prewire_and_construction", "equipment_procurement", "installation", "calibration_and_commissioning", "training_and_punch", "closeout"],
    },
    reports: [
      { key: "pipeline-by-room", name: "Cinema pipeline and stage aging", coreMetric: "project_age", dimensions: ["project_type", "stage"] },
      { key: "equipment-and-trades", name: "Equipment and trade schedule variance", coreMetric: "schedule_variance", dimensions: ["supplier", "dependency"] },
      { key: "support-and-punch", name: "Punch, support, and callback outcomes", coreMetric: "job_outcomes", dimensions: ["system_type", "cause"] },
    ],
    pricingTemplates: [
      { key: "design-and-room", name: "Room design and consultation", stage: "base", inputFields: ["room_size", "design_scope", "site_visits", "plans"], effect: "add_fixed", requiresTenantAmount: true },
      { key: "equipment-system", name: "Equipment and system configuration", stage: "quantity", inputFields: ["display", "screen", "speakers", "rack", "control_system"], effect: "per_unit", requiresTenantAmount: true },
      { key: "infrastructure-and-acoustic", name: "Prewire, acoustic, and lighting scope", stage: "add_on", inputFields: ["prewire", "network", "acoustic_treatment", "lighting", "shades"], effect: "add_fixed", requiresTenantAmount: true },
      { key: "install-and-support", name: "Installation, calibration, and support", stage: "add_on", inputFields: ["installation", "programming", "calibration", "training", "support"], effect: "add_fixed", requiresTenantAmount: true },
    ],
    recommendationQuestions: [
      { key: "design_vs_install", prompt: "Do you design full rooms, install selected equipment, or both?", answerType: "enum", options: ["room_design", "installation_only", "both"] },
      { key: "equipment_supply", prompt: "Do you supply the AV equipment?", answerType: "boolean" },
      { key: "new_build_work", prompt: "Do you coordinate prewire and new-build projects?", answerType: "boolean" },
      { key: "ongoing_support", prompt: "Do you offer paid ongoing support or managed service?", answerType: "boolean" },
    ],
    productCapabilityRecommendations: [
      { featureKey: "estimate_management", recommendation: "normally_recommended", rationale: "Room-specific design options, equipment, construction scope, and changes need a reviewed proposal." },
      { featureKey: "service_scheduling", recommendation: "normally_recommended", rationale: "Room readiness, equipment lead times, trade work, install, and calibration must be coordinated." },
      { featureKey: "field_job_tracking", recommendation: "normally_recommended", rationale: "The team needs current site notes, wiring references, device records, and handover evidence." },
      { featureKey: "invoicing", recommendation: "normally_recommended", rationale: "Project equipment and labor require a clear customer billing record." },
      { featureKey: "customer_notifications", recommendation: "normally_recommended", rationale: "Customer decisions, equipment delivery, site readiness, and project changes need updates." },
      { featureKey: "recurring_service_management", recommendation: "optional", rationale: "Useful only when the integrator sells ongoing support or maintenance plans." },
      { featureKey: "inventory_tracking", recommendation: "optional", rationale: "Relevant when a company stocks AV equipment or common parts rather than ordering per project." },
    ],
    recommendedConnectorCapabilities: ["calendar", "email", "storage", "accounting", "payments", "sms"], inventoryDefaults: [],
    website: { template: "classic", sections: ["hero", "cinema_services", "room_gallery", "design_process", "consultation_request", "contact"], signupSteps: ["room_photos_or_plans", "room_goals", "equipment_preferences", "project_stage", "consultation_request"], heroHeadline: "A cinema system planned around your room", heroDescription: "Share your room, viewing goals, and project stage. We will review design, equipment, and construction needs before proposing an installation." },
  }),

  projectPack({
    key: "home-office-build-out", displayName: "Home Office Build-Out",
    customerTypes: ["homeowner", "remote_worker", "home_business", "designer", "remodeler", "property_manager"],
    terminology: { customer: "Client", serviceLocation: "Property / Office Room", job: "Home Office Project", estimate: "Room Scope and Proposal", fieldTechnician: "Design / Build Team", customerAsset: "Installed Built-In", workArea: "Office Room / Work Area" },
    locationFields: [
      { key: "room_dimensions_openings", label: "Room dimensions, doors, and windows", type: "text" },
      { key: "existing_power_data", label: "Existing power and data locations", type: "text" },
      { key: "desk_storage_needs", label: "Desk, storage, and equipment needs", type: "text", customerVisible: true },
      { key: "finish_and_material", label: "Material and finish selections", type: "text", customerVisible: true },
      { key: "trade_scope", label: "Electrical, low-voltage, paint, or floor scope", type: "text" },
      { key: "occupancy_access", label: "Room occupancy and home access", type: "text", sensitive: true },
      { key: "approved_plan_revision", label: "Approved room-plan revision", type: "text", customerVisible: true },
    ],
    assets: [{ key: "office_built_in", label: "Office built-in", pluralLabel: "Office built-ins", fields: [
      { key: "component_and_material", label: "Desk, storage, and material details", type: "text", customerVisible: true },
      { key: "finish_and_hardware", label: "Finish and hardware", type: "text", customerVisible: true },
      { key: "product_documents", label: "Product and care document references", type: "text" },
    ] }],
    services: [
      { key: "office-consult", name: "Home Office Consultation and Measure", kind: "add_on" },
      { key: "office-built-ins", name: "Custom Desk and Storage Built-Ins", kind: "one_time", defaultEnabled: true },
      { key: "office-carpentry", name: "Home Office Carpentry", kind: "one_time" },
      { key: "office-room-renovation", name: "Home Office Room Renovation Coordination", kind: "one_time" },
      { key: "office-install", name: "Delivery and Installation", kind: "add_on" },
      { key: "office-punch", name: "Punch or Adjustment Visit", kind: "recovery" },
    ],
    formSteps: [
      { key: "room", label: "Describe the room and how you work", fields: ["room_dimensions_openings", "work_style", "equipment", "photos_or_plans"] },
      { key: "built-ins", label: "Share desk and storage needs", fields: ["desk_storage_needs", "material_and_finish", "cable_management", "approved_plan_revision"] },
      { key: "trades", label: "Clarify room and trade scope", fields: ["existing_power_data", "trade_scope", "flooring_or_paint", "permit_or_trade_review"] },
      { key: "site", label: "Arrange a measure and discuss room access", fields: ["occupancy_access", "site_measure", "schedule"] },
    ],
    jobChecklist: [
      { key: "existing-condition", label: "Record room condition, equipment, and service routes", required: true },
      { key: "approved-scope", label: "Confirm approved plan, selections, and included or excluded trades", required: true },
      { key: "trade-ready", label: "Record required trade work and room readiness", required: true },
      { key: "install-and-clearance", label: "Install built-ins and check agreed fit, operation, and clearances", required: true },
      { key: "test-and-punch", label: "Record agreed feature checks, finish photos, and punch handoff", required: true },
    ],
    noncompletionReasons: [
      { key: "design-change", label: "Room plan or selection change needs approval", billableByDefault: false },
      { key: "power-data-work", label: "Power or data work is not ready", billableByDefault: false },
      { key: "material-fabrication", label: "Material or built-in fabrication is delayed", billableByDefault: false },
      { key: "hidden-room-condition", label: "Hidden wall, floor, or service condition needs review", billableByDefault: false },
      { key: "room-access", label: "Occupied room or property access is unavailable", billableByDefault: false },
      { key: "trade-delay", label: "Painting, flooring, or other trade is not ready", billableByDefault: false },
    ],
    workflows: {
      carpentry_scope: ["inquiry", "room_measure", "design_and_materials", "proposal", "approval", "fabrication_or_procurement", "delivery", "built_in_install", "finish_and_punch", "handover"],
      full_room: ["consultation", "room_plan", "scope_and_responsibility", "estimate_and_approval", "trade_sequence", "rough_in", "fabrication", "carpentry_and_finishes", "test_and_inspect", "punch_and_closeout"],
    },
    reports: [
      { key: "plan-and-approval", name: "Room plan approval and project aging", coreMetric: "project_age", dimensions: ["service", "scope_type"] },
      { key: "trade-and-milestones", name: "Trade and milestone variance", coreMetric: "schedule_variance", dimensions: ["responsible_party", "stage"] },
      { key: "changes-and-punch", name: "Change and punch outcomes", coreMetric: "job_outcomes", dimensions: ["service", "cause"] },
    ],
    pricingTemplates: [
      { key: "built-in-scope", name: "Built-in dimensions and complexity", stage: "quantity", inputFields: ["linear_length", "cabinet_count", "desk_size", "design_complexity"], effect: "per_unit", requiresTenantAmount: true },
      { key: "wood-finish-hardware", name: "Materials, finish, and hardware", stage: "add_on", inputFields: ["wood_or_panel", "finish", "hardware", "cable_grommets"], effect: "add_fixed", requiresTenantAmount: true },
      { key: "room-and-trade", name: "Room preparation and trade scope", stage: "add_on", inputFields: ["demolition", "electrical", "data", "paint", "flooring"], effect: "add_fixed", requiresTenantAmount: true },
      { key: "delivery-install", name: "Delivery, access, and installation", stage: "add_on", inputFields: ["delivery", "access", "installation", "disposal"], effect: "add_fixed", requiresTenantAmount: true },
    ],
    recommendationQuestions: [
      { key: "work_scope", prompt: "Do you build office carpentry only or manage a whole-room renovation?", answerType: "enum", options: ["carpentry_only", "full_room", "both"] },
      { key: "shop_fabrication", prompt: "Do you design or fabricate built-ins in your own shop?", answerType: "boolean" },
      { key: "trade_partners", prompt: "Do you coordinate electrical, data, flooring, or painting trades?", answerType: "boolean" },
      { key: "staffed_projects", prompt: "Do employees or regular crews work on projects?", answerType: "boolean" },
    ],
    productCapabilityRecommendations: [
      { featureKey: "estimate_management", recommendation: "normally_recommended", rationale: "Room scope, selections, trade allowances, and approved changes shape the proposal." },
      { featureKey: "service_scheduling", recommendation: "normally_recommended", rationale: "Design, fabrication, room preparation, trade work, and installation need milestone coordination." },
      { featureKey: "field_job_tracking", recommendation: "normally_recommended", rationale: "Site notes, trade readiness, photos, changes, and punch belong to the project." },
      { featureKey: "invoicing", recommendation: "normally_recommended", rationale: "Project billing follows approved room scope and changes." },
      { featureKey: "time_tracking", recommendation: "optional", rationale: "Job costing is more useful to multi-worker teams than solo fixed-scope carpenters." },
      { featureKey: "inventory_tracking", recommendation: "optional", rationale: "A shop may track material stock; field contractors often purchase for each project." },
      { featureKey: "customer_self_service", recommendation: "optional", rationale: "Photo intake and plan approvals can help while trade and site review stay with staff." },
    ],
    recommendedConnectorCapabilities: ["accounting", "calendar", "storage", "email", "sms", "payments"], inventoryDefaults: [],
    website: { template: "classic", sections: ["hero", "office_projects", "built_in_gallery", "how_it_works", "consultation_request", "contact"], signupSteps: ["room_photos_or_plan", "built_in_or_room_scope", "work_and_storage_needs", "consultation_request", "contact"], heroHeadline: "A home office built around your work", heroDescription: "Tell us whether you need custom built-ins or a broader room update. We will review the room, design choices, and trade scope before confirming a proposal." },
  }),

  projectPack({
    key: "interior-design", displayName: "Interior Design",
    customerTypes: ["homeowner", "commercial_client", "property_developer", "hospitality_client", "retail_business"],
    terminology: { customer: "Client", serviceLocation: "Project Site / Room", job: "Design Project", estimate: "Scope and Fee Proposal", fieldTechnician: "Designer / Project Coordinator", customerAsset: "Selected Product", workArea: "Room / Zone" },
    locationFields: [
      { key: "site_and_room", label: "Site, room, and project use", type: "text", customerVisible: true },
      { key: "measurements_and_photos", label: "Room measurements and photos", type: "text" },
      { key: "design_brief", label: "Client goals, style, and functional brief", type: "text", customerVisible: true },
      { key: "budget_and_allowances", label: "Budget and purchasing allowances", type: "text", sensitive: true },
      { key: "decision_authority", label: "Client decision makers and purchase authority", type: "text", sensitive: true },
      { key: "jurisdiction_and_construction", label: "Jurisdiction and construction scope notes", type: "text" },
    ],
    assets: [{ key: "design_selection", label: "Approved design selection", pluralLabel: "Approved design selections", fields: [
      { key: "product_or_finish", label: "Product, finish, or material", type: "text", customerVisible: true },
      { key: "vendor_and_model", label: "Vendor, model, and SKU", type: "text" },
      { key: "price_and_lead_time", label: "Quoted price and lead time", type: "text" },
      { key: "approval_date_revision", label: "Client approval date and revision", type: "text", customerVisible: true },
      { key: "care_and_warranty", label: "Care and warranty document reference", type: "text" },
    ] }],
    services: [
      { key: "design-consult", name: "Design Consultation", kind: "one_time", defaultEnabled: true },
      { key: "space-planning", name: "Space Planning and Concept Design", kind: "one_time" },
      { key: "e-design", name: "Remote or E-Design Package", kind: "one_time" },
      { key: "selection-specification", name: "Merchandise Selection and Specification", kind: "one_time" },
      { key: "purchasing", name: "Purchasing and Vendor Coordination", kind: "add_on" },
      { key: "project-administration", name: "Project Administration and Installation Coordination", kind: "add_on" },
    ],
    formSteps: [
      { key: "brief", label: "Share the project brief and rooms", fields: ["project_type", "site_and_room", "measurements_and_photos", "desired_function"] },
      { key: "scope", label: "Choose the services you need", fields: ["design_deliverables", "purchasing_scope", "project_administration", "construction_scope"] },
      { key: "budget", label: "Set project budget and decision process", fields: ["budget_and_allowances", "decision_authority", "target_dates"] },
      { key: "consult", label: "Arrange a discovery consultation", fields: ["consultation_request", "existing_items", "jurisdiction_and_construction"] },
    ],
    jobChecklist: [
      { key: "contract-and-authority", label: "Confirm signed scope, fee basis, decision authority, and purchasing role", required: true },
      { key: "brief-and-site", label: "Record brief, measurements, site constraints, and existing conditions", required: true },
      { key: "concept-approval", label: "Record client-approved concept and revision", required: true },
      { key: "selection-approval", label: "Obtain approval of product, price, allowance, and lead time before purchase", required: true },
      { key: "delivery-and-punch", label: "Record delivery or installation issues, punch, and client handoff", required: true },
    ],
    noncompletionReasons: [
      { key: "client-decision", label: "Client decision or selection is pending", billableByDefault: false },
      { key: "scope-or-fee-change", label: "Scope or compensation needs a signed change", billableByDefault: false },
      { key: "vendor-lead-time", label: "Vendor stock, lead time, or delivery is delayed", billableByDefault: false },
      { key: "site-not-ready", label: "Construction or installation site is not ready", billableByDefault: false },
      { key: "damaged-or-substitute", label: "Delivered item is damaged or needs substitution approval", billableByDefault: false },
      { key: "qualified-consultant", label: "Regulated or technical work needs a qualified professional", billableByDefault: false },
    ],
    workflows: {
      consultation_or_e_design: ["lead", "discovery", "brief_and_inputs", "scope_and_fee_proposal", "contract", "concept", "client_approval", "deliverables", "closeout"],
      full_service: ["lead", "site_survey", "contract_and_deposit", "concept_and_revisions", "selection_approval", "specification", "purchasing_authority", "vendor_orders", "delivery_and_site_coordination", "installation_and_punch", "care_and_closeout"],
    },
    reports: [
      { key: "proposal-and-conversion", name: "Proposal conversion by service scope", coreMetric: "proposal_conversion", dimensions: ["service", "customer_type"] },
      { key: "decision-and-orders", name: "Client decision aging and vendor lead time", coreMetric: "schedule_variance", dimensions: ["project_stage", "vendor"] },
      { key: "fee-and-punch", name: "Project fees, changes, and punch closeout", coreMetric: "project_margin", dimensions: ["compensation_type", "service"] },
    ],
    pricingTemplates: [
      { key: "design-fee", name: "Design scope and compensation", stage: "base", inputFields: ["service_scope", "room_count", "deliverables", "phase", "revision_rounds"], effect: "add_fixed", requiresTenantAmount: true },
      { key: "time-or-retainer", name: "Hourly, retainer, or project fee", stage: "quantity", inputFields: ["hours", "retainer", "project_fee", "milestones"], effect: "per_unit", requiresTenantAmount: true },
      { key: "purchasing-admin", name: "Purchasing and project administration", stage: "add_on", inputFields: ["purchasing", "vendor_coordination", "site_visits", "installation_admin"], effect: "add_fixed", requiresTenantAmount: true },
      { key: "consultants-and-travel", name: "Consultants, travel, and project complexity", stage: "add_on", inputFields: ["consultant_scope", "travel", "commercial_complexity"], effect: "add_fixed", requiresTenantAmount: true },
    ],
    recommendationQuestions: [
      { key: "project_mix", prompt: "Do you work primarily on residential, commercial, or both?", answerType: "enum", options: ["residential", "commercial", "both"] },
      { key: "service_scope", prompt: "Do you offer e-design, full-service design, purchasing, or combinations?", answerType: "enum", options: ["e_design", "full_service", "design_and_purchasing", "mixed"] },
      { key: "purchasing_authority", prompt: "Do clients authorize you to place orders on their behalf?", answerType: "boolean" },
      { key: "fee_model", prompt: "Do you bill hourly or track time against projects?", answerType: "boolean" },
    ],
    productCapabilityRecommendations: [
      { featureKey: "estimate_management", recommendation: "normally_recommended", rationale: "Design scope, deliverables, compensation, and revisions belong in a written proposal." },
      { featureKey: "service_scheduling", recommendation: "normally_recommended", rationale: "Consultations, surveys, approvals, deliveries, and installation coordination are milestone-based." },
      { featureKey: "customer_notifications", recommendation: "normally_recommended", rationale: "Clients need clear requests for decisions, selections, orders, delivery, and schedule changes." },
      { featureKey: "invoicing", recommendation: "normally_recommended", rationale: "Design fees and project compensation need records separate from merchandise decisions." },
      { featureKey: "payment_collection", recommendation: "normally_recommended", rationale: "Contract-specific deposits and design payments need a clear customer record." },
      { featureKey: "time_tracking", recommendation: "optional", rationale: "Useful for hourly or time-costed engagements but not universal for fixed-fee projects." },
      { featureKey: "inventory_tracking", recommendation: "usually_unnecessary", rationale: "Selected products are often client purchases or vendor stock; display samples vary by studio." },
      { featureKey: "online_booking", recommendation: "optional", rationale: "A discovery consultation can be booked, while project scope and procurement need review." },
    ],
    recommendedConnectorCapabilities: ["calendar", "email", "storage", "payments", "accounting", "crm_import"], inventoryDefaults: [],
    website: { template: "classic", sections: ["hero", "services", "design_portfolio", "our_process", "consultation_request", "contact"], signupSteps: ["project_type", "rooms_and_photos", "desired_services", "budget_and_timing", "consultation_request"], heroHeadline: "Spaces shaped around the people who use them", heroDescription: "Tell us about your rooms, goals, and the design services you need. We will arrange a discovery consultation and define scope before starting a project." },
  }),

  projectPack({
    key: "mirror-installation", displayName: "Mirror Installation",
    customerTypes: ["homeowner", "remodeler", "interior_designer", "gym_or_studio", "builder", "commercial_property"],
    terminology: { customer: "Customer / Client", serviceLocation: "Property / Room", job: "Mirror Project", estimate: "Measured Quote", fieldTechnician: "Glass Handling / Install Crew", customerAsset: "Installed Mirror", workArea: "Room / Wall" },
    locationFields: [
      { key: "room_and_panel_count", label: "Room, use, and number of panels", type: "text" },
      { key: "wall_measurements", label: "Wall dimensions and field-measure notes", type: "text" },
      { key: "substrate_and_plumb", label: "Wall surface, substrate, and plumb notes", type: "text" },
      { key: "cutouts_and_obstructions", label: "Outlets, fixtures, and cutout locations", type: "text" },
      { key: "handling_access", label: "Fragile-panel handling and access route", type: "text", sensitive: true },
      { key: "moisture_or_impact", label: "Moisture or impact exposure notes", type: "text" },
      { key: "approved_drawing", label: "Approved panel drawing or template", type: "text", customerVisible: true },
    ],
    assets: [{ key: "mirror_assembly", label: "Installed mirror assembly", pluralLabel: "Installed mirror assemblies", fields: [
      { key: "panel_dimensions", label: "Panel dimensions and glass details", type: "text" },
      { key: "edge_and_backing", label: "Edge and backing selection", type: "text", customerVisible: true },
      { key: "mounting_approach", label: "Mounting approach and product reference", type: "text" },
      { key: "fabrication_source", label: "Fabrication source and order reference", type: "text" },
      { key: "installation_and_warranty", label: "Install date and warranty notes", type: "text" },
    ] }],
    services: [
      { key: "custom-mirror", name: "Custom Mirror Measure and Installation", kind: "one_time", defaultEnabled: true },
      { key: "stock-mirror-hang", name: "Stock Mirror Hanging", kind: "one_time" },
      { key: "gym-mirror", name: "Gym or Studio Mirror Panels", kind: "one_time" },
      { key: "mirror-removal-replacement", name: "Mirror Removal and Replacement", kind: "one_time" },
      { key: "mirror-repair", name: "Mirror Re-securing or Repair Visit", kind: "recovery" },
    ],
    formSteps: [
      { key: "project", label: "Tell us about the room and mirror", fields: ["room_use", "panel_count", "photos_whole_wall", "approximate_dimensions"] },
      { key: "surface", label: "Share wall, fixtures, and access details", fields: ["substrate_and_plumb", "cutouts_and_obstructions", "handling_access", "moisture_or_impact"] },
      { key: "selections", label: "Choose glass, edge, backing, and cutouts", fields: ["glass_type", "edge_finish", "backing", "approved_drawing"] },
      { key: "measure", label: "Arrange a site measure and quote", fields: ["site_survey", "removal_scope", "installation_request"] },
    ],
    jobChecklist: [
      { key: "survey-and-drawing", label: "Verify field dimensions, substrate, and approved panel drawing", required: true },
      { key: "glass-order", label: "Confirm glass, edge, backing, cutouts, and fabrication approval", required: true },
      { key: "delivery-and-handling", label: "Inspect delivered panels and confirm crew and handling readiness", required: true },
      { key: "protect-and-mount", label: "Protect the room and install to the approved product and mounting plan", required: true },
      { key: "alignment-and-acceptance", label: "Record alignment, finish, customer acceptance, and care handoff", required: true },
    ],
    noncompletionReasons: [
      { key: "dimension-mismatch", label: "Measurement or fabrication dimension needs review", billableByDefault: false },
      { key: "panel-damage", label: "Delivered glass is damaged or incomplete", billableByDefault: false },
      { key: "wall-condition", label: "Wall or substrate needs review before mounting", billableByDefault: false },
      { key: "handling-access", label: "Panel handling or access conditions are unsuitable", billableByDefault: false },
      { key: "out-of-scope-repair", label: "Electrical or wall repair is outside approved scope", billableByDefault: false },
      { key: "fabrication-delay", label: "Fabrication or delivery is delayed", billableByDefault: false },
    ],
    workflows: {
      custom_fabricated: ["inquiry_and_photos", "site_survey", "measured_quote", "glass_and_drawing_approval", "fabrication", "delivery_inspection", "installation", "walkthrough_and_photos", "closeout"],
      stock_or_replacement: ["inquiry", "scope_and_access_review", "estimate", "approval", "schedule", "remove_or_hang", "inspect", "closeout"],
    },
    reports: [
      { key: "survey-to-install", name: "Survey-to-install lead time", coreMetric: "schedule_variance", dimensions: ["service", "project_type"] },
      { key: "first-visit-and-damage", name: "First-visit completion and fabrication damage", coreMetric: "job_outcomes", dimensions: ["crew", "cause"] },
      { key: "quote-variance", name: "Estimate variance and job margin", coreMetric: "job_margin", dimensions: ["panel_type", "service"] },
    ],
    pricingTemplates: [
      { key: "panel-and-area", name: "Panel count, dimensions, and glass", stage: "quantity", inputFields: ["panel_count", "area", "thickness", "glass_type"], effect: "per_unit", requiresTenantAmount: true },
      { key: "edge-cutout-backing", name: "Edges, cutouts, backing, and finish", stage: "add_on", inputFields: ["edgework", "cutouts", "safety_backing", "finish"], effect: "add_fixed", requiresTenantAmount: true },
      { key: "mounting-and-removal", name: "Mounting, removal, and wall preparation", stage: "add_on", inputFields: ["mounting", "removal", "wall_preparation", "disposal"], effect: "add_fixed", requiresTenantAmount: true },
      { key: "access-and-crew", name: "Delivery, access, handling, and crew", stage: "add_on", inputFields: ["stairs_or_elevator", "lift", "crew_size", "delivery"], effect: "add_fixed", requiresTenantAmount: true },
    ],
    recommendationQuestions: [
      { key: "fabrication_model", prompt: "Do you fabricate custom mirrors, install stock mirrors, or both?", answerType: "enum", options: ["custom_fabrication", "stock_install", "both"] },
      { key: "commercial_work", prompt: "Do you serve gyms, studios, builders, or commercial sites?", answerType: "boolean" },
      { key: "crew_size", prompt: "Do larger panels require a second installer or specialist crew?", answerType: "boolean" },
      { key: "stock_materials", prompt: "Do you carry standard mirrors or mounting hardware in stock?", answerType: "boolean" },
    ],
    productCapabilityRecommendations: [
      { featureKey: "estimate_management", recommendation: "normally_recommended", rationale: "Custom dimensions, glass, cutouts, substrate, access, and handling shape each quote." },
      { featureKey: "service_scheduling", recommendation: "normally_recommended", rationale: "Survey, fabrication, delivery, and installation need coordinated appointments." },
      { featureKey: "field_job_tracking", recommendation: "normally_recommended", rationale: "Install crews need room measurements, wall notes, access, and completion evidence." },
      { featureKey: "customer_notifications", recommendation: "normally_recommended", rationale: "Clients need survey, fabrication, delivery, and installation updates." },
      { featureKey: "invoicing", recommendation: "normally_recommended", rationale: "A measured project quote and closeout need a billing record." },
      { featureKey: "payment_collection", recommendation: "optional", rationale: "Deposit and final payment practices are not uniform across installers." },
      { featureKey: "inventory_tracking", recommendation: "optional", rationale: "Useful for stocking standard panels or hardware; custom fabrication may be supplier-specific." },
      { featureKey: "route_planning", recommendation: "usually_unnecessary", rationale: "Project survey and install appointments dominate over dense recurring routes." },
    ],
    recommendedConnectorCapabilities: ["calendar", "email", "sms", "payments", "accounting", "storage"], inventoryDefaults: [],
    website: { template: "classic", sections: ["hero", "mirror_services", "project_gallery", "measure_process", "quote_request", "contact"], signupSteps: ["room_photos", "approximate_dimensions", "panel_and_finish_options", "access_details", "measure_request"], heroHeadline: "Mirrors fitted to your room and project", heroDescription: "Share wall photos, approximate dimensions, and the mirror style you have in mind. We will confirm a site measure and installation scope." },
  }),

  projectPack({
    key: "murphy-bed-building-installation-nyc", displayName: "Murphy Bed Building and Installation (NYC)",
    customerTypes: ["homeowner", "renter", "landlord", "designer", "millwork_shop", "furniture_installer", "developer"],
    terminology: { customer: "Client / Resident", serviceLocation: "NYC Property / Unit", job: "Wall-Bed Project", estimate: "Product or Custom Proposal", fieldTechnician: "Design / Delivery / Install Team", customerAsset: "Wall-Bed System", workArea: "Room / Mounting Wall" },
    locationFields: [
      { key: "room_dimensions_clearance", label: "Room dimensions and bed clearances", type: "text" },
      { key: "wall_floor_notes", label: "Wall, floor, and observed substrate notes", type: "text" },
      { key: "building_access", label: "Building, elevator, loading, and access rules", type: "text", sensitive: true },
      { key: "building_reservations", label: "Building approval, reservation, or insurance status", type: "text" },
      { key: "landlord_or_board", label: "Landlord or board approval notes", type: "text" },
      { key: "approved_layout_revision", label: "Approved layout and drawing revision", type: "text", customerVisible: true },
      { key: "delivery_access_window", label: "Delivery and installation access window", type: "text" },
    ],
    assets: [{ key: "wall_bed_system", label: "Installed wall-bed system", pluralLabel: "Installed wall-bed systems", fields: [
      { key: "catalog_or_custom", label: "Catalog model or custom build", type: "enum", options: ["catalog", "custom", "mixed"], customerVisible: true },
      { key: "bed_orientation_size", label: "Orientation and bed size", type: "text", customerVisible: true },
      { key: "mechanism_and_model", label: "Mechanism and product model", type: "text" },
      { key: "cabinet_and_finish", label: "Cabinet configuration and finish", type: "text", customerVisible: true },
      { key: "anchor_and_manual", label: "Anchor/product manual reference", type: "text" },
      { key: "operation_handoff", label: "Function check and operating handoff", type: "text" },
      { key: "warranty_notes", label: "Warranty notes", type: "text" },
    ] }],
    services: [
      { key: "catalog-bed-install", name: "Catalog Wall-Bed Assembly and Installation", kind: "one_time", defaultEnabled: true },
      { key: "custom-wall-bed", name: "Custom Wall-Bed Design and Build", kind: "one_time" },
      { key: "bed-cabinetry", name: "Integrated Storage or Office Cabinetry", kind: "add_on" },
      { key: "bed-move-reinstall", name: "Wall-Bed Move or Reinstallation", kind: "one_time" },
      { key: "bed-repair", name: "Mechanism Adjustment or Repair Visit", kind: "recovery" },
    ],
    formSteps: [
      { key: "product", label: "Tell us whether you have a kit or custom project", fields: ["catalog_or_custom", "product_model", "bed_orientation_size", "who_supplies_product"] },
      { key: "room", label: "Share room dimensions and photos", fields: ["room_dimensions_clearance", "wall_floor_notes", "ceiling_and_trim", "power_or_obstructions"] },
      { key: "custom-design", label: "Plan any cabinetry, desk, or finish options", fields: ["cabinet_and_finish", "storage_options", "approved_layout_revision"] },
      { key: "building", label: "Prepare building access and installation", fields: ["building_access", "building_reservations", "landlord_or_board", "delivery_access_window"] },
    ],
    jobChecklist: [
      { key: "model-and-instructions", label: "Confirm product model, approved layout, and manufacturer instructions", required: true },
      { key: "room-and-building", label: "Verify room measurements, clearances, and building access", required: true },
      { key: "parts-and-protection", label: "Check delivered parts and protect the occupied apartment", required: true },
      { key: "mount-and-operate", label: "Record installation approach and agreed mechanism operation checks", required: true },
      { key: "demonstrate-and-handoff", label: "Demonstrate operation and record customer acceptance and warranty handoff", required: true },
    ],
    noncompletionReasons: [
      { key: "model-or-parts", label: "Product model or required parts are unresolved", billableByDefault: false },
      { key: "room-measure", label: "Room measurement or clearance needs review", billableByDefault: false },
      { key: "wall-review", label: "Wall or mounting conditions need qualified review", billableByDefault: false },
      { key: "building-access", label: "Elevator, loading, or building access is unavailable", billableByDefault: false },
      { key: "approval-pending", label: "Landlord, board, or building approval is pending", billableByDefault: false },
      { key: "shipment-or-finish", label: "Shipment damage, missing hardware, or finish issue needs review", billableByDefault: false },
    ],
    workflows: {
      catalog_installation: ["inquiry", "model_and_manual_review", "room_and_access_check", "estimate", "approval", "product_delivery", "building_reservation", "assembly_and_mounting", "operation_check", "demonstration_and_closeout"],
      custom_wall_bed: ["inquiry", "site_measure", "design_and_options", "drawing_and_finish_approval", "estimate_and_deposit", "fabrication_or_order", "building_and_delivery_coordination", "installation", "operation_walkthrough", "punch_and_warranty"],
    },
    reports: [
      { key: "custom-approval-lead", name: "Custom design approval and production lead time", coreMetric: "project_age", dimensions: ["service", "catalog_or_custom"] },
      { key: "building-access", name: "Building access and delivery blockers", coreMetric: "schedule_variance", dimensions: ["building_type", "cause"] },
      { key: "anchor-callback", name: "Installation callbacks and punch", coreMetric: "job_outcomes", dimensions: ["service", "cause"] },
    ],
    pricingTemplates: [
      { key: "bed-system", name: "Catalog system or custom bed configuration", stage: "base", inputFields: ["catalog_or_custom", "bed_size", "orientation", "mechanism"], effect: "add_fixed", requiresTenantAmount: true },
      { key: "cabinetry-and-finish", name: "Cabinetry, finish, and integrated options", stage: "add_on", inputFields: ["storage", "desk", "lighting", "finish", "hardware"], effect: "add_fixed", requiresTenantAmount: true },
      { key: "delivery-and-building", name: "Delivery, stairs, and building access", stage: "add_on", inputFields: ["delivery", "stairs_or_elevator", "loading_window", "building_requirements"], effect: "add_fixed", requiresTenantAmount: true },
      { key: "assembly-and-install", name: "Assembly, mounting, and reinstallation", stage: "add_on", inputFields: ["assembly", "mounting", "removal", "reinstallation"], effect: "add_fixed", requiresTenantAmount: true },
    ],
    recommendationQuestions: [
      { key: "product_model", prompt: "Do you build custom beds, install catalog kits, or offer both?", answerType: "enum", options: ["custom_build", "catalog_install", "both"] },
      { key: "product_supplied", prompt: "Do you supply the wall-bed system?", answerType: "boolean" },
      { key: "nyc_building_access", prompt: "Do you coordinate NYC building, elevator, loading, or insurance requirements?", answerType: "boolean" },
      { key: "multi_unit_work", prompt: "Do you serve multifamily or repeat development projects?", answerType: "boolean" },
    ],
    productCapabilityRecommendations: [
      { featureKey: "estimate_management", recommendation: "normally_recommended", rationale: "Catalog versus custom scope, cabinetry, access, and installation affect the proposal." },
      { featureKey: "service_scheduling", recommendation: "normally_recommended", rationale: "Room measure, product lead time, building reservations, delivery, and install need coordination." },
      { featureKey: "field_job_tracking", recommendation: "normally_recommended", rationale: "Installers need current room, product, access, and closeout information." },
      { featureKey: "invoicing", recommendation: "normally_recommended", rationale: "Custom and installation work need a record of approved project charges." },
      { featureKey: "customer_self_service", recommendation: "optional", rationale: "Customers can share room photos and approve layouts; mounting suitability still needs staff review." },
      { featureKey: "inventory_tracking", recommendation: "optional", rationale: "Relevant to businesses stocking mechanisms and hardware; custom systems may be ordered per project." },
      { featureKey: "time_tracking", recommendation: "optional", rationale: "Useful for multiple installers or repeated development projects, less so for solo assembly work." },
    ],
    recommendedConnectorCapabilities: ["calendar", "email", "sms", "payments", "accounting", "storage"], inventoryDefaults: [],
    website: { template: "classic", sections: ["hero", "wall_bed_services", "project_gallery", "how_it_works", "measure_request", "contact"], signupSteps: ["catalog_or_custom", "room_photos_and_dimensions", "product_or_design_options", "building_access", "consultation_request"], heroHeadline: "Make room with a wall bed planned for your home", heroDescription: "Tell us whether you have a wall-bed kit or need a custom system. We will review room measurements, building access, and installation needs before confirming the work." },
  }),
];
