import type { IndustryPack } from "../index.ts";

/** Independently configured venue, restoration, event retail, moving, and inspection packs. */
export const RESTORATION_LOGISTICS_PACKS: readonly IndustryPack[] = [
  {
    key: "beer-line-cleaning-keg-tap-services", version: "1.0.0", displayName: "Beer Line Cleaning & Draft System Service",
    customerTypes: ["bar_or_pub", "restaurant", "brewery", "hotel_or_venue", "multi_site_group"],
    terminology: { customer: "Venue account", serviceLocation: "Venue", customerAsset: "Draft system / line", job: "Service stop", servicePlan: "Cleaning cycle", fieldTechnician: "Draft technician" },
    locationFields: [
      { key: "venue_hours", label: "Venue operating hours", type: "text" },
      { key: "service_window", label: "Preferred quiet service window", type: "text" },
      { key: "bar_and_cooler_access", label: "Bar, cellar, and cooler access", type: "text", sensitive: true },
      { key: "water_and_drain_access", label: "Water and drain access", type: "text" },
      { key: "system_map", label: "Draft system or line map", type: "media" },
      { key: "service_zone", label: "Service zone", type: "text", reportable: true },
    ],
    assets: [
      { key: "draft-system", label: "Draft system", pluralLabel: "Draft systems", fields: [
        { key: "system_type", label: "System type", type: "enum", options: ["direct_draw", "long_draw", "glycol", "other"] },
        { key: "line_count", label: "Number of beverage lines", type: "number" },
        { key: "faucet_count", label: "Number of faucets", type: "number" },
        { key: "coupler_count", label: "Number of couplers", type: "number" },
        { key: "beverages", label: "Beverages served", type: "text" },
        { key: "cleaning_interval", label: "Venue's approved cleaning interval", type: "text" },
        { key: "chiller_and_gas_notes", label: "Chiller and gas system notes", type: "text" },
        { key: "last_service", label: "Last documented service", type: "date" },
      ] },
      { key: "draft-line", label: "Draft line", pluralLabel: "Draft lines", fields: [
        { key: "line_identifier", label: "Venue line identifier", type: "text", required: true },
        { key: "beverage", label: "Beverage connected", type: "text" },
        { key: "line_length", label: "Approximate line length", type: "number" },
        { key: "line_diameter", label: "Line diameter", type: "text" },
        { key: "faucet_or_coupler", label: "Faucet or coupler details", type: "text" },
        { key: "prior_defects", label: "Prior leaks, pour, or taste issues", type: "text" },
      ] },
    ],
    services: [
      { key: "scheduled-line-clean", name: "Scheduled beverage line cleaning", kind: "recurring", estimatedMinutes: 45, defaultEnabled: true },
      { key: "faucet-coupler-detail", name: "Faucet and coupler detail service", kind: "add_on", estimatedMinutes: 30 },
      { key: "draft-system-diagnosis", name: "Draft system diagnosis", kind: "one_time", estimatedMinutes: 60 },
      { key: "draft-repair", name: "Tap, line, or coupler repair", kind: "one_time", estimatedMinutes: 60 },
      { key: "system-installation", name: "Draft system installation or change", kind: "one_time", estimatedMinutes: 180 },
      { key: "chiller-maintenance", name: "Glycol / chiller maintenance", kind: "one_time", estimatedMinutes: 90 },
      { key: "emergency-draft-call", name: "Urgent draft system service call", kind: "recovery", estimatedMinutes: 90 },
    ],
    recurrencePresets: [
      { key: "weekly", label: "Weekly (set to venue policy)", rrule: "FREQ=WEEKLY" },
      { key: "every-two-weeks", label: "Every two weeks (set to venue policy)", rrule: "FREQ=WEEKLY;INTERVAL=2" },
      { key: "quarterly-detail", label: "Quarterly detail reminder", rrule: "FREQ=MONTHLY;INTERVAL=3" },
      { key: "custom-cycle", label: "Custom venue or jurisdiction cycle", custom: true },
    ],
    formSteps: [
      { key: "venue", label: "Tell us about the venue", fields: ["venue_type", "service_address", "venue_hours", "service_window", "service_zone"] },
      { key: "draft-system", label: "Describe the draft system", fields: ["system_type", "line_count", "faucet_count", "coupler_count", "beverages", "system_map"] },
      { key: "service", label: "Choose cleaning or technical service", fields: ["service", "cleaning_interval", "existing_maintenance", "emergency_symptoms"] },
      { key: "access-quote", label: "Plan access and review the quote", fields: ["bar_and_cooler_access", "water_and_drain_access", "preferred_window", "quote_request"] },
    ],
    jobChecklist: [
      { key: "confirm-system-lines", label: "Identify the system and lines included in the approved work", required: true },
      { key: "confirm-venue-window", label: "Confirm service access and any venue operating restrictions", required: true },
      { key: "record-process-reference", label: "Record the tenant-approved process and chemical reference", required: true },
      { key: "record-ppe-process", label: "Record applicable PPE and process steps used", required: true },
      { key: "record-contact-rinse", label: "Record contact-time and rinse / purge checks required by the selected process", required: true },
      { key: "restore-test-defects", label: "Restore system, check pour, and record defects or follow-up quote", required: true },
      { key: "next-service-due", label: "Set the next service due date from the venue's selected cycle", required: true },
    ],
    noncompletionReasons: [
      { key: "venue-no-access", label: "No venue or system access", billableByDefault: false },
      { key: "venue-not-ready", label: "Venue not ready for service window", billableByDefault: false },
      { key: "system-needs-repair", label: "System issue requires diagnosis or approved repair", billableByDefault: false },
      { key: "process-material-unavailable", label: "Approved process reference or material unavailable", billableByDefault: false },
      { key: "unsafe-work-condition", label: "Unsafe or unsuitable work condition", billableByDefault: false },
      { key: "customer-change-approval", label: "Additional work awaits account approval", billableByDefault: false },
    ],
    workflows: {
      recurringStop: ["due", "scheduled", "system_confirmed", "cleaning_in_progress", "checks_recorded", "completed", "next_due_set"],
      technicalCall: ["reported", "triaged", "site_survey", "estimate", "approved", "parts_or_equipment", "scheduled", "tested_and_closed"],
      repairApproval: ["defect_recorded", "quote_prepared", "awaiting_venue_approval", "approved", "completed_or_referred"],
    },
    defaultAutomations: [],
    reports: [
      { key: "due-lines", name: "Draft systems and lines due for service", coreMetric: "service_due", dimensions: ["venue", "line_identifier", "cleaning_interval"] },
      { key: "route-stops", name: "Completed venue stops by service zone", coreMetric: "job_outcomes", dimensions: ["service_zone", "service"] },
      { key: "draft-defects", name: "Recorded defects and repair follow-ups", coreMetric: "follow_up_work", dimensions: ["venue", "service"] },
      { key: "quote-conversion", name: "Repair and installation quote conversion", coreMetric: "estimate_conversion", dimensions: ["service", "service_zone"] },
    ],
    pricingTemplates: [
      { key: "account-minimum", name: "Tenant-set venue service minimum", stage: "base", inputFields: ["service", "system_type"], effect: "set_base_amount", requiresTenantAmount: true },
      { key: "line-count", name: "Included and additional beverage lines", stage: "quantity", inputFields: ["line_count", "faucet_count", "coupler_count"], effect: "add_variable", requiresTenantAmount: true },
      { key: "cycle-frequency", name: "Contracted service cycle", stage: "quantity", inputFields: ["cleaning_interval"], effect: "add_variable", requiresTenantAmount: true },
      { key: "technical-parts", name: "Approved repair parts or installation", stage: "add_on", inputFields: ["repair_scope", "parts"], effect: "add_fixed", requiresTenantAmount: true },
      { key: "travel-zone", name: "Travel by service zone", stage: "zone", inputFields: ["service_zone"], effect: "add_fixed", requiresTenantAmount: true },
    ],
    recommendationQuestions: [
      { key: "has_recurring_venue_accounts", prompt: "Do you maintain recurring bar, restaurant, brewery, or venue accounts?", answerType: "boolean" },
      { key: "services_technical_systems", prompt: "Do you also diagnose, repair, or install draft systems?", answerType: "boolean" },
      { key: "services_chillers_or_gas", prompt: "Do you service glycol chillers or gas equipment?", answerType: "boolean" },
      { key: "many_daily_stops", prompt: "Do technicians make several venue stops in a typical day?", answerType: "boolean" },
      { key: "stocks_parts_and_chemicals", prompt: "Do you track repair parts or cleaning supplies?", answerType: "boolean" },
      { key: "has_field_staff", prompt: "Do employees perform service visits?", answerType: "boolean" },
    ],
    productCapabilityRecommendations: [
      { featureKey: "service_scheduling", recommendation: "normally_recommended", rationale: "Per-venue system cleaning cycles need due dates and quiet service windows." },
      { featureKey: "field_job_tracking", recommendation: "normally_recommended", rationale: "Technicians record lines serviced, process checks, defects, and service history." },
      { featureKey: "route_planning", recommendation: "normally_recommended", rationale: "Recurring venue stops benefit from geographic route coordination." },
      { featureKey: "estimate_management", recommendation: "normally_recommended", rationale: "System surveys and repair or installation scope need customer review." },
      { featureKey: "invoicing", recommendation: "normally_recommended", rationale: "Recurring agreements and parts work need clear service billing." },
      { featureKey: "payment_collection", recommendation: "normally_recommended", rationale: "Accounts need a convenient way to pay service invoices." },
      { featureKey: "inventory_tracking", recommendation: "optional", rationale: "Track parts, chemicals, and supplies when they are managed beyond basic van stock.", rules: [{ when: { op: "equals", answerKey: "stocks_parts_and_chemicals", value: true }, recommendation: "normally_recommended" }] },
      { featureKey: "time_tracking", recommendation: "optional", rationale: "Job time supports labor costing when employees make service visits.", rules: [{ when: { op: "equals", answerKey: "has_field_staff", value: true }, recommendation: "normally_recommended" }] },
      { featureKey: "recurring_service_management", recommendation: "normally_recommended", rationale: "Cleaning is sold on account-specific cycles that vary by venue policy and jurisdiction." },
      { featureKey: "customer_notifications", recommendation: "normally_recommended", rationale: "Venue contacts need scheduling, outage, completion, and repair update messages." },
      { featureKey: "website_publishing", recommendation: "optional", rationale: "A site can explain service areas and request a draft system survey." },
    ],
    recommendedConnectorCapabilities: ["calendar", "routing", "geocoding", "email", "sms", "accounting", "payments", "storage"],
    inventoryDefaults: [
      { key: "line-cleaning-solution", name: "Tenant-approved line cleaning solution", unit: "container" },
      { key: "ppe", name: "Protective equipment", unit: "set" },
      { key: "cleaning-hose-adapter", name: "Cleaning hoses and system adapters", unit: "piece" },
      { key: "faucet-coupler-parts", name: "Faucet, coupler, and seal repair parts", unit: "piece" },
      { key: "process-test-supplies", name: "Process verification supplies", unit: "kit" },
    ],
    website: { template: "route-service", sections: ["hero", "draft-line-cleaning", "system-repairs", "venues-served", "service-area", "service-process", "reviews", "request-survey", "contact"], signupSteps: ["venue", "draft-system", "service", "access-quote"], heroHeadline: "Reliable draft systems for every pour", heroDescription: "Request scheduled line service or a survey for a draft system repair or installation." },
  },
  {
    key: "fire-damage-restoration", version: "1.0.0", displayName: "Fire & Smoke Damage Restoration",
    customerTypes: ["homeowner_or_insured", "property_manager", "commercial_owner", "institution", "adjuster_or_claim_contact"],
    terminology: { customer: "Owner / insured", serviceLocation: "Loss property", customerAsset: "Affected room or contents item", job: "Fire loss project", servicePlan: "Restoration work plan", fieldTechnician: "Restoration team" },
    locationFields: [
      { key: "loss_reference", label: "Customer or claim loss reference", type: "text", sensitive: true },
      { key: "event_date", label: "Reported event date", type: "date" },
      { key: "building_unit", label: "Building and unit", type: "text" },
      { key: "access_security", label: "Property access and security notes", type: "text", sensitive: true },
      { key: "occupancy_coordination", label: "Occupant or displacement coordination", type: "text", sensitive: true },
      { key: "authority_release_notes", label: "Authority or site release notes", type: "text", sensitive: true },
      { key: "utility_and_water_status", label: "Reported utility and firefighting-water status", type: "text" },
    ],
    assets: [
      { key: "affected-area", label: "Affected room or area", pluralLabel: "Affected rooms and areas", fields: [
        { key: "floor_and_room", label: "Floor and room identifier", type: "text", required: true },
        { key: "observed_residue", label: "Observed smoke, soot, or residue condition", type: "text" },
        { key: "odor_observation", label: "Recorded odor observation", type: "text" },
        { key: "surface_materials", label: "Affected surfaces and materials", type: "text" },
        { key: "initial_photos", label: "Initial condition photos", type: "media" },
        { key: "scope_status", label: "Scope status", type: "enum", options: ["not_assessed", "assessed", "proposed", "approved", "work_complete", "needs_review"] },
      ] },
      { key: "contents-item", label: "Contents item", pluralLabel: "Contents items", fields: [
        { key: "item_description", label: "Item description or identifier", type: "text", required: true },
        { key: "origin_room", label: "Room found", type: "text" },
        { key: "preexisting_condition", label: "Recorded pre-existing condition", type: "text" },
        { key: "before_photos", label: "Before-work condition photos", type: "media" },
        { key: "restoration_disposition", label: "Proposed disposition", type: "enum", options: ["evaluate", "clean", "store", "return", "owner_decision", "not_restorable_proposed"] },
        { key: "container_or_location", label: "Container, box, or storage location", type: "text" },
        { key: "custody_notes", label: "Contents custody and transfer notes", type: "text", sensitive: true },
      ] },
    ],
    services: [
      { key: "emergency-secure", name: "Emergency property security and stabilization", kind: "recovery", estimatedMinutes: 120, defaultEnabled: true },
      { key: "fire-loss-assessment", name: "Fire and smoke loss assessment", kind: "one_time", estimatedMinutes: 120 },
      { key: "smoke-soot-cleaning", name: "Structure and surface smoke / soot cleaning", kind: "one_time", estimatedMinutes: 240 },
      { key: "contents-packout", name: "Contents inventory and pack-out", kind: "one_time", estimatedMinutes: 240 },
      { key: "contents-clean-store", name: "Contents cleaning and storage coordination", kind: "one_time", estimatedMinutes: 240 },
      { key: "odor-management", name: "Odor management service", kind: "one_time", estimatedMinutes: 180 },
      { key: "restoration-repairs", name: "Approved restoration repairs", kind: "one_time", estimatedMinutes: 240 },
      { key: "contents-packback", name: "Contents pack-back and reconciliation", kind: "one_time", estimatedMinutes: 180 },
    ],
    recurrencePresets: [{ key: "custom-project-followup", label: "Project follow-up visit", custom: true }],
    formSteps: [
      { key: "loss-intake", label: "Tell us about the reported loss", fields: ["event_date", "loss_reference", "building_unit", "reported_fire_area", "reported_water_impact"] },
      { key: "safe-access", label: "Coordinate property access", fields: ["access_security", "utility_and_water_status", "authority_release_notes", "occupancy_coordination"] },
      { key: "assessment-contents", label: "Assess affected rooms and contents", fields: ["affected_rooms", "residue_observations", "contents_present", "photos"] },
      { key: "scope-approval", label: "Review proposed work and contents decisions", fields: ["work_plan", "contents_disposition", "estimate", "change_approval"] },
    ],
    jobChecklist: [
      { key: "confirm-authority-access", label: "Confirm customer authority and permitted site access", required: true },
      { key: "document-loss-conditions", label: "Document room conditions and source-reported facts", required: true },
      { key: "prepare-reviewed-scope", label: "Record the work plan and approved scope", required: true },
      { key: "inventory-contents-custody", label: "Record contents condition, disposition, and each custody handoff when pack-out applies", required: true },
      { key: "record-work-evidence", label: "Record completed cleaning, odor, and repair work with job evidence", required: true },
      { key: "approve-extra-scope", label: "Obtain documented approval for scope changes before proceeding where required", required: true },
      { key: "packback-signoff", label: "Reconcile returned contents and customer decisions when pack-back applies", required: false },
      { key: "deliver-claim-records", label: "Share selected closeout and claim-support records with authorized recipients", required: true },
    ],
    noncompletionReasons: [
      { key: "authority-access-pending", label: "Site access or release is pending", billableByDefault: false },
      { key: "unsafe-specialty-condition", label: "Condition requires qualified review or specialist referral", billableByDefault: false },
      { key: "owner-contents-decision", label: "Owner decision on contents is pending", billableByDefault: false },
      { key: "adjuster-scope-review", label: "Claim or estimate scope review is pending", billableByDefault: false },
      { key: "additional-damage-found", label: "Additional damage requires assessment and scope approval", billableByDefault: false },
      { key: "trade-or-contents-vendor", label: "Specialty trade or contents vendor is not ready", billableByDefault: false },
    ],
    workflows: {
      fireLoss: ["reported", "access_or_release_review", "inspection", "work_plan", "estimate", "approval", "mitigation", "contents_packout_if_selected", "cleaning_and_repairs", "packback_if_selected", "closeout"],
      contentsCustody: ["identified", "condition_recorded", "owner_disposition_review", "packed", "transferred_or_stored", "treated_if_approved", "returned_or_other_disposition", "reconciled"],
      changeApproval: ["condition_or_scope_change", "supplement_prepared", "owner_or_authorized_contact_review", "approved", "scheduled_or_completed"],
    },
    defaultAutomations: [],
    reports: [
      { key: "fire-loss-stage", name: "Open fire losses by project stage", coreMetric: "open_jobs", dimensions: ["stage", "service", "referral_source"] },
      { key: "contents-custody", name: "Contents inventory and custody status", coreMetric: "contents_items", dimensions: ["disposition", "storage_location", "custody_status"] },
      { key: "scope-changes", name: "Estimate supplements and approval status", coreMetric: "scope_changes", dimensions: ["loss_reference", "approval_status"] },
      { key: "closeout", name: "Restoration closeout and return reconciliation", coreMetric: "job_outcomes", dimensions: ["service", "property_type"] },
    ],
    pricingTemplates: [
      { key: "fire-assessment", name: "Assessment and approved work-plan base", stage: "base", inputFields: ["service", "loss_severity"], effect: "set_base_amount", requiresTenantAmount: true },
      { key: "affected-area-scope", name: "Affected area, surface, and work scope", stage: "quantity", inputFields: ["affected_area", "materials", "approved_scope"], effect: "add_variable", requiresTenantAmount: true },
      { key: "contents-packout", name: "Contents item or container handling", stage: "quantity", inputFields: ["contents_items", "boxes", "handling"], effect: "add_variable", requiresTenantAmount: true },
      { key: "storage-and-equipment", name: "Approved storage and deployed equipment", stage: "add_on", inputFields: ["storage_duration", "equipment_days"], effect: "add_fixed", requiresTenantAmount: true },
      { key: "specialty-trades", name: "Approved specialty trade or repair scope", stage: "add_on", inputFields: ["trade_scope", "materials"], effect: "add_fixed", requiresTenantAmount: true },
    ],
    recommendationQuestions: [
      { key: "offers_contents_packout", prompt: "Do you inventory, clean, store, or return customer contents?", answerType: "boolean" },
      { key: "has_contents_storage", prompt: "Do you operate a contents storage facility?", answerType: "boolean" },
      { key: "offers_reconstruction", prompt: "Do you perform approved reconstruction work?", answerType: "boolean" },
      { key: "offers_after_hours_response", prompt: "Do you provide after-hours loss response?", answerType: "boolean" },
      { key: "handles_commercial_losses", prompt: "Do you handle commercial or institutional properties?", answerType: "boolean" },
      { key: "has_multiple_crews", prompt: "Do you coordinate multiple crews or specialty vendors?", answerType: "boolean" },
    ],
    productCapabilityRecommendations: [
      { featureKey: "field_job_tracking", recommendation: "normally_recommended", rationale: "A loss project spans rooms, tasks, evidence, customers, and claim-facing records." },
      { featureKey: "estimate_management", recommendation: "normally_recommended", rationale: "Room findings and newly discovered conditions can change the proposed scope." },
      { featureKey: "service_scheduling", recommendation: "normally_recommended", rationale: "Security, mitigation, contents, trades, repairs, and return visits need coordination." },
      { featureKey: "invoicing", recommendation: "normally_recommended", rationale: "Owners and authorized claim contacts need clear project charges and records." },
      { featureKey: "customer_notifications", recommendation: "normally_recommended", rationale: "Displaced owners need timely progress, decisions, and access updates." },
      { featureKey: "inventory_tracking", recommendation: "optional", rationale: "Contents item inventory and custody are central when pack-out is offered.", rules: [{ when: { op: "equals", answerKey: "offers_contents_packout", value: true }, recommendation: "normally_recommended" }] },
      { featureKey: "customer_self_service", recommendation: "optional", rationale: "Authorized owners may need access to approved documents and contents decisions." },
      { featureKey: "multi_location_management", recommendation: "optional", rationale: "Multi-property and commercial work can involve several active sites.", rules: [{ when: { op: "equals", answerKey: "handles_commercial_losses", value: true }, recommendation: "normally_recommended" }] },
      { featureKey: "advanced_reporting", recommendation: "optional", rationale: "Project and contents reporting helps larger restoration operations." },
      { featureKey: "route_planning", recommendation: "usually_unnecessary", rationale: "Loss response and multi-trade project sequence usually outrank dense route optimization." },
      { featureKey: "payment_collection", recommendation: "optional", rationale: "Direct customer collection applies by business and claim arrangement." },
      { featureKey: "website_publishing", recommendation: "optional", rationale: "An intake page can route emergency requests to a human coordinator." },
    ],
    recommendedConnectorCapabilities: ["storage", "email", "sms", "payments", "accounting", "calendar"],
    inventoryDefaults: [
      { key: "contents-boxes-labels", name: "Contents cartons and inventory labels", unit: "piece" },
      { key: "ppegeneral", name: "Tenant-selected protective equipment", unit: "set" },
      { key: "air-filtration", name: "Air filtration equipment", unit: "unit" },
      { key: "cleaning-supplies", name: "Tenant-selected restoration cleaning supplies", unit: "kit" },
      { key: "temporary-boardup", name: "Temporary securing materials", unit: "piece" },
    ],
    website: { template: "classic", sections: ["hero", "emergency-contact", "fire-loss-response", "contents-care", "project-process", "insurance-coordination", "service-area", "reviews", "contact"], signupSteps: ["loss-intake", "safe-access", "assessment-contents", "scope-approval"], heroHeadline: "Clear coordination after a fire loss", heroDescription: "Request a restoration assessment and coordinate approved structure, contents, and repair work." },
  },
  {
    key: "mobile-retail-pop-ups", version: "1.0.0", displayName: "Mobile Retail & Pop-up Shops",
    customerTypes: ["independent_retailer", "maker_or_brand", "online_first_seller", "market_vendor", "wholesale_brand"],
    terminology: { customer: "Retail customer", serviceLocation: "Event / selling location", customerAsset: "Retail product / event kit", job: "Retail activation", servicePlan: "Event calendar", fieldTechnician: "Seller / event staff" },
    locationFields: [
      { key: "event_venue", label: "Venue and event address", type: "location", required: true },
      { key: "booth_space", label: "Booth or selling space", type: "text" },
      { key: "event_dates_hours", label: "Event dates and selling hours", type: "text" },
      { key: "load_in_strike", label: "Load-in and teardown rules", type: "text" },
      { key: "power_connectivity", label: "Power and checkout connectivity", type: "text" },
      { key: "organizer_and_approval", label: "Organizer contact and acceptance status", type: "text" },
      { key: "tax_and_permit_notes", label: "Tenant-recorded permit and tax jurisdiction notes", type: "text", sensitive: true },
    ],
    assets: [
      { key: "retail-product", label: "Retail product", pluralLabel: "Retail products", fields: [
        { key: "sku", label: "SKU", type: "text", required: true },
        { key: "variant", label: "Size, color, or variant", type: "text" },
        { key: "unit_cost", label: "Tenant-recorded unit cost", type: "number", sensitive: true },
        { key: "retail_price", label: "Tenant-set retail price", type: "number" },
        { key: "stock_quantity", label: "Stock quantity", type: "number" },
        { key: "stock_ownership", label: "Stock ownership", type: "enum", options: ["owned", "consignment", "other"] },
        { key: "product_image", label: "Product photo", type: "media" },
      ] },
      { key: "event-kit", label: "Event display or checkout item", pluralLabel: "Event display and checkout items", fields: [
        { key: "kit_item", label: "Tent, fixture, signage, or POS item", type: "text", required: true },
        { key: "assigned_event", label: "Assigned event", type: "text" },
        { key: "setup_notes", label: "Setup or power notes", type: "text" },
      ] },
    ],
    services: [
      { key: "market-stall", name: "Market or craft fair activation", kind: "one_time", estimatedMinutes: 360, defaultEnabled: true },
      { key: "festival-pop-up", name: "Festival or community pop-up", kind: "one_time", estimatedMinutes: 480 },
      { key: "brand-activation", name: "Brand or short-term retail activation", kind: "one_time", estimatedMinutes: 480 },
      { key: "wholesale-event", name: "Wholesale or buyer event", kind: "one_time", estimatedMinutes: 360 },
      { key: "online-store-fulfillment", name: "Online order fulfillment from allocated stock", kind: "add_on", estimatedMinutes: 60 },
    ],
    recurrencePresets: [{ key: "event-series", label: "Event series dates", custom: true }, { key: "seasonal-market", label: "Seasonal market dates", custom: true }],
    formSteps: [
      { key: "event", label: "Plan the selling event", fields: ["event_name", "event_venue", "event_dates_hours", "audience", "organizer_and_approval"] },
      { key: "space-logistics", label: "Check space and site logistics", fields: ["booth_space", "load_in_strike", "power_connectivity", "insurance_or_permit_evidence"] },
      { key: "assortment", label: "Plan products and stock", fields: ["product_categories", "sku_variants", "allocated_quantities", "consignment_status"] },
      { key: "settlement", label: "Set up checkout and closeout", fields: ["payment_method", "online_channel", "returns_policy", "event_costs"] },
    ],
    jobChecklist: [
      { key: "confirm-event-acceptance", label: "Confirm organizer acceptance and event terms", required: true },
      { key: "check-local-requirements", label: "Record the seller's permit and venue requirement checks", required: true },
      { key: "allocate-event-stock", label: "Allocate products and variants to this selling location", required: true },
      { key: "pack-and-setup", label: "Pack and set up the assigned display and checkout kit", required: true },
      { key: "record-sales-returns", label: "Reconcile sales and returns using the connected or chosen point-of-sale process", required: true },
      { key: "reconcile-remaining-stock", label: "Count, transfer, or return remaining stock and note discrepancies", required: true },
      { key: "settle-event-costs", label: "Record event costs and settlement for the activation", required: true },
    ],
    noncompletionReasons: [
      { key: "organizer-not-accepted", label: "Application not accepted by organizer", billableByDefault: false },
      { key: "event-cancelled", label: "Event cancelled or postponed", billableByDefault: false },
      { key: "permit-or-venue-delay", label: "Venue or seller approval is unresolved", billableByDefault: false },
      { key: "stock-or-kit-shortage", label: "Required stock or display kit unavailable", billableByDefault: false },
      { key: "weather-or-site-issue", label: "Weather or site conditions prevent opening", billableByDefault: false },
      { key: "checkout-connectivity", label: "Checkout connectivity or equipment issue", billableByDefault: false },
    ],
    workflows: {
      eventActivation: ["lead", "application_or_invitation", "awaiting_organizer", "accepted", "event_planned", "stock_allocated", "packed", "selling", "settlement_and_reconciliation", "closed"],
      stockMovement: ["on_hand", "allocated_to_event", "loaded", "available_for_sale", "sold_or_returned", "counted", "restocked_or_transferred"],
      eventSettlement: ["sales_recorded", "returns_recorded", "payment_reconciled", "remaining_stock_counted", "event_costs_entered", "margin_reviewed"],
    },
    defaultAutomations: [],
    reports: [
      { key: "event-sales", name: "Sales and event costs by activation", coreMetric: "event_sales", dimensions: ["event", "venue", "date"] },
      { key: "sku-sell-through", name: "SKU and variant sell-through", coreMetric: "units_sold", dimensions: ["sku", "variant", "event"] },
      { key: "stock-variance", name: "Opening and closing stock variance", coreMetric: "inventory_variance", dimensions: ["sku", "event", "stock_ownership"] },
      { key: "event-margin", name: "Retail activation margin", coreMetric: "event_margin", dimensions: ["event", "venue", "product_category"] },
    ],
    pricingTemplates: [
      { key: "retail-product-price", name: "Tenant-set product and variant price", stage: "base", inputFields: ["sku", "variant", "retail_price"], effect: "set_base_amount", requiresTenantAmount: true },
      { key: "event-costs", name: "Booth, travel, and event labor costs", stage: "add_on", inputFields: ["booth_fee", "travel", "labor"], effect: "track_event_cost", requiresTenantAmount: true },
      { key: "event-promotion", name: "Tenant-approved event promotion", stage: "promotion", inputFields: ["promotion_code", "discount"], effect: "apply_tenant_promotion", requiresTenantAmount: true },
    ],
    recommendationQuestions: [
      { key: "sells_online_too", prompt: "Do you also sell through an online store?", answerType: "boolean" },
      { key: "runs_multiple_events", prompt: "Do you run several events or selling locations at once?", answerType: "boolean" },
      { key: "uses_consignment", prompt: "Do you carry any consigned products?", answerType: "boolean" },
      { key: "sells_regulated_goods", prompt: "Do you sell goods with additional venue or jurisdiction requirements?", answerType: "boolean" },
      { key: "needs_b2b_invoices", prompt: "Do you invoice wholesale buyers or event organizers?", answerType: "boolean" },
      { key: "uses_connected_pos", prompt: "Do you already use a point-of-sale system?", answerType: "boolean" },
    ],
    productCapabilityRecommendations: [
      { featureKey: "inventory_tracking", recommendation: "normally_recommended", rationale: "Products and variants must be allocated, sold, returned, and counted by event." },
      { featureKey: "payment_collection", recommendation: "normally_recommended", rationale: "In-person retail requires checkout through the seller's chosen payment setup." },
      { featureKey: "service_scheduling", recommendation: "optional", rationale: "An event calendar coordinates dates, load-in, shifts, and teardown." },
      { featureKey: "invoicing", recommendation: "optional", rationale: "Consumer checkout usually sits in POS; wholesale and organizer billing may need invoices.", rules: [{ when: { op: "equals", answerKey: "needs_b2b_invoices", value: true }, recommendation: "normally_recommended" }] },
      { featureKey: "multi_location_management", recommendation: "optional", rationale: "Separate event allocations matter when several locations operate together.", rules: [{ when: { op: "equals", answerKey: "runs_multiple_events", value: true }, recommendation: "normally_recommended" }] },
      { featureKey: "customer_records", recommendation: "optional", rationale: "Customer follow-up is useful when shoppers choose to share their details." },
      { featureKey: "customer_notifications", recommendation: "optional", rationale: "Event reminders and location updates can help opted-in shoppers." },
      { featureKey: "website_publishing", recommendation: "normally_recommended", rationale: "A public page can list upcoming pop-ups, event hours, and product categories." },
      { featureKey: "route_planning", recommendation: "optional", rationale: "Location sequencing may help when a brand moves between several events." },
      { featureKey: "field_job_tracking", recommendation: "usually_unnecessary", rationale: "The central workflow is stock, checkout, and settlement at events." },
      { featureKey: "online_booking", recommendation: "usually_unnecessary", rationale: "Retail sales are handled through event checkout or the existing storefront." },
    ],
    recommendedConnectorCapabilities: ["payments", "accounting", "email", "sms", "calendar", "storage", "geocoding", "crm_import"],
    inventoryDefaults: [
      { key: "retail-merchandise", name: "Tenant product catalog and event merchandise", unit: "unit" },
      { key: "display-fixtures", name: "Display fixtures and signage", unit: "piece" },
      { key: "pop-up-canopy", name: "Canopy or trailer kit", unit: "unit" },
      { key: "pos-hardware", name: "POS terminal, scanner, or card reader", unit: "piece" },
      { key: "packing-materials", name: "Product packing and transport supplies", unit: "pack" },
    ],
    website: { template: "fresh", sections: ["hero", "upcoming-events", "featured-products", "online-store", "locations", "returns-policy", "reviews", "contact"], signupSteps: ["event", "space-logistics", "assortment", "settlement"], heroHeadline: "Find us at the next pop-up", heroDescription: "See upcoming markets and retail activations, browse featured products, and check event hours." },
  },
  {
    key: "mold-remediation", version: "1.0.0", displayName: "Mold Remediation",
    customerTypes: ["property_owner", "tenant_or_occupant", "property_manager", "school_or_institution", "commercial_owner", "assessor_or_ieP"],
    terminology: { customer: "Owner / responsible contact", serviceLocation: "Property", customerAsset: "Affected room or assembly", job: "Remediation project", servicePlan: "Remediation work plan", fieldTechnician: "Remediation team" },
    locationFields: [
      { key: "building_unit", label: "Building and unit", type: "text" },
      { key: "occupancy_access", label: "Occupancy and access coordination", type: "text", sensitive: true },
      { key: "reported_moisture_source", label: "Customer-reported moisture source", type: "text" },
      { key: "source_correction_status", label: "Moisture source correction status", type: "text" },
      { key: "hvac_zone", label: "Related HVAC zone or equipment", type: "text" },
      { key: "prior_reports", label: "Prior assessment or work-plan documents", type: "media" },
    ],
    assets: [
      { key: "affected-room", label: "Affected room or assembly", pluralLabel: "Affected rooms and assemblies", fields: [
        { key: "room_identifier", label: "Room, floor, or assembly identifier", type: "text", required: true },
        { key: "material_type", label: "Affected material", type: "text" },
        { key: "reported_symptoms", label: "Customer-reported visible growth or odor", type: "text", sensitive: true },
        { key: "observed_extent", label: "Observed extent and access limits", type: "text" },
        { key: "moisture_observations", label: "Recorded moisture readings or observations", type: "text" },
        { key: "photos", label: "Condition and work photos", type: "media" },
        { key: "protocol_status", label: "Work-plan status", type: "enum", options: ["not_received", "assessment_pending", "received", "reviewed", "scope_approved", "work_complete", "verification_pending"] },
      ] },
    ],
    services: [
      { key: "mold-site-assessment", name: "Site assessment", kind: "one_time", estimatedMinutes: 120, defaultEnabled: true },
      { key: "mold-remediation", name: "Approved mold remediation", kind: "one_time", estimatedMinutes: 240 },
      { key: "containment-setup", name: "Containment setup and removal", kind: "one_time", estimatedMinutes: 120 },
      { key: "selective-removal", name: "Approved selective material removal", kind: "one_time", estimatedMinutes: 180 },
      { key: "hepa-cleaning", name: "HEPA cleaning and surface work", kind: "one_time", estimatedMinutes: 180 },
      { key: "moisture-source-coordination", name: "Moisture source correction coordination", kind: "add_on", estimatedMinutes: 90 },
      { key: "contents-handling", name: "Affected contents handling coordination", kind: "add_on", estimatedMinutes: 120 },
      { key: "post-work-verification", name: "Post-work verification coordination", kind: "one_time", estimatedMinutes: 90 },
    ],
    recurrencePresets: [{ key: "project-return-visit", label: "Project return visit", custom: true }],
    formSteps: [
      { key: "concern", label: "Describe the concern", fields: ["service_address", "building_unit", "reported_moisture_source", "reported_symptoms", "affected_rooms"] },
      { key: "reports-access", label: "Share existing reports and access details", fields: ["prior_reports", "occupancy_access", "photos", "landlord_or_owner_authority"] },
      { key: "assessment", label: "Arrange a site assessment", fields: ["service", "room_material_scope", "moisture_observations", "assessment_contact"] },
      { key: "plan-approval", label: "Review work plan and proposed scope", fields: ["protocol_status", "work_plan", "estimate", "change_approval"] },
    ],
    jobChecklist: [
      { key: "confirm-responsible-roles", label: "Record who prepared the assessment or work plan and who is responsible for remediation", required: true },
      { key: "review-prerequisites", label: "Review applicable work-plan, access, and site prerequisites", required: true },
      { key: "record-boundaries", label: "Record affected rooms, observed conditions, and work limits", required: true },
      { key: "document-controls", label: "Record the approved controls, equipment, and PPE selected by qualified staff", required: true },
      { key: "record-material-disposition", label: "Record removed or cleaned material and disposal handoff", required: true },
      { key: "source-correction-followup", label: "Record moisture source status and any separate repair referral", required: true },
      { key: "changed-conditions-approval", label: "Pause changed scope for qualified review and customer approval", required: true },
      { key: "verification-records", label: "Attach verification or independent post-remediation records when obtained", required: false },
    ],
    noncompletionReasons: [
      { key: "assessment-protocol-pending", label: "Assessment, protocol, or prerequisite report is pending", billableByDefault: false },
      { key: "owner-authority-pending", label: "Owner authority or occupant coordination is pending", billableByDefault: false },
      { key: "unsafe-condition-review", label: "Condition requires qualified safety or specialty review", billableByDefault: false },
      { key: "hidden-condition-found", label: "Hidden or changed condition requires reassessment", billableByDefault: false },
      { key: "source-not-corrected", label: "Moisture source correction needs coordination", billableByDefault: false },
      { key: "independent-verification-pending", label: "Independent verification or lab result is pending", billableByDefault: false },
    ],
    workflows: {
      remediationProject: ["inquiry", "assessment_role_review", "site_assessment", "protocol_or_work_plan", "estimate", "approval", "controls_setup", "remediation", "source_correction_or_referral", "closeout", "verification_if_applicable"],
      documentRoles: ["assessment_requested", "assessment_received", "responsible_parties_recorded", "work_scope_reviewed", "customer_authorized", "work_records_attached"],
      changeReview: ["new_condition_found", "work_paused_for_review", "scope_update_prepared", "customer_approval", "work_rescheduled"],
    },
    defaultAutomations: [],
    reports: [
      { key: "assessment-throughput", name: "Time from concern to assessment", coreMetric: "elapsed_days", dimensions: ["referral_source", "property_type"] },
      { key: "scope-by-room", name: "Approved scope by room and material", coreMetric: "approved_scope", dimensions: ["room_identifier", "material_type"] },
      { key: "equipment-days", name: "Containment and equipment deployment", coreMetric: "equipment_days", dimensions: ["property", "service"] },
      { key: "verification-followup", name: "Verification and repeat-visit outcomes", coreMetric: "follow_up_work", dimensions: ["property_type", "verification_status"] },
    ],
    pricingTemplates: [
      { key: "assessment-base", name: "Site assessment or project minimum", stage: "base", inputFields: ["service", "property_type"], effect: "set_base_amount", requiresTenantAmount: true },
      { key: "area-material-scope", name: "Affected area, material, and approved scope", stage: "quantity", inputFields: ["affected_area", "material_type", "work_plan"], effect: "add_variable", requiresTenantAmount: true },
      { key: "containment-days", name: "Containment and equipment duration", stage: "quantity", inputFields: ["containment", "equipment_days"], effect: "add_variable", requiresTenantAmount: true },
      { key: "labor-disposal", name: "Labor, removal, and disposal", stage: "add_on", inputFields: ["labor", "removed_material", "disposal"], effect: "add_fixed", requiresTenantAmount: true },
      { key: "testing-repair", name: "Separately approved testing or repair", stage: "add_on", inputFields: ["verification", "source_repair"], effect: "add_fixed", requiresTenantAmount: true },
    ],
    recommendationQuestions: [
      { key: "works_in_regulated_jurisdictions", prompt: "Do you work in jurisdictions with mold-specific licensing or role rules?", answerType: "boolean" },
      { key: "provides_assessment_or_testing", prompt: "Does your business also provide assessment or testing?", answerType: "boolean" },
      { key: "provides_post_work_verification", prompt: "Do you coordinate or provide post-work verification?", answerType: "boolean" },
      { key: "handles_commercial_occupied_sites", prompt: "Do you work in occupied, commercial, school, or institutional properties?", answerType: "boolean" },
      { key: "handles_hvac_or_contents", prompt: "Do you handle HVAC or contents work?", answerType: "boolean" },
      { key: "has_multiple_crews", prompt: "Do you coordinate multiple remediation crews?", answerType: "boolean" },
    ],
    productCapabilityRecommendations: [
      { featureKey: "field_job_tracking", recommendation: "normally_recommended", rationale: "Site-specific work plans, rooms, material records, and closeout need a job record." },
      { featureKey: "estimate_management", recommendation: "normally_recommended", rationale: "Hidden conditions, access, and protocols affect the reviewed project scope." },
      { featureKey: "service_scheduling", recommendation: "normally_recommended", rationale: "Assessment, multi-day work, repair coordination, and verification need scheduling." },
      { featureKey: "invoicing", recommendation: "normally_recommended", rationale: "Customers need charges that follow approved remediation scope." },
      { featureKey: "customer_notifications", recommendation: "normally_recommended", rationale: "Owners and occupants need access, work, and follow-up updates." },
      { featureKey: "customer_self_service", recommendation: "optional", rationale: "Property contacts can review approved documents and schedule updates." },
      { featureKey: "inventory_tracking", recommendation: "optional", rationale: "Equipment and containment stock may be tracked by larger teams." },
      { featureKey: "advanced_reporting", recommendation: "optional", rationale: "Larger operators can review repeat visits, equipment use, and closeout." },
      { featureKey: "multi_location_management", recommendation: "optional", rationale: "Property managers and institutions may have multiple active buildings.", rules: [{ when: { op: "equals", answerKey: "handles_commercial_occupied_sites", value: true }, recommendation: "normally_recommended" }] },
      { featureKey: "route_planning", recommendation: "usually_unnecessary", rationale: "Site assessment and project sequence usually matter more than dense routes." },
      { featureKey: "payment_collection", recommendation: "optional", rationale: "Direct payment applies according to the business and claim arrangement." },
      { featureKey: "website_publishing", recommendation: "optional", rationale: "An intake page can collect concerns and route them for human review." },
    ],
    recommendedConnectorCapabilities: ["storage", "email", "sms", "calendar", "accounting", "payments"],
    inventoryDefaults: [
      { key: "protective-equipment", name: "Tenant-selected PPE and respiratory equipment", unit: "set" },
      { key: "containment-material", name: "Containment sheeting and tape", unit: "roll" },
      { key: "hepa-air-equipment", name: "HEPA filtration or vacuum equipment", unit: "unit" },
      { key: "moisture-meter", name: "Moisture meter", unit: "unit" },
      { key: "disposal-bags", name: "Material handling and disposal supplies", unit: "pack" },
    ],
    website: { template: "classic", sections: ["hero", "assessment-first", "remediation-services", "work-plan-process", "occupied-properties", "service-area", "frequently-asked-questions", "contact"], signupSteps: ["concern", "reports-access", "assessment", "plan-approval"], heroHeadline: "A clear plan for mold remediation", heroDescription: "Request a site assessment and share existing reports so a qualified professional can review next steps." },
  },
  {
    key: "moving-services", version: "1.0.0", displayName: "Moving & Hauling Services",
    customerTypes: ["household_shipper", "renter", "homeowner", "property_manager", "realtor_referral", "business_or_office"],
    terminology: { customer: "Customer / shipper", serviceLocation: "Origin or destination", customerAsset: "Shipment item", job: "Move", servicePlan: "Move booking", fieldTechnician: "Moving crew" },
    locationFields: [
      { key: "building_access", label: "Origin / destination building access", type: "text", sensitive: true },
      { key: "stairs_elevator", label: "Stairs, elevator, and reservation details", type: "text" },
      { key: "parking_loading", label: "Parking and loading restrictions", type: "text" },
      { key: "long_carry", label: "Long carry or access distance", type: "text" },
      { key: "building_contact", label: "Building or move-day contact", type: "text" },
      { key: "move_date_window", label: "Move date and arrival window", type: "text" },
      { key: "interstate_jurisdiction", label: "Customer-confirmed shipment and jurisdiction type", type: "enum", options: ["local_or_intrastate", "interstate_household_goods", "labor_only", "commercial", "needs_review"] },
      { key: "insurance_or_coi_notes", label: "Insurance or certificate notes when required", type: "text", sensitive: true },
    ],
    assets: [
      { key: "shipment-item", label: "Shipment item", pluralLabel: "Shipment items", fields: [
        { key: "item_identifier", label: "Shipment item identifier", type: "text", required: true },
        { key: "description", label: "Item description", type: "text" },
        { key: "room_or_origin", label: "Room or origin location", type: "text" },
        { key: "condition_before", label: "Recorded condition before loading", type: "text" },
        { key: "high_value_or_special_handling", label: "Customer-noted high value or special handling", type: "text", sensitive: true },
        { key: "packing_status", label: "Packing status", type: "enum", options: ["not_packed", "customer_packed", "crew_packed", "loaded", "delivered", "exception"] },
        { key: "delivery_condition", label: "Recorded delivery condition or exception", type: "text" },
        { key: "item_photos", label: "Condition or exception photos", type: "media" },
      ] },
      { key: "moving-vehicle", label: "Moving vehicle", pluralLabel: "Moving vehicles", fields: [
        { key: "vehicle_identifier", label: "Vehicle identifier", type: "text" },
        { key: "capacity_notes", label: "Capacity notes", type: "text" },
        { key: "assigned_crew", label: "Assigned crew", type: "text" },
      ] },
    ],
    services: [
      { key: "local-move", name: "Local household move", kind: "one_time", estimatedMinutes: 240, defaultEnabled: true },
      { key: "long-distance-move", name: "Long-distance household move", kind: "one_time", estimatedMinutes: 480 },
      { key: "commercial-move", name: "Office or commercial move", kind: "one_time", estimatedMinutes: 360 },
      { key: "packing-unpacking", name: "Packing and unpacking", kind: "add_on", estimatedMinutes: 180 },
      { key: "labor-only", name: "Loading or unloading labor only", kind: "one_time", estimatedMinutes: 120 },
      { key: "specialty-item", name: "Specialty or heavy item handling", kind: "add_on", estimatedMinutes: 90 },
      { key: "storage-handling", name: "Storage or warehouse handling", kind: "add_on", estimatedMinutes: 120 },
      { key: "small-load-hauling", name: "Small-load customer goods transport", kind: "one_time", estimatedMinutes: 120 },
    ],
    recurrencePresets: [{ key: "multi-day-move", label: "Multi-day move schedule", custom: true }, { key: "storage-followup", label: "Storage or delivery follow-up", custom: true }],
    formSteps: [
      { key: "move-route-date", label: "Set the move route and date", fields: ["origin_address", "destination_address", "move_date_window", "shipment_type"] },
      { key: "inventory-survey", label: "Describe the shipment", fields: ["home_or_office_size", "item_list", "photos_or_video", "special_items", "packing_needs"] },
      { key: "access", label: "Share access and building details", fields: ["stairs_elevator", "parking_loading", "long_carry", "building_contact", "storage_needs"] },
      { key: "estimate-documents", label: "Review survey, estimate, and move documents", fields: ["estimate_type", "service_scope", "accessorials", "document_review", "approval"] },
    ],
    jobChecklist: [
      { key: "confirm-move-parties-dates", label: "Confirm shipper, origin, destination, dates, and contacts", required: true },
      { key: "confirm-survey-inventory", label: "Confirm shipment inventory and agreed services", required: true },
      { key: "issue-applicable-documents", label: "Prepare documents applicable to the shipment and jurisdiction", required: true },
      { key: "record-preload-condition", label: "Record item condition, tags, and agreed packing status", required: true },
      { key: "load-transport", label: "Record crew, vehicle, loading, and shipment handoff", required: true },
      { key: "delivery-exceptions-signoff", label: "Record delivery, exceptions, condition notes, and customer signoff", required: true },
      { key: "scope-change-approval", label: "Document estimate or shipment changes and required customer approval", required: true },
      { key: "retain-claim-records", label: "Attach move and claim records when applicable", required: false },
    ],
    noncompletionReasons: [
      { key: "access-parking-denied", label: "Access, parking, or building reservation unavailable", billableByDefault: false },
      { key: "customer-not-ready", label: "Customer or shipment not ready", billableByDefault: false },
      { key: "scope-inventory-changed", label: "Inventory or move scope changed and needs review", billableByDefault: false },
      { key: "weather-delay", label: "Weather or travel delay", billableByDefault: false },
      { key: "crew-vehicle-unavailable", label: "Crew or vehicle unavailable", billableByDefault: false },
      { key: "safety-concern", label: "Site or item safety concern", billableByDefault: false },
      { key: "customer-cancelled", label: "Customer cancelled or rescheduled", billableByDefault: false },
    ],
    workflows: {
      moveBooking: ["lead", "survey_requested", "survey_complete", "estimate_prepared", "documents_reviewed", "approved_and_booked", "crew_vehicle_assigned", "loading", "in_transit_or_storage", "delivery", "signoff_and_closeout"],
      shipmentItem: ["identified", "condition_recorded", "packed_or_tagged", "loaded", "in_transit_or_storage", "delivered", "exception_or_claim_if_needed"],
      changedScope: ["additional_item_or_accessorial", "estimate_revised", "customer_review", "approved", "work_continues"],
    },
    defaultAutomations: [],
    reports: [
      { key: "moves-by-date", name: "Booked move capacity by date", coreMetric: "booked_capacity", dimensions: ["move_date", "crew", "vehicle", "service"] },
      { key: "estimate-variance", name: "Estimated and actual move effort", coreMetric: "estimate_variance", dimensions: ["service", "shipment_type", "crew"] },
      { key: "move-outcomes", name: "Delays, incomplete moves, and delivery outcomes", coreMetric: "job_outcomes", dimensions: ["reason", "service", "service_zone"] },
      { key: "claims-exceptions", name: "Shipment damage and delivery exceptions", coreMetric: "move_exceptions", dimensions: ["service", "exception_type"] },
    ],
    pricingTemplates: [
      { key: "local-hourly", name: "Tenant-set local crew, vehicle, and minimum", stage: "base", inputFields: ["crew_size", "vehicle", "minimum_hours"], effect: "set_base_amount", requiresTenantAmount: true },
      { key: "shipment-volume", name: "Shipment size or survey volume", stage: "quantity", inputFields: ["inventory", "volume_or_weight"], effect: "add_variable", requiresTenantAmount: true },
      { key: "distance-and-legs", name: "Distance, travel legs, or service area", stage: "zone", inputFields: ["origin", "destination", "distance"], effect: "add_variable", requiresTenantAmount: true },
      { key: "accessorials", name: "Access and approved extra services", stage: "add_on", inputFields: ["stairs", "long_carry", "packing", "specialty_items"], effect: "add_fixed", requiresTenantAmount: true },
      { key: "storage-and-material", name: "Storage and packing materials", stage: "add_on", inputFields: ["storage_duration", "packing_materials"], effect: "add_fixed", requiresTenantAmount: true },
    ],
    recommendationQuestions: [
      { key: "handles_interstate_household_goods", prompt: "Do you arrange covered interstate household-goods moves?", answerType: "boolean" },
      { key: "offers_labor_only", prompt: "Do you offer labor-only loading or unloading?", answerType: "boolean" },
      { key: "offers_packing_or_storage", prompt: "Do you offer packing, warehouse handling, or storage?", answerType: "boolean" },
      { key: "runs_multiple_trucks", prompt: "Do you coordinate multiple crews or trucks on the same day?", answerType: "boolean" },
      { key: "uses_warehouse_stock", prompt: "Do you manage packing supplies or warehouse stock?", answerType: "boolean" },
      { key: "has_paid_crews", prompt: "Do you employ moving crews?", answerType: "boolean" },
    ],
    productCapabilityRecommendations: [
      { featureKey: "service_scheduling", recommendation: "normally_recommended", rationale: "Moves require date-specific crew, vehicle, and access coordination." },
      { featureKey: "estimate_management", recommendation: "normally_recommended", rationale: "Surveys and changed inventory or access affect the estimate and approved scope." },
      { featureKey: "field_job_tracking", recommendation: "normally_recommended", rationale: "Crews need shipment instructions, item condition, delivery, and exception records." },
      { featureKey: "invoicing", recommendation: "normally_recommended", rationale: "Customers need documented charges and completed move records." },
      { featureKey: "payment_collection", recommendation: "normally_recommended", rationale: "The business needs to collect according to its move terms." },
      { featureKey: "customer_notifications", recommendation: "normally_recommended", rationale: "Arrival, delay, loading, and delivery updates matter on move day." },
      { featureKey: "customer_self_service", recommendation: "optional", rationale: "Customers can share inventory, photos, access details, and review records." },
      { featureKey: "route_planning", recommendation: "optional", rationale: "Routing helps fleets with multiple jobs while preserving shipment legs and windows.", rules: [{ when: { op: "equals", answerKey: "runs_multiple_trucks", value: true }, recommendation: "normally_recommended" }] },
      { featureKey: "inventory_tracking", recommendation: "optional", rationale: "Manage packing supplies and warehouse stock; shipment inventory remains move-specific.", rules: [{ when: { op: "equals", answerKey: "uses_warehouse_stock", value: true }, recommendation: "normally_recommended" }] },
      { featureKey: "time_tracking", recommendation: "optional", rationale: "Labor time supports costing for employed crews.", rules: [{ when: { op: "equals", answerKey: "has_paid_crews", value: true }, recommendation: "normally_recommended" }] },
      { featureKey: "payroll_inputs", recommendation: "optional", rationale: "Payroll inputs are useful when employees and crew pay are managed in the business." },
      { featureKey: "website_publishing", recommendation: "optional", rationale: "An estimate request page can collect route, date, inventory, and access needs." },
      { featureKey: "online_booking", recommendation: "usually_unnecessary", rationale: "Survey and dispatch review commonly precede confirmation of move capacity." },
    ],
    recommendedConnectorCapabilities: ["payments", "email", "sms", "accounting", "calendar", "routing", "geocoding", "storage", "payroll", "crm_import"],
    inventoryDefaults: [
      { key: "moving-cartons", name: "Moving cartons", unit: "piece" },
      { key: "packing-materials", name: "Packing and wrapping materials", unit: "pack" },
      { key: "furniture-pads", name: "Furniture pads and covers", unit: "piece" },
      { key: "dollies-straps", name: "Dollies, straps, and moving equipment", unit: "piece" },
      { key: "shipment-tags", name: "Shipment item tags", unit: "piece" },
    ],
    website: { template: "classic", sections: ["hero", "moving-services", "packing-and-storage", "how-estimates-work", "service-area", "move-preparation", "reviews", "request-a-survey", "contact"], signupSteps: ["move-route-date", "inventory-survey", "access", "estimate-documents"], heroHeadline: "A move planned around your shipment", heroDescription: "Share your dates, locations, inventory, and access details to request a moving survey and estimate." },
  },
  {
    key: "thermal-imaging-home-inspection", version: "1.0.0", displayName: "Thermal Imaging & Home Inspection",
    customerTypes: ["homebuyer", "homeowner", "home_seller", "realtor_referral", "home_performance_client"],
    terminology: { customer: "Client", serviceLocation: "Property", customerAsset: "Inspection area / building system", job: "Inspection or audit", servicePlan: "Inspection booking", fieldTechnician: "Inspector / auditor" },
    locationFields: [
      { key: "property_type", label: "Property type", type: "text" },
      { key: "property_occupancy", label: "Occupancy and access contact", type: "text", sensitive: true },
      { key: "inspection_context", label: "Inspection or energy-analysis context", type: "enum", options: ["real_estate_inspection", "thermal_add_on", "home_energy_audit", "commercial_scan", "other"] },
      { key: "conditions_notes", label: "Weather, operating, and observed test conditions", type: "text" },
      { key: "report_recipients", label: "Client-selected report recipients", type: "text", sensitive: true },
      { key: "realtor_or_program", label: "Referral, program, or transaction contact", type: "text" },
    ],
    assets: [
      { key: "inspection-area", label: "Inspection area", pluralLabel: "Inspection areas", fields: [
        { key: "area_identifier", label: "Room, surface, or system", type: "text", required: true },
        { key: "visual_observation", label: "Visual observation", type: "text" },
        { key: "thermal_observation", label: "Thermal image observation", type: "text" },
        { key: "paired_image", label: "Related visual and thermal images", type: "media" },
        { key: "instrument_or_test", label: "Instrument or test used", type: "text" },
        { key: "verification_followup", label: "Recommended verification or referral", type: "text" },
        { key: "report_status", label: "Report status", type: "enum", options: ["not_reviewed", "observation_recorded", "requires_review", "reported_with_limits", "followup_recommended"] },
      ] },
      { key: "inspection-instrument", label: "Inspection instrument", pluralLabel: "Inspection instruments", fields: [
        { key: "instrument_type", label: "Camera or diagnostic instrument", type: "text", required: true },
        { key: "instrument_identifier", label: "Instrument identifier", type: "text" },
        { key: "tenant_calibration_note", label: "Tenant-recorded calibration or service note", type: "text" },
      ] },
    ],
    services: [
      { key: "visual-home-inspection", name: "Visual home inspection", kind: "one_time", estimatedMinutes: 180, defaultEnabled: true },
      { key: "thermal-inspection-add-on", name: "Thermal imaging inspection add-on", kind: "add_on", estimatedMinutes: 60 },
      { key: "standalone-thermal-survey", name: "Standalone thermal imaging survey", kind: "one_time", estimatedMinutes: 120 },
      { key: "home-energy-audit", name: "Home energy performance audit", kind: "one_time", estimatedMinutes: 240 },
      { key: "followup-verification", name: "Follow-up verification visit", kind: "one_time", estimatedMinutes: 90 },
      { key: "commercial-building-scan", name: "Commercial building scan", kind: "one_time", estimatedMinutes: 240 },
    ],
    recurrencePresets: [{ key: "client-requested-followup", label: "Client-requested follow-up", custom: true }],
    formSteps: [
      { key: "inspection-context", label: "Choose the service context", fields: ["inspection_context", "property_type", "transaction_or_energy_question"] },
      { key: "property-access", label: "Share property access and conditions", fields: ["service_address", "property_occupancy", "conditions_notes", "preferred_window"] },
      { key: "service-scope", label: "Select inspection, thermal, or audit services", fields: ["service", "systems_of_interest", "requested_instruments", "test_conditions"] },
      { key: "report-handoff", label: "Set report delivery expectations", fields: ["report_recipients", "report_due_date", "limitations_and_assumptions", "estimate"] },
    ],
    jobChecklist: [
      { key: "confirm-scope-credential", label: "Confirm service scope and inspector or auditor qualifications relevant to that scope", required: true },
      { key: "record-site-conditions", label: "Record access, weather, operating, and test conditions", required: true },
      { key: "capture-observations", label: "Record visual observations and paired thermal images where useful", required: true },
      { key: "review-anomalies", label: "Review thermal observations and record limits or verification needs", required: true },
      { key: "avoid-unverified-diagnosis", label: "Keep observations distinct from confirmed building defects or performance conclusions", required: true },
      { key: "prepare-report", label: "Prepare a report appropriate to the selected inspection or audit service", required: true },
      { key: "deliver-to-authorized-recipients", label: "Deliver the reviewed report to client-authorized recipients", required: true },
    ],
    noncompletionReasons: [
      { key: "property-no-access", label: "Property or inspected area unavailable", billableByDefault: false },
      { key: "conditions-unsuitable", label: "Conditions unsuitable for the planned observations or test", billableByDefault: false },
      { key: "scope-credential-review", label: "Requested scope requires qualification or program review", billableByDefault: false },
      { key: "instrument-issue", label: "Required instrument unavailable or not ready", billableByDefault: false },
      { key: "hidden-area-limited", label: "Area inaccessible; limitation and follow-up recorded", billableByDefault: false },
      { key: "client-reschedule", label: "Client or transaction contact requested rescheduling", billableByDefault: false },
    ],
    workflows: {
      homeInspection: ["inquiry", "scope_selected", "scheduled", "site_conditions_recorded", "inspection", "observations_reviewed", "report_prepared", "client_delivery", "followup_if_requested"],
      energyAudit: ["inquiry", "program_and_scope_review", "audit_scheduled", "conditions_and_tests_recorded", "analysis", "report_review", "client_or_program_handoff"],
      thermalObservation: ["image_captured", "paired_with_visual_context", "reviewed", "limitation_or_verification_recorded", "included_in_report"],
    },
    defaultAutomations: [],
    reports: [
      { key: "inspection-bookings", name: "Inspections by service type and referral", coreMetric: "scheduled_jobs", dimensions: ["inspection_context", "referral_source", "service"] },
      { key: "report-turnaround", name: "Inspection and audit report turnaround", coreMetric: "elapsed_days", dimensions: ["service", "property_type"] },
      { key: "followup-observations", name: "Observations with verification or referral follow-up", coreMetric: "follow_up_work", dimensions: ["service", "area_identifier"] },
      { key: "service-mix", name: "Thermal add-on and standalone service mix", coreMetric: "service_mix", dimensions: ["inspection_context", "service"] },
    ],
    pricingTemplates: [
      { key: "inspection-base", name: "Tenant-set inspection base", stage: "base", inputFields: ["service", "property_type"], effect: "set_base_amount", requiresTenantAmount: true },
      { key: "property-scope", name: "Property size and inspection scope", stage: "quantity", inputFields: ["area", "building_systems", "service"], effect: "add_variable", requiresTenantAmount: true },
      { key: "thermal-add-on", name: "Thermal imaging scope add-on", stage: "add_on", inputFields: ["thermal_areas", "paired_reporting"], effect: "add_fixed", requiresTenantAmount: true },
      { key: "energy-test-scope", name: "Energy audit instruments and tests", stage: "add_on", inputFields: ["audit_scope", "tests", "program"], effect: "add_fixed", requiresTenantAmount: true },
      { key: "service-zone", name: "Travel by service area", stage: "zone", inputFields: ["service_zone"], effect: "add_fixed", requiresTenantAmount: true },
    ],
    recommendationQuestions: [
      { key: "includes_standard_home_inspection", prompt: "Do you offer standard real-estate home inspections?", answerType: "boolean" },
      { key: "offers_thermal_addon", prompt: "Is thermal imaging included, optional, or sold as an add-on in your inspection service?", answerType: "enum", options: ["included", "optional_add_on", "standalone", "not_offered"] },
      { key: "offers_energy_audit", prompt: "Do you perform home energy audits or utility analysis?", answerType: "boolean" },
      { key: "uses_other_diagnostics", prompt: "Do you use other diagnostic instruments or tests?", answerType: "boolean" },
      { key: "serves_program_or_commercial_clients", prompt: "Do you serve utility programs or commercial buildings?", answerType: "boolean" },
      { key: "has_inspection_staff", prompt: "Do multiple inspectors or auditors perform site visits?", answerType: "boolean" },
    ],
    productCapabilityRecommendations: [
      { featureKey: "service_scheduling", recommendation: "normally_recommended", rationale: "Property access and transaction deadlines require date-specific appointments." },
      { featureKey: "estimate_management", recommendation: "normally_recommended", rationale: "Inspection, thermal add-on, and energy audit scopes differ by client and property." },
      { featureKey: "field_job_tracking", recommendation: "normally_recommended", rationale: "Inspectors need an organized record of conditions, instruments, observations, and report status." },
      { featureKey: "customer_notifications", recommendation: "normally_recommended", rationale: "Clients and authorized transaction contacts need appointment and report updates." },
      { featureKey: "invoicing", recommendation: "normally_recommended", rationale: "Inspection and add-on services need clear fee and report records." },
      { featureKey: "payment_collection", recommendation: "normally_recommended", rationale: "Clients need a way to pay for the selected inspection or audit." },
      { featureKey: "customer_self_service", recommendation: "optional", rationale: "Clients may submit property details and receive approved reports." },
      { featureKey: "inventory_tracking", recommendation: "optional", rationale: "Instrument assignment and maintenance records help teams with multiple devices.", rules: [{ when: { op: "equals", answerKey: "has_inspection_staff", value: true }, recommendation: "normally_recommended" }] },
      { featureKey: "website_publishing", recommendation: "normally_recommended", rationale: "A website can explain when thermal imaging is included, optional, or a separate audit." },
      { featureKey: "route_planning", recommendation: "optional", rationale: "Appointment sequencing helps when inspectors cover multiple properties." },
      { featureKey: "recurring_service_management", recommendation: "usually_unnecessary", rationale: "Home inspections and energy audits are generally transaction or project-based." },
      { featureKey: "online_booking", recommendation: "optional", rationale: "Online requests help, while the final appointment may depend on scope and conditions." },
    ],
    recommendedConnectorCapabilities: ["calendar", "email", "sms", "storage", "payments", "accounting", "geocoding"],
    inventoryDefaults: [
      { key: "thermal-camera", name: "Thermal imaging camera", unit: "unit" },
      { key: "visual-camera", name: "Visual inspection camera", unit: "unit" },
      { key: "moisture-meter", name: "Moisture meter", unit: "unit" },
      { key: "audit-instruments", name: "Tenant-selected energy audit instruments", unit: "kit" },
      { key: "inspection-supplies", name: "Inspection and safety supplies", unit: "kit" },
    ],
    website: { template: "classic", sections: ["hero", "home-inspection", "thermal-imaging", "energy-audit", "what-reports-show", "limitations-and-followup", "service-area", "reviews", "book-an-inspection"], signupSteps: ["inspection-context", "property-access", "service-scope", "report-handoff"], heroHeadline: "A clearer view of your property", heroDescription: "Book a home inspection, thermal imaging add-on, or separate home energy assessment with a report for your needs." },
  },
  {
    key: "water-damage-remediation", version: "1.0.0", displayName: "Water Damage Mitigation & Restoration",
    customerTypes: ["homeowner_or_insured", "property_manager", "commercial_owner", "institution", "adjuster_or_claim_contact"],
    terminology: { customer: "Owner / insured", serviceLocation: "Loss property", customerAsset: "Affected room / material", job: "Water loss", servicePlan: "Drying plan", fieldTechnician: "Mitigation technician" },
    locationFields: [
      { key: "loss_reference", label: "Customer or claim loss reference", type: "text", sensitive: true },
      { key: "reported_discovery_time", label: "When the water was discovered", type: "text" },
      { key: "reported_source", label: "Reported water source or cause", type: "text" },
      { key: "active_source_status", label: "Water source status as reported or verified", type: "text" },
      { key: "building_unit_levels", label: "Building, unit, and affected levels", type: "text" },
      { key: "occupancy_access", label: "Occupancy and property access notes", type: "text", sensitive: true },
      { key: "reported_safety_conditions", label: "Reported hazards for qualified review", type: "text", sensitive: true },
      { key: "adjuster_contact", label: "Authorized adjuster or claim contact", type: "text", sensitive: true },
    ],
    assets: [
      { key: "affected-room", label: "Affected room or area", pluralLabel: "Affected rooms and areas", fields: [
        { key: "room_identifier", label: "Floor and room identifier", type: "text", required: true },
        { key: "source_and_category", label: "Reported source and technician-recorded classification", type: "text" },
        { key: "affected_material", label: "Affected material or assembly", type: "text" },
        { key: "initial_condition", label: "Initial observed condition", type: "text" },
        { key: "initial_readings", label: "Initial moisture or environmental readings", type: "text" },
        { key: "reading_reference_points", label: "Reading locations and reference material", type: "text" },
        { key: "room_photos_map", label: "Room map and timestamped condition photos", type: "media" },
        { key: "drying_status", label: "Drying status", type: "enum", options: ["not_assessed", "extraction", "equipment_deployed", "monitoring", "needs_scope_review", "closeout_review"] },
      ] },
      { key: "drying-equipment", label: "Drying equipment", pluralLabel: "Drying equipment", fields: [
        { key: "equipment_type", label: "Equipment type", type: "enum", options: ["air_mover", "dehumidifier", "extractor", "moisture_meter", "other"] },
        { key: "equipment_identifier", label: "Equipment identifier", type: "text" },
        { key: "room_placement", label: "Placement room or area", type: "text" },
        { key: "deployment_start", label: "Deployment start", type: "date" },
        { key: "deployment_end", label: "Removal or return date", type: "date" },
      ] },
    ],
    services: [
      { key: "emergency-water-response", name: "Emergency water loss response", kind: "recovery", estimatedMinutes: 120, defaultEnabled: true },
      { key: "water-loss-inspection", name: "Water loss inspection and moisture mapping", kind: "one_time", estimatedMinutes: 120 },
      { key: "water-extraction", name: "Water extraction", kind: "one_time", estimatedMinutes: 180 },
      { key: "structural-drying", name: "Structural drying setup and monitoring", kind: "one_time", estimatedMinutes: 120 },
      { key: "contents-handling", name: "Contents manipulation or pack-out", kind: "add_on", estimatedMinutes: 180 },
      { key: "approved-material-removal", name: "Approved material removal and disposal", kind: "one_time", estimatedMinutes: 180 },
      { key: "repair-reconstruction", name: "Separately approved repair or reconstruction", kind: "one_time", estimatedMinutes: 240 },
      { key: "equipment-return", name: "Drying equipment removal and return visit", kind: "add_on", estimatedMinutes: 90 },
    ],
    recurrencePresets: [{ key: "monitoring-return", label: "Drying monitoring return visit", custom: true }],
    formSteps: [
      { key: "urgent-intake", label: "Tell us about the water loss", fields: ["service_address", "loss_reference", "reported_discovery_time", "reported_source", "active_source_status"] },
      { key: "occupants-safety", label: "Share access and reported site conditions", fields: ["building_unit_levels", "occupancy_access", "reported_safety_conditions", "photos"] },
      { key: "claim-contact", label: "Provide authorized claim details if applicable", fields: ["insurer", "claim_number", "adjuster_contact", "communication_authority"] },
      { key: "assessment-scope", label: "Arrange inspection and review proposed work", fields: ["affected_rooms", "materials", "moisture_map", "estimate", "approval"] },
    ],
    jobChecklist: [
      { key: "record-reported-facts", label: "Record customer-reported source and timeline separately from verified observations", required: true },
      { key: "confirm-authority-access", label: "Confirm customer authority and property access", required: true },
      { key: "map-rooms-reference-points", label: "Map affected rooms, materials, and repeatable reading points", required: true },
      { key: "record-initial-readings", label: "Record initial readings and timestamped condition evidence", required: true },
      { key: "record-extraction-setup", label: "Record extraction, equipment placement, and approved scope", required: true },
      { key: "repeat-monitoring-log", label: "Record readings, conditions, and equipment at each monitoring visit", required: true },
      { key: "changed-scope-approval", label: "Document changed conditions and obtain scope approval before added work where applicable", required: true },
      { key: "dry-closeout-documents", label: "Record closeout observations, equipment return, and authorized report delivery", required: true },
    ],
    noncompletionReasons: [
      { key: "no-property-access", label: "No access to affected property or room", billableByDefault: false },
      { key: "qualified-safety-review", label: "Reported condition requires qualified safety or specialist review", billableByDefault: false },
      { key: "active-source-uncontrolled", label: "Reported water source needs owner or specialist coordination", billableByDefault: false },
      { key: "authorization-claim-review", label: "Customer or authorized scope review is pending", billableByDefault: false },
      { key: "additional-hidden-damage", label: "Concealed or changed condition requires reassessment", billableByDefault: false },
      { key: "customer-unavailable-monitoring", label: "Customer unavailable for scheduled monitoring visit", billableByDefault: false },
      { key: "equipment-unavailable", label: "Required equipment unavailable", billableByDefault: false },
    ],
    workflows: {
      waterLoss: ["reported", "human_triage", "dispatch", "site_assessment", "scope_and_authorization", "extraction", "equipment_placed", "monitoring_visits", "dry_closeout_review", "equipment_removed", "report_and_invoice"],
      monitoringVisit: ["scheduled", "room_points_checked", "readings_recorded", "equipment_checked", "scope_or_setup_updated", "next_visit_or_closeout"],
      claimHandoff: ["authorization_recorded", "claim_contact_recorded", "approved_documents_selected", "owner_or_adjuster_delivery", "receipt_or_followup"],
    },
    defaultAutomations: [],
    reports: [
      { key: "first-response", name: "Time from reported loss to first response", coreMetric: "elapsed_hours", dimensions: ["service_zone", "referral_source"] },
      { key: "open-dryouts", name: "Open drying projects and monitoring age", coreMetric: "open_jobs", dimensions: ["stage", "property_type", "age_days"] },
      { key: "moisture-history", name: "Room and material readings by visit", coreMetric: "reading_records", dimensions: ["room_identifier", "affected_material", "visit"] },
      { key: "equipment-deployment", name: "Equipment deployment days by loss", coreMetric: "equipment_days", dimensions: ["equipment_type", "room_identifier"] },
      { key: "scope-invoice-variance", name: "Estimate and invoice variance", coreMetric: "estimate_variance", dimensions: ["service", "claim_reference"] },
    ],
    pricingTemplates: [
      { key: "response-minimum", name: "Tenant-set emergency response or assessment minimum", stage: "base", inputFields: ["service", "response_window"], effect: "set_base_amount", requiresTenantAmount: true },
      { key: "area-material", name: "Affected area and material scope", stage: "quantity", inputFields: ["room_count", "affected_material", "approved_scope"], effect: "add_variable", requiresTenantAmount: true },
      { key: "equipment-duration", name: "Equipment quantity and deployment duration", stage: "quantity", inputFields: ["equipment_count", "equipment_days"], effect: "add_variable", requiresTenantAmount: true },
      { key: "extraction-disposal", name: "Extraction labor and approved disposal", stage: "add_on", inputFields: ["extraction", "labor", "disposal"], effect: "add_fixed", requiresTenantAmount: true },
      { key: "contents-repair", name: "Approved contents or separate repair work", stage: "add_on", inputFields: ["contents", "repair_scope"], effect: "add_fixed", requiresTenantAmount: true },
    ],
    recommendationQuestions: [
      { key: "offers_after_hours_response", prompt: "Do you respond to loss calls after business hours?", answerType: "boolean" },
      { key: "coordinates_insurance_claims", prompt: "Do you prepare documentation for insurance claim contacts?", answerType: "boolean" },
      { key: "offers_contents_services", prompt: "Do you handle contents manipulation or pack-out?", answerType: "boolean" },
      { key: "offers_reconstruction", prompt: "Do you also perform repair or reconstruction work?", answerType: "boolean" },
      { key: "many_monitoring_visits", prompt: "Do technicians manage many daily monitoring visits?", answerType: "boolean" },
      { key: "owns_drying_equipment", prompt: "Do you own and track drying equipment across jobs?", answerType: "boolean" },
    ],
    productCapabilityRecommendations: [
      { featureKey: "field_job_tracking", recommendation: "normally_recommended", rationale: "The job record needs room maps, repeated readings, photos, and equipment notes." },
      { featureKey: "estimate_management", recommendation: "normally_recommended", rationale: "Measured conditions and hidden damage can change the approved scope." },
      { featureKey: "service_scheduling", recommendation: "normally_recommended", rationale: "Urgent response and repeated monitoring visits need active scheduling." },
      { featureKey: "invoicing", recommendation: "normally_recommended", rationale: "Labor, equipment, extraction, and approved scope need documented billing." },
      { featureKey: "customer_notifications", recommendation: "normally_recommended", rationale: "Owners need response, visit, progress, and equipment removal updates." },
      { featureKey: "inventory_tracking", recommendation: "optional", rationale: "Equipment deployment matters when owned fleets serve concurrent losses.", rules: [{ when: { op: "equals", answerKey: "owns_drying_equipment", value: true }, recommendation: "normally_recommended" }] },
      { featureKey: "route_planning", recommendation: "optional", rationale: "Route sequencing can help when monitoring rounds include many sites.", rules: [{ when: { op: "equals", answerKey: "many_monitoring_visits", value: true }, recommendation: "normally_recommended" }] },
      { featureKey: "customer_self_service", recommendation: "optional", rationale: "Authorized customers may review documents and updates for an active loss." },
      { featureKey: "advanced_reporting", recommendation: "optional", rationale: "Larger teams can compare response, drying, equipment, and return visit records." },
      { featureKey: "payment_collection", recommendation: "optional", rationale: "Direct payment depends on the customer and insurance arrangement." },
      { featureKey: "multi_location_management", recommendation: "optional", rationale: "Useful for operators serving multi-unit and commercial property groups." },
      { featureKey: "website_publishing", recommendation: "optional", rationale: "An intake page can collect urgent loss details before human triage." },
    ],
    recommendedConnectorCapabilities: ["storage", "email", "sms", "calendar", "accounting", "payments", "routing", "geocoding"],
    inventoryDefaults: [
      { key: "air-mover", name: "Air mover", unit: "unit" },
      { key: "dehumidifier", name: "Dehumidifier", unit: "unit" },
      { key: "extractor", name: "Water extraction equipment", unit: "unit" },
      { key: "moisture-meter", name: "Moisture meter", unit: "unit" },
      { key: "protective-equipment", name: "Tenant-selected protective equipment", unit: "set" },
      { key: "containment-supplies", name: "Containment and disposal supplies", unit: "pack" },
    ],
    website: { template: "classic", sections: ["hero", "urgent-response", "water-mitigation", "drying-visits", "what-to-expect", "insurance-coordination", "service-area", "frequently-asked-questions", "contact"], signupSteps: ["urgent-intake", "occupants-safety", "claim-contact", "assessment-scope"], heroHeadline: "A coordinated response to water damage", heroDescription: "Share what happened and request a response; a team member will review access, site conditions, and next steps." },
  },
];
