import { test, expect } from "@playwright/test";
test("new owner starts without a card, subscribes, loses editing after grace and recovers through hosted billing", async ({ page }) => {
  const email = `billing-${crypto.randomUUID()}@example.test`;
  await page.goto("/create-account");
  await page.getByLabel("Your name").fill("Billing Owner");
  await page.getByLabel("Business name").fill("Subscription Test Business");
  await page.getByLabel("Email address").fill(email);
  await page.getByLabel("Password", { exact: true }).fill("Demo12345!");
  await page.getByRole("button", { name: "Create account" }).click();
  await expect(page).toHaveURL(/\/onboarding/);
  await page.goto("/app/plan-billing");
  await expect(page.getByText("14 days left in your free trial. No card required.")).toBeVisible();
  const initial = await page.request.get("/api/v1/platform-billing"); expect(initial.status()).toBe(200); expect((await initial.json()).item.status).toBe("trialing");
  await page.getByRole("button", { name: "Choose Standard (local example)", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Secure plan payment" })).toBeVisible();
  // A browser redirect is not payment evidence.
  await page.goto("/app/plan-billing?billing=success");
  expect((await (await page.request.get("/api/v1/platform-billing")).json()).item.status).toBe("trialing");
  await page.getByRole("button", { name: "Choose Standard (local example)", exact: true }).click();
  await page.getByRole("button", { name: "Confirm test payment" }).click();
  await expect(page.getByText("Your plan is active", { exact: true })).toBeVisible();
  expect((await page.request.post("/api/v1/platform-billing/mock/fail")).status()).toBe(200);
  await page.reload(); await expect(page.getByText("Payment needs attention", { exact: true })).toBeVisible();
  expect((await page.request.post("/api/v1/platform-billing/mock/expire-grace")).status()).toBe(200);
  await page.reload(); await expect(page.getByText("Your workspace is read-only", { exact: true })).toBeVisible();
  const write = await page.request.post("/api/v1/customers", { data: { name: "Must not be added" } });
  expect(write.status()).toBe(402); expect((await write.json()).error.code).toBe("BILLING_REQUIRED");
  expect((await page.request.get("/api/v1/customers")).status()).toBe(200);
  expect((await page.request.get("/api/v1/exports/business-data")).status()).toBe(200);
  await page.getByRole("button", { name: "Update card", exact: true }).click();
  await expect(page.getByText("Update your test card and pay the outstanding bill.")).toBeVisible();
  await page.getByRole("button", { name: "Confirm test payment" }).click();
  await expect(page.getByText("Your plan is active", { exact: true })).toBeVisible();
  const recovered = await page.request.post("/api/v1/customers", { data: { name: "Recovered Customer", email: "recovered@example.test" } }); expect(recovered.status()).toBe(201);
  await page.getByRole("button", { name: "Change plan", exact: true }).click();
  await page.getByLabel("New plan").selectOption("local-small");
  await page.getByRole("button", { name: "Confirm plan change" }).click();
  await expect(page.getByRole("heading", { name: "Small team (local example)", exact: true }).first()).toBeVisible();
  await page.goto("/app/customers"); await expect(page.getByText("Recovered Customer").first()).toBeVisible();
});
