import { DomainError } from "@modular-crm/domain";
import { requireActor } from "./actor";
import { handleAdminOperations } from "./admin-operations";
import { handleAuthRoute } from "./auth-routes";
import { handleCapabilitySettings } from "./capability-settings";
import { handleConnectorCredentials } from "./connector-credentials";
import { handleConnectorOAuth } from "./connector-oauth";
import { handleTenantCapabilities } from "./tenant-capabilities";
import { requireApiCapability } from "./capability-enforcement";
import { handleDataPortability } from "./data-portability";
import { handleDocuments } from "./documents";
import { handleDeveloperCredentials } from "./developer-credentials";
import { handleDeveloperWebhooks } from "./developer-webhooks";
import { handleFiles } from "./files";
import { handleFranchiseRoyalty } from "./franchise-royalty";
import { apiError } from "./http";
import { handleOnboardingSite } from "./onboarding-site";
import { handleWebsiteDomains } from "./website-domains";
import { handlePayroll } from "./payroll";
import { handlePortal } from "./portal";
import { handlePublicSite } from "./public-site";
import { handlePublicApi } from "./public-api";
import { handleSecureEstimateLink } from "./secure-estimate-links";
import { handleRecords } from "./records";
import { handleReporting } from "./reporting";
import { handleInvoiceRefund } from "./refunds";
import { handleRoutesField } from "./routes-field";
import { handleWorkflow } from "./workflows";

export async function handleV1(request: Request, path: string[]): Promise<Response> {
  try {
    if (path[0] === "auth") return await handleAuthRoute(request, path);
    const publicApi = await handlePublicApi(request, path);
    if (publicApi) return publicApi;
    const secureEstimate = await handleSecureEstimateLink(request, path);
    if (secureEstimate) return secureEstimate;
    const publicResult = await handlePublicSite(request, path);
    if (publicResult) return publicResult;
    const actor = await requireActor(request);
    await requireApiCapability(actor.tenantId, path, request.method);
    const connectorOAuth = await handleConnectorOAuth(request, path, actor);
    if (connectorOAuth) return connectorOAuth;
    const websiteDomains = await handleWebsiteDomains(request, path, actor);
    if (websiteDomains) return websiteDomains;
    const onboarding = await handleOnboardingSite(request, path, actor);
    if (onboarding) return onboarding;
    const portal = await handlePortal(request, path, actor);
    if (portal) return portal;
    const document = await handleDocuments(request, path, actor);
    if (document) return document;
    const refund = await handleInvoiceRefund(request, path, actor);
    if (refund) return refund;
    const file = await handleFiles(request, path, actor);
    if (file) return file;
    const operations = await handleAdminOperations(request, path, actor);
    if (operations) return operations;
    const franchise = await handleFranchiseRoyalty(request, path, actor);
    if (franchise) return franchise;
    const portability = await handleDataPortability(request, path, actor);
    if (portability) return portability;
    const developerCredentials = await handleDeveloperCredentials(request, path, actor);
    if (developerCredentials) return developerCredentials;
    const developerWebhooks = await handleDeveloperWebhooks(request, path, actor);
    if (developerWebhooks) return developerWebhooks;
    const connectorCredentials = await handleConnectorCredentials(request, path, actor);
    if (connectorCredentials) return connectorCredentials;
    const capabilitySettings = await handleCapabilitySettings(request, path, actor);
    if (capabilitySettings) return capabilitySettings;
    const tenantCapabilities = await handleTenantCapabilities(request, path, actor);
    if (tenantCapabilities) return tenantCapabilities;
    const reporting = await handleReporting(request, path, actor);
    if (reporting) return reporting;
    const payroll = await handlePayroll(request, path, actor);
    if (payroll) return payroll;
    const workflow = await handleWorkflow(request, path, actor);
    if (workflow) return workflow;
    const routesField = await handleRoutesField(request, path, actor);
    if (routesField) return routesField;
    const records = await handleRecords(request, path, actor);
    if (records) return records;
    throw new DomainError("NOT_FOUND", "Endpoint not found.", 404);
  } catch (error) {
    return apiError(error);
  }
}
