"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { api, body, patch, unwrapItem } from "./api";
import { Icon, Loading, Logo, Notice, useResource } from "./ui";
import CapabilitySetup, { isWebsitePublishingUsable, type CapabilityCatalog } from "./CapabilitySetup";

type StepData = Record<string, any>;
type Answers = Record<number, StepData>;
const labels = ["Your business", "Basics", "Service area", "Services", "Payments", "Updates", "Customers", "Schedule", "Website", "Review"];

export default function Onboarding() {
  const result = useResource<{ item: Record<string, any> }>("/onboarding", { item: {} });
  const [step, setStep] = useState(0); const [answers, setAnswers] = useState<Answers>({}); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const [capabilityStepComplete, setCapabilityStepComplete] = useState(false); const [capabilityCatalog, setCapabilityCatalog] = useState<CapabilityCatalog | null>(null);
  const [csv, setCsv] = useState(""); const [csvPreview, setCsvPreview] = useState<Record<string, any> | null>(null); const [mapping, setMapping] = useState<Record<string, string>>({}); const [importDone, setImportDone] = useState(false);
  const current = answers[step] || {};
  useEffect(() => { if (!result.loading && !result.error) { const item = unwrapItem(result.data); if (item.data && typeof item.data === "object") setAnswers(item.data); if (Number.isInteger(item.step)) setStep(Math.min(9, Math.max(0, item.step))); } }, [result.loading, result.error, result.data]);
  function set(key: string, value: any) { setAnswers((previous) => ({ ...previous, [step]: { ...(previous[step] || {}), [key]: value } })); }
  async function advance(event: React.FormEvent) {
    event.preventDefault(); setError(""); setBusy(true);
    try {
      if (step === 6 && current.importChoice === "csv" && csv && !importDone) { setError("Review and import your CSV before continuing, or choose to add customers later."); return; }
      await api("/onboarding", patch({ step, data: answers[step] || {} }));
      if (step === 9) { await api("/onboarding/complete", body({ publishWebsite: isWebsitePublishingUsable(capabilityCatalog) && Boolean(answers[8]?.publish) })); window.location.href = "/app/dashboard"; return; }
      setStep(step + 1);
    } catch (issue) { setError((issue as Error).message); }
    finally { setBusy(false); }
  }
  async function previewCsv() { setBusy(true); setError(""); try { const response = await api<{ item: Record<string, any> }>("/imports", body({ csv, preview: true })); const item = unwrapItem(response); setCsvPreview(item); setMapping(item.mapping || {}); } catch (issue) { setError((issue as Error).message); } finally { setBusy(false); } }
  async function importCsv() { if (!csvPreview) return; if ((csvPreview.duplicates || []).length && !window.confirm("Possible duplicates will be skipped. Continue with the reviewed import?")) return; setBusy(true); setError(""); try { await api("/imports", body({ csv, mapping, confirmed: true, idempotencyKey: `onboarding-${csv.length}-${Object.keys(mapping).length}` })); setImportDone(true); setCsvPreview(null); } catch (issue) { setError((issue as Error).message); } finally { setBusy(false); } }
  if (result.loading) return <Loading label="Preparing your setup…"/>;
  if (result.error) return <div className="auth-main" style={{ minHeight: "100vh" }}><div className="auth-box"><Logo/><h2 style={{ marginTop: 30 }}>Sign in to get started</h2><p>{result.error}</p><Link href="/login" className="btn btn-primary">Go to sign in</Link></div></div>;
  if (!capabilityStepComplete) return <CapabilitySetup mode="setup" onComplete={(catalog) => { setCapabilityCatalog(catalog); setCapabilityStepComplete(true); }}/>;
  const websitePublishingUsable = isWebsitePublishingUsable(capabilityCatalog);
  return <div className="onboarding"><header className="onboarding-header"><Link href="/app/dashboard"><Logo/></Link><div className="inline-actions"><span className="muted-label">Step {step + 1} of 10</span><span className="badge badge-good">{labels[step]}</span></div></header><main className="onboarding-main"><div className="eyebrow">Your workspace starts here</div><div className="onboarding-progress" aria-label={`Step ${step + 1} of 10`}>{labels.map((_, index) => <span key={index} className={index <= step ? "done" : ""}/>)}</div><form className="card onboarding-card" onSubmit={advance}>
    {step === 0 && <><div className="eyebrow">01 · Industry</div><h1>What kind of business do you run?</h1><p>We’ll start with useful service names, workflows, and a website that fits.</p><div className="choice-grid"><button type="button" className={`choice ${current.packKey === "pet-waste-removal" || !current.packKey ? "selected" : ""}`} onClick={() => set("packKey", "pet-waste-removal")}><strong>Pet Waste Removal</strong><span>Recurring route service, one-time cleanup, and customer signup.</span></button></div><div className="notice notice-info" style={{ marginTop: 20 }}>More industry packs can be added without changing your business data.</div></>}
    {step === 1 && <><div className="eyebrow">02 · Business basics</div><h1>Tell us about your business.</h1><p>Customers will see this name and contact information on your website and messages.</p><div className="form-grid"><Field name="businessName" label="Business name" value={current.businessName} onChange={set} required/><Field name="phone" label="Business phone" type="tel" value={current.phone} onChange={set}/><Field name="email" label="Business email" type="email" value={current.email} onChange={set}/><Field name="address" label="Business address" value={current.address} onChange={set}/><div className="field"><label htmlFor="onboard-timezone">Time zone</label><select id="onboard-timezone" value={current.timezone || "America/New_York"} onChange={(event) => set("timezone", event.target.value)}><option value="America/New_York">Eastern</option><option value="America/Chicago">Central</option><option value="America/Denver">Mountain</option><option value="America/Los_Angeles">Pacific</option></select></div><div className="field"><label htmlFor="onboard-color">Brand color</label><input id="onboard-color" type="color" value={current.brandColor || "#173d35"} onChange={(event) => set("brandColor", event.target.value)}/></div></div></>}
    {step === 2 && <><div className="eyebrow">03 · Service area</div><h1>Where do you work?</h1><p>We’ll use this for customer signup and route planning.</p><div className="choice-grid">{[{ key: "zip", title: "By ZIP code", text: "Add the ZIP codes you serve." }, { key: "radius", title: "Around my business", text: "Set a distance from your base." }, { key: "later", title: "Set this later", text: "You can start using Modular now." }].map((option) => <button type="button" className={`choice ${current.areaType === option.key ? "selected" : ""}`} key={option.key} onClick={() => set("areaType", option.key)}><strong>{option.title}</strong><span>{option.text}</span></button>)}</div>{current.areaType === "zip" && <div className="field" style={{ marginTop: 20 }}><label htmlFor="onboard-zips">ZIP codes (comma separated)</label><input id="onboard-zips" value={current.zips || ""} onChange={(event) => set("zips", event.target.value)} placeholder="30901, 30904, 30907"/></div>}{current.areaType === "radius" && <div className="field" style={{ marginTop: 20 }}><label htmlFor="onboard-radius">Miles from your business</label><input id="onboard-radius" type="number" min="1" value={current.radiusMiles || ""} onChange={(event) => set("radiusMiles", Number(event.target.value))}/></div>}</>}
    {step === 3 && <><div className="eyebrow">04 · Services</div><h1>What do you offer?</h1><p>Pet Waste Removal starts with common services. Choose what applies and add starting prices if you want them public.</p><div className="stack">{[{ key: "recurring", label: "Recurring Cleanup", defaultOn: true }, { key: "one_time", label: "One-Time Cleanup", defaultOn: true }, { key: "initial", label: "Initial Cleanup", defaultOn: true }, { key: "deodorizer", label: "Deodorizer / Yard Treatment", defaultOn: false }, { key: "commercial", label: "Commercial Property Cleanup", defaultOn: false }].map((service) => <div className="card card-pad" key={service.key} style={{ boxShadow: "none", padding: 16 }}><label className="checkbox-row"><input type="checkbox" checked={current.services?.[service.key]?.enabled ?? service.defaultOn} onChange={(event) => set("services", { ...current.services, [service.key]: { ...current.services?.[service.key], enabled: event.target.checked } })}/><strong>{service.label}</strong></label>{(current.services?.[service.key]?.enabled ?? service.defaultOn) && <div className="field" style={{ marginTop: 12, maxWidth: 190 }}><label htmlFor={`price-${service.key}`}>Starting price (optional)</label><input id={`price-${service.key}`} type="number" min="0" step="0.01" value={current.services?.[service.key]?.price || ""} onChange={(event) => set("services", { ...current.services, [service.key]: { ...current.services?.[service.key], enabled: true, price: event.target.value } })}/></div>}</div>)}</div><div className="field" style={{ marginTop: 20 }}><label htmlFor="onboard-dog-price">Do additional dogs change the price?</label><select id="onboard-dog-price" value={current.additionalPetPricing || "yes"} onChange={(event) => set("additionalPetPricing", event.target.value)}><option value="yes">Yes</option><option value="no">No</option><option value="quote">I’ll quote this personally</option></select></div></>}
    {step === 4 && <><div className="eyebrow">05 · Payments</div><h1>How do you get paid?</h1><p>Choose a starting point. You can connect a real payment provider later.</p><div className="choice-grid">{[{ key: "demo", title: "Use demo payments", text: "Try invoices and payments locally without a real charge." }, { key: "manual", title: "Invoice manually", text: "Send invoices and record cash or checks." }, { key: "connect", title: "Connect a provider", text: "Choose a payment tool after setup." }].map((option) => <button type="button" className={`choice ${(current.paymentMode || "demo") === option.key ? "selected" : ""}`} key={option.key} onClick={() => set("paymentMode", option.key)}><strong>{option.title}</strong><span>{option.text}</span></button>)}</div></>}
    {step === 5 && <><div className="eyebrow">06 · Customer updates</div><h1>How should customers hear from you?</h1><p>Pick the updates you want to send. Demo mode records them without contacting real customers.</p><div className="choice-grid">{[{ key: "email", title: "Email updates", text: "Receipts, service changes, and reminders." }, { key: "sms", title: "Text updates", text: "On-the-way and service-day reminders." }].map((channel) => <div className="card card-pad" key={channel.key} style={{ boxShadow: "none" }}><h3>{channel.title}</h3><p className="subtle" style={{ fontSize: ".84rem" }}>{channel.text}</p><select className="filter-select" value={current[channel.key] || "demo"} onChange={(event) => set(channel.key, event.target.value)}><option value="demo">Use demo updates</option><option value="connect">Connect a provider after setup</option><option value="off">Turn off for now</option></select></div>)}</div></>}
    {step === 6 && <><div className="eyebrow">07 · Customers</div><h1>Bring your customers.</h1><p>Starting fresh works too. You can import at any time from Settings.</p><div className="choice-grid">{[{ key: "fresh", title: "I’m starting fresh", text: "Add customers as they arrive." }, { key: "csv", title: "Upload a spreadsheet", text: "We’ll review column matches first." }, { key: "later", title: "I’ll do this later", text: "Continue without importing." }].map((option) => <button type="button" className={`choice ${(current.importChoice || "fresh") === option.key ? "selected" : ""}`} key={option.key} onClick={() => set("importChoice", option.key)}><strong>{option.title}</strong><span>{option.text}</span></button>)}</div>{current.importChoice === "csv" && <div className="card card-pad" style={{ marginTop: 19, boxShadow: "none" }}><div className="field"><label htmlFor="onboard-csv">CSV file</label><input id="onboard-csv" type="file" accept=".csv,text/csv" onChange={async (event) => { const file = event.target.files?.[0]; if (file) { setCsv(await file.text()); setCsvPreview(null); setImportDone(false); } }}/></div>{csv && !csvPreview && !importDone && <button type="button" className="btn btn-secondary btn-sm" style={{ marginTop: 13 }} disabled={busy} onClick={previewCsv}>Review rows</button>}{csvPreview && <div style={{ marginTop: 18 }}><p className="subtle" style={{ fontSize: ".84rem" }}>{csvPreview.rowCount ?? csvPreview.previewRows?.length ?? 0} rows found. Check the column matches before importing.</p><div className="form-grid">{(csvPreview.columns || Object.keys(mapping)).map((column: string) => <div className="field" key={column}><label htmlFor={`onboard-map-${column}`}>{column}</label><select id={`onboard-map-${column}`} value={mapping[column] || ""} onChange={(event) => setMapping({ ...mapping, [column]: event.target.value })}><option value="">Ignore</option>{["name", "email", "phone", "address", "notes"].map((target) => <option key={target} value={target}>{target}</option>)}</select></div>)}</div>{(csvPreview.duplicates || []).length > 0 && <div className="notice notice-info" style={{ marginTop: 14 }}>{csvPreview.duplicates.length} possible duplicate rows will be skipped for review.</div>}<button type="button" className="btn btn-primary btn-sm" style={{ marginTop: 16 }} disabled={busy} onClick={importCsv}>Import reviewed customers</button></div>}{importDone && <div style={{ marginTop: 14 }}><Notice kind="success" text="Customers imported successfully."/></div>}</div>}</>}
    {step === 7 && <><div className="eyebrow">08 · Schedule</div><h1>Plan your normal week.</h1><p>Choose the days you work. You can fine-tune routes and staff later.</p><div className="field"><span className="field-label">Working days</span><div className="inline-actions">{["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"].map((day) => <button key={day} type="button" className={`day-toggle ${(current.workDays || ["Mon", "Tue", "Wed", "Thu", "Fri"]).includes(day) ? "selected" : ""}`} onClick={() => { const days = current.workDays || ["Mon", "Tue", "Wed", "Thu", "Fri"]; set("workDays", days.includes(day) ? days.filter((entry: string) => entry !== day) : [...days, day]); }}>{day}</button>)}</div></div><div className="form-grid" style={{ marginTop: 23 }}><div className="field"><label htmlFor="onboard-techs">How many technicians do you have now?</label><input id="onboard-techs" type="number" min="0" value={current.technicianCount ?? 1} onChange={(event) => set("technicianCount", Number(event.target.value))}/></div><div className="field"><label htmlFor="onboard-worker">Will you work in the field?</label><select id="onboard-worker" value={current.ownerFieldWorker ? "yes" : "no"} onChange={(event) => set("ownerFieldWorker", event.target.value === "yes")}><option value="no">No</option><option value="yes">Yes</option></select></div></div></>}
    {step === 8 && <>{websitePublishingUsable ? <><div className="eyebrow">09 · Website</div><h1>Your site is taking shape.</h1><p>Use the business details you entered to create a simple, professional website.</p><div className="detail-grid"><div className="stack"><Field name="tagline" label="Headline" value={current.tagline} onChange={set} placeholder="A cleaner yard. A better day."/><div className="field"><label htmlFor="onboard-description">Short description</label><textarea id="onboard-description" value={current.description || ""} onChange={(event) => set("description", event.target.value)} placeholder="Friendly local cleanup service for your home and pets."/></div><Field name="hours" label="Business hours" value={current.hours} onChange={set} placeholder="Monday–Friday, 8am–5pm"/></div><div className="card card-pad" style={{ boxShadow: "none", background: "#f4f8ee" }}><div className="eyebrow">Preview</div><h2 style={{ margin: "12px 0 7px" }}>{answers[1]?.businessName || "Your business"}</h2><h3 style={{ color: "#3f8056" }}>{current.tagline || "A cleaner yard. A better day."}</h3><p className="subtle" style={{ fontSize: ".84rem" }}>{current.description || "Your business description will appear here."}</p><span className="muted-label">Serving {answers[2]?.zips || "your local area"}</span></div></div><label className="checkbox-row" style={{ marginTop: 24 }}><input type="checkbox" checked={Boolean(current.publish)} onChange={(event) => set("publish", event.target.checked)}/>Publish to my platform website address when setup is complete</label></> : <><div className="eyebrow">09 · Website</div><h1>You can skip the website for now.</h1><p>Website publishing isn’t part of the tools you selected. Continue setup without publishing a site. You can review your capabilities later from your workspace.</p><div className="notice notice-info" style={{ marginTop: 20 }}>Your other setup details will still be saved, and you can choose website publishing later from My capabilities.</div></>}</>}
    {step === 9 && <><div className="eyebrow">10 · Ready to go</div><h1>Your business is ready.</h1><p>Review your setup. You can change any of these details from your dashboard later.</p><div className="two-col">{[{ title: "Business", value: answers[1]?.businessName || "Ready" }, { title: "Industry", value: "Pet Waste Removal" }, { title: "Service area", value: answers[2]?.areaType === "zip" ? answers[2]?.zips || "ZIP codes" : answers[2]?.areaType === "radius" ? `${answers[2]?.radiusMiles || "—"} miles` : "Set later" }, { title: "Payments", value: answers[4]?.paymentMode === "manual" ? "Manual invoices" : answers[4]?.paymentMode === "connect" ? "Connect later" : "Demo payments" }, { title: "Messages", value: `Email: ${answers[5]?.email || "demo"}, texts: ${answers[5]?.sms || "demo"}` }, { title: "Customers", value: importDone ? "Imported" : "Ready to add" }, { title: "Website", value: websitePublishingUsable ? answers[8]?.publish ? "Publish on completion" : "Save as draft" : "Not included in selected tools" }, { title: "Team", value: `${answers[7]?.technicianCount ?? 1} technician${(answers[7]?.technicianCount ?? 1) === 1 ? "" : "s"}` }].map((entry) => <div className="review-item" key={entry.title}><Icon name="check" size={18}/><span><strong>{entry.title}</strong><small>{entry.value}</small></span></div>)}</div></>}
    {error && <div style={{ marginTop: 20 }}><Notice kind="error" text={error}/></div>}<div className="onboarding-footer">{step > 0 ? <button type="button" className="btn btn-secondary" onClick={() => { setError(""); setStep(step - 1); }}>Back</button> : <span/>}<button type="submit" className="btn btn-primary" disabled={busy}>{busy ? "Saving…" : step === 9 ? "Go to my dashboard" : "Continue"} <Icon name="arrow" size={16}/></button></div>
  </form></main></div>;
}

function Field({ name, label, value, onChange, type = "text", required = false, placeholder }: { name: string; label: string; value?: string; onChange: (key: string, value: string) => void; type?: string; required?: boolean; placeholder?: string }) {
  return <div className="field"><label htmlFor={`onboard-${name}`}>{label}</label><input id={`onboard-${name}`} type={type} required={required} value={value || ""} placeholder={placeholder} onChange={(event) => onChange(name, event.target.value)}/></div>;
}
