"use client";

import Link from "next/link";
import { useState } from "react";
import { api, body, money, unwrapItem } from "./api";
import { Icon, Loading, Notice, useResource } from "./ui";

type SiteData = Record<string, any>;

function SiteLogo({ name }: { name: string }) { return <span className="site-brand"><span className="site-brand-icon"><Icon name="spark" size={23}/></span>{name}</span>; }

export default function PublicSite({ slug }: { slug: string }) {
  const result = useResource<{ item: SiteData }>(`/public/site?slug=${encodeURIComponent(slug)}`, { item: {} });
  const site = unwrapItem(result.data);
  const [address, setAddress] = useState(""); const [zip, setZip] = useState(""); const [eligibility, setEligibility] = useState<{ eligible?: boolean; message?: string } | null>(null); const [checking, setChecking] = useState(false); const [eligibilityError, setEligibilityError] = useState("");
  const [contactName, setContactName] = useState(""); const [contactEmail, setContactEmail] = useState(""); const [contactPhone, setContactPhone] = useState(""); const [contactMessage, setContactMessage] = useState(""); const [contactError, setContactError] = useState(""); const [contactSuccess, setContactSuccess] = useState(""); const [sending, setSending] = useState(false);
  async function check(event: React.FormEvent) { event.preventDefault(); setChecking(true); setEligibilityError(""); try { const response = await api<{ item: { eligible?: boolean; message?: string } }>("/public/eligibility", body({ slug, address, zip })); setEligibility(unwrapItem(response)); } catch (issue) { setEligibilityError((issue as Error).message); } finally { setChecking(false); } }
  async function contact(event: React.FormEvent) { event.preventDefault(); setSending(true); setContactError(""); try { await api("/public/contact", body({ slug, name: contactName, email: contactEmail, phone: contactPhone, message: contactMessage })); setContactSuccess("Thanks! Your message was sent. We’ll be in touch soon."); setContactName(""); setContactEmail(""); setContactPhone(""); setContactMessage(""); } catch (issue) { setContactError((issue as Error).message); } finally { setSending(false); } }
  if (result.loading) return <Loading label="Opening the website…"/>;
  if (result.error) return <div className="auth-main" style={{ minHeight: "100vh" }}><div className="auth-box"><h1>Website unavailable</h1><p>{result.error}</p><Link href="/login" className="btn btn-secondary">Customer login</Link></div></div>;
  const name = site.businessName || "Local service";
  const services: SiteData[] = site.services || [];
  return <div className="site"><header className="site-header"><div className="site-header-inner"><Link href={`/site/${slug}`}><SiteLogo name={name}/></Link><nav className="site-nav" aria-label="Website navigation"><a href="#services">Services</a><a href="#how-it-works">How it works</a><a href="#area">Service area</a>{(site.faqs || []).length > 0 && <a href="#faq">FAQs</a>}<a href="#contact">Contact</a><Link href="/login">Customer login</Link></nav><Link className="btn btn-primary btn-sm" href={`/site/${slug}/signup`}>Get started <Icon name="arrow" size={15}/></Link></div></header>
    <main><section className="site-hero"><div className="site-inner site-hero-grid"><div><div className="eyebrow">A cleaner yard. A better day.</div><h1>{site.tagline || `Fresh, dependable service from ${name}.`}</h1><p>{site.description || `Friendly local service for families throughout ${site.serviceArea || "our community"}.`}</p><div className="inline-actions"><Link className="btn btn-primary" href={`/site/${slug}/signup`}>Get my quote <Icon name="arrow" size={17}/></Link><a className="btn btn-secondary" href="#how-it-works">See how it works</a></div><div className="site-trust"><span><Icon name="check" size={15}/> Easy signup</span><span><Icon name="check" size={15}/> Reliable visits</span><span><Icon name="check" size={15}/> Local team</span></div></div><div className="site-hero-card" aria-hidden="true"><div className="site-hero-illustration"><svg viewBox="0 0 350 230" fill="none" xmlns="http://www.w3.org/2000/svg"><circle cx="250" cy="72" r="51" fill="#EAF5D8"/><path d="M33 177C104 114 164 165 220 141C263 122 310 141 344 164V229H33V177Z" fill="#CEE7AB"/><path d="M0 188C84 168 135 181 198 169C269 156 319 174 350 186V230H0V188Z" fill="#94C97D"/><path d="M76 161V91L151 43L226 91V161" fill="#F7EECF" stroke="#2F6C4A" strokeWidth="5" strokeLinejoin="round"/><path d="M68 94L151 39L234 94" stroke="#2F6C4A" strokeWidth="11" strokeLinecap="round" strokeLinejoin="round"/><rect x="139" y="111" width="32" height="50" rx="3" fill="#77AA73"/><rect x="95" y="106" width="23" height="23" rx="3" fill="#D3EEC8" stroke="#2F6C4A" strokeWidth="4"/><path d="M262 149c-3-16 2-29 17-33 11-3 20 2 26 10l12 2 3 10-11 4c0 16-8 24-26 24h-13" fill="#6D8E63"/><path d="M263 152c-8 0-17 7-17 14h-12" stroke="#486B4D" strokeWidth="7" strokeLinecap="round"/><path d="M283 163v14M300 161v16" stroke="#486B4D" strokeWidth="7" strokeLinecap="round"/><path d="M275 115c-4-15-14-18-24-15 0 11 8 18 19 20" fill="#6D8E63"/><circle cx="300" cy="129" r="2.5" fill="#173D35"/><path d="M321 139c5-6 9-12 8-20" stroke="#486B4D" strokeWidth="6" strokeLinecap="round"/></svg></div><div className="site-hero-card-bottom"><Icon name="spark" size={21}/> More free time, less to worry about.</div></div></div></section>
      <section className="site-section" id="services"><div className="site-inner"><div className="eyebrow">What we do</div><h2>Service that fits your day.</h2><p className="site-section-intro">Choose the right visit for your home or property. We’ll help with the details.</p><div className="three-col">{services.length ? services.slice(0, 6).map((service) => <div className="site-service-card" key={service.id || service.key}><div className="site-service-icon"><Icon name="spark" size={21}/></div><h3>{service.name}</h3><p>{service.description || "Dependable service from a local team."}</p><div className="inline-actions" style={{ justifyContent: "space-between" }}><strong>{service.basePriceCents ? `From ${money(service.basePriceCents)}` : "Get a quote"}</strong><Link href={`/site/${slug}/signup`} className="link">Get started</Link></div></div>) : <div className="card card-pad"><h3>Personal service</h3><p className="subtle">Tell us what you need and we’ll help find the right fit.</p><Link className="link" href={`/site/${slug}/signup`}>Request service</Link></div>}</div></div></section>
      <section className="site-section site-band" id="how-it-works"><div className="site-inner"><div className="eyebrow" style={{ color: "var(--mint)" }}>Simple from start to finish</div><h2>How it works</h2><p className="site-section-intro">A few quick steps, then we’ll take care of the rest.</p><div className="steps"><div><span className="step-number">1</span><h3>Tell us about your place</h3><p>Enter your address and choose the service you want.</p></div><div><span className="step-number">2</span><h3>Get a clear next step</h3><p>See a price when available, or receive a personal quote.</p></div><div><span className="step-number">3</span><h3>Enjoy your time back</h3><p>We’ll confirm your plan and keep you updated on visits.</p></div></div></div></section>
      <section className="site-section" id="area"><div className="site-inner two-col"><div><div className="eyebrow">Local to you</div><h2>Check your service area.</h2><p className="site-section-intro">We currently serve {site.serviceArea || "our local community"}. Enter your address and we’ll tell you what’s available.</p></div><form className="card card-pad" onSubmit={check}><div className="field"><label htmlFor="eligibility-address">Service address</label><input id="eligibility-address" required value={address} onChange={(event) => setAddress(event.target.value)} placeholder="123 Main Street"/></div><div className="field" style={{ marginTop: 13 }}><label htmlFor="eligibility-zip">ZIP code</label><input id="eligibility-zip" required inputMode="numeric" value={zip} onChange={(event) => setZip(event.target.value)} placeholder="30901"/></div><button className="btn btn-primary" style={{ marginTop: 17 }} type="submit" disabled={checking}>{checking ? "Checking…" : "Check availability"}</button>{eligibilityError && <div style={{ marginTop: 13 }}><Notice kind="error" text={eligibilityError}/></div>}{eligibility && <div style={{ marginTop: 13 }}><Notice kind={eligibility.eligible ? "success" : "info"} text={eligibility.message || (eligibility.eligible ? "Good news—we serve your area." : "We can still review your request personally.")}/><Link className="link" href={`/site/${slug}/signup`} style={{ display: "inline-block", marginTop: 11 }}>Continue to service request</Link></div>}</form></div></section>
      {(site.faqs || []).length > 0 && <section className="site-section" id="faq" style={{ background: "#f5f8f0" }}><div className="site-inner"><div className="eyebrow">Good to know</div><h2>Frequently asked questions</h2><div className="site-faq">{site.faqs.map((faq: SiteData, index: number) => <details key={index}><summary>{faq.question}</summary><p>{faq.answer}</p></details>)}</div></div></section>}
      <section className="site-section" id="contact"><div className="site-inner two-col"><div><div className="eyebrow">Let’s talk</div><h2>Questions? We’re here.</h2><p className="site-section-intro">Send a message and our local team will follow up.</p>{site.phone && <p><strong>Call</strong> <a className="link" href={`tel:${site.phone}`}>{site.phone}</a></p>}{site.email && <p><strong>Email</strong> <a className="link" href={`mailto:${site.email}`}>{site.email}</a></p>}</div><form className="card card-pad" onSubmit={contact}><div className="form-grid"><div className="field"><label htmlFor="contact-name">Your name</label><input id="contact-name" required value={contactName} onChange={(event) => setContactName(event.target.value)}/></div><div className="field"><label htmlFor="contact-email">Email</label><input id="contact-email" type="email" required value={contactEmail} onChange={(event) => setContactEmail(event.target.value)}/></div><div className="field"><label htmlFor="contact-phone">Phone (optional)</label><input id="contact-phone" type="tel" value={contactPhone} onChange={(event) => setContactPhone(event.target.value)}/></div><div className="field full"><label htmlFor="contact-message">Your message</label><textarea id="contact-message" required value={contactMessage} onChange={(event) => setContactMessage(event.target.value)}/></div></div>{contactError && <div style={{ marginTop: 12 }}><Notice kind="error" text={contactError}/></div>}{contactSuccess && <div style={{ marginTop: 12 }}><Notice kind="success" text={contactSuccess}/></div>}<button type="submit" className="btn btn-primary" style={{ marginTop: 17 }} disabled={sending}>{sending ? "Sending…" : "Send message"}</button></form></div></section></main><footer className="site-footer"><div className="site-footer-inner"><div><SiteLogo name={name}/><p>Serving {site.serviceArea || "our community"}</p><p>© {new Date().getFullYear()} {name}</p></div><div className="site-footer-links"><a href="#services">Services</a><a href="#area">Service area</a><a href="#contact">Contact</a><Link href="/login">Customer login</Link></div></div></footer></div>;
}

