"use client";

import Link from "next/link";
import type { IndustryPack } from "@modular-crm/industry-packs";
import { PackFields } from "./PackFields";
import { useEffect, useRef, useState } from "react";
import { api, body, money, unwrapItem } from "./api";
import { Icon, Loading, Notice, useResource } from "./ui";

type ServiceItem = { assetTypeKey: string; name: string; customFields: Record<string, unknown> };

export default function PublicSignup({ slug, allowDemoPayments = false, loginUrl = "/login" }: { slug: string; allowDemoPayments?: boolean; loginUrl?: string }) {
  const siteResult = useResource<{ item: Record<string, any> }>(`/public/site?slug=${encodeURIComponent(slug)}`, { item: {} });
  const site = unwrapItem(siteResult.data);
  const pack = site.pack as IndustryPack | undefined;
  const steps = pack?.formSteps ?? [];
  const finalStep = steps.findIndex(item => item.fields.includes("terms_accepted"));
  const [assets, setAssets] = useState<ServiceItem[]>([]);
  const [locationFields, setLocationFields] = useState<Record<string, unknown>>({});
  const [step, setStep] = useState(0); const [address, setAddress] = useState(""); const [zip, setZip] = useState(""); const [eligible, setEligible] = useState<boolean | null>(null); const [eligibilityMessage, setEligibilityMessage] = useState("");
  const stepFields = steps[step]?.fields ?? [];
  const [contact, setContact] = useState({ name: "", email: "", phone: "" });
  const [serviceId, setServiceId] = useState(""); const [frequency, setFrequency] = useState("weekly"); const [preferredDay, setPreferredDay] = useState("");
  const [quote, setQuote] = useState<Record<string, any> | null>(null); const [quoteUnavailable, setQuoteUnavailable] = useState(false); const [terms, setTerms] = useState(false); const [demoPayment, setDemoPayment] = useState(false); const [result, setResult] = useState<Record<string, any> | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const idempotencyKey = useRef("");
  useEffect(() => { if (!pack) return; setAssets(pack.assets.map(def => ({ assetTypeKey: def.key, name: "", customFields: {} }))); setLocationFields(Object.fromEntries(pack.locationFields.filter(field => field.signupVisible && field.defaultValue !== undefined).map(field => [field.key, field.defaultValue]))); }, [pack]);
  const services: Record<string, any>[] = site.services || [];
  const selectedService = services.find((service) => service.id === serviceId || service.key === serviceId);
  async function next(event: React.FormEvent) {
    event.preventDefault(); setError("");
    if (stepFields.includes("service_address")) { setBusy(true); try { const response = await api<{ item: { eligible?: boolean; message?: string } }>("/public/eligibility", body({ slug, address, zip })); const info = unwrapItem(response); setEligible(Boolean(info.eligible)); setEligibilityMessage(info.message || (info.eligible ? "Great! Your address is in our service area." : "We’ll review your address personally.")); setStep(step + 1); } catch (issue) { setError((issue as Error).message); } finally { setBusy(false); } return; }
    if (stepFields.includes("service") && !serviceId) { setError("Choose a service to continue."); return; }
    if (assets.some(item => stepFields.includes(item.assetTypeKey) && !item.name.trim())) { setError("Add a name for each service item."); return; }
    if (step === finalStep - 1) { await getQuote(); return; }
    if (step === finalStep) { await submit(); return; }
    setStep(step + 1);
  }
  async function getQuote() {
    setBusy(true); setError(""); setQuoteUnavailable(false);
    try { const response = await api<{ item: Record<string, any> }>("/public/quote", body({ slug, address, zip, serviceId, serviceKey: selectedService?.key, frequency, assets, locationFields, preferredDay })); setQuote(unwrapItem(response)); }
    catch { setQuoteUnavailable(true); }
    finally { setBusy(false); setStep(finalStep); }
  }
  async function submit() {
    if (!terms) { setError("Please accept the service terms to continue."); return; }
    setBusy(true); setError("");
    try {
      // randomUUID requires HTTPS; local custom-host fixtures use HTTP. Both
      // paths use browser cryptographic randomness and retain the key on retry.
      if (!idempotencyKey.current) idempotencyKey.current = globalThis.crypto.randomUUID?.() ?? Array.from(globalThis.crypto.getRandomValues(new Uint8Array(16)), byte => byte.toString(16).padStart(2, "0")).join("");
      const response = await api<{ item: Record<string, any> }>("/public/signup", body({ slug, address, zip, contact, service: { id: serviceId, key: selectedService?.key, frequency }, assets, locationFields, preferredDay, quoteId: quote?.id, paymentMethod: allowDemoPayments && demoPayment && eligible && quote?.amountCents ? "demo" : undefined, notificationPreferences: { email: true, sms: true }, termsAccepted: terms, termsVersion: site.termsVersion || "v1", idempotencyKey: idempotencyKey.current })); setResult(unwrapItem(response)); setStep(steps.length);
    }
    catch (issue) { setError((issue as Error).message); }
    finally { setBusy(false); }
  }
  if (siteResult.loading) return <Loading label="Preparing your signup…"/>;
  if (siteResult.error) return <div className="auth-main" style={{ minHeight: "100vh" }}><div className="auth-box"><h1>Signup unavailable</h1><p>{siteResult.error}</p><Link href={`/site/${slug}`} className="btn btn-secondary">Back to website</Link></div></div>;
  return <div className="signup-page"><header className="signup-header"><Link href={`/site/${slug}`} className="site-brand"><span className="site-brand-icon"><Icon name="spark" size={22}/></span>{site.businessName || "Service team"}</Link></header><main className="signup-shell"><div className="card signup-panel">{step === steps.length ? <div className="signup-success"><div className="empty-icon"><Icon name="check" size={27}/></div><div className="eyebrow">Request received</div><h1>{result?.kind === "customer" || result?.status === "active" ? "You’re all set!" : "Thanks, we’ll be in touch."}</h1><p className="subtle">{result?.message || (eligible ? "We’ve received your service details and will confirm your next step soon." : "Your address needs a personal review. Our team will follow up with a quote.")}</p><div className="inline-actions" style={{ justifyContent: "center", marginTop: 22 }}><Link className="btn btn-primary" href={loginUrl}>Customer login</Link><Link className="btn btn-secondary" href={`/site/${slug}`}>Back to website</Link></div></div> : <><div className="eyebrow">Get started with {site.businessName || "our team"}</div><h1>{steps[step]?.label || "Service details"}</h1><p>{["We’ll check that your address is in our service area.", "We’ll use this to confirm service and send updates.", "Pick what works for your household. You can review the details later.", "These details help your technician arrive prepared.", "Check everything below, then send it to our local team."][step]}</p><div className="signup-steps" aria-label={`Step ${step + 1} of ${steps.length}`}>{Array.from({ length: steps.length }, (_, index) => <span key={index} className={index <= step ? "done" : ""}/>)}</div>{error && <div style={{ marginBottom: 16 }}><Notice kind="error" text={error}/></div>}{eligibilityMessage && step > 0 && <div style={{ marginBottom: 15 }}><Notice kind={eligible ? "success" : "info"} text={eligibilityMessage}/></div>}
      <form onSubmit={next}>{stepFields.includes("service_address") && <div className="form-grid"><div className="field full"><label htmlFor="signup-address">Street address</label><input id="signup-address" required autoComplete="street-address" value={address} onChange={(event) => setAddress(event.target.value)} placeholder="123 Main Street"/></div><div className="field"><label htmlFor="signup-zip">ZIP code</label><input id="signup-zip" required inputMode="numeric" autoComplete="postal-code" value={zip} onChange={(event) => setZip(event.target.value)} placeholder="30901"/></div></div>}
        {stepFields.includes("email") && <div className="form-grid"><div className="field full"><label htmlFor="signup-name">Full name</label><input id="signup-name" required autoComplete="name" value={contact.name} onChange={(event) => setContact({ ...contact, name: event.target.value })}/></div><div className="field"><label htmlFor="signup-email">Email</label><input id="signup-email" type="email" required autoComplete="email" value={contact.email} onChange={(event) => setContact({ ...contact, email: event.target.value })}/></div><div className="field"><label htmlFor="signup-phone">Phone</label><input id="signup-phone" type="tel" required autoComplete="tel" value={contact.phone} onChange={(event) => setContact({ ...contact, phone: event.target.value })}/></div></div>}
        {stepFields.includes("service") && <div className="stack"><div className="form-grid"><div className="field"><label htmlFor="signup-service">Service</label><select id="signup-service" required value={serviceId} onChange={(event) => setServiceId(event.target.value)}><option value="">Choose a service</option>{services.map((service) => <option key={service.id || service.key} value={service.id || service.key}>{service.name}</option>)}</select></div><div className="field"><label htmlFor="signup-frequency">How often?</label><select id="signup-frequency" value={frequency} onChange={(event) => setFrequency(event.target.value)}>{pack?.recurrencePresets.filter(preset => preset.rrule).map(preset => <option key={preset.key} value={preset.key.replaceAll("-", "_")}>{preset.label}</option>)}<option value="one_time">Just once</option></select></div></div></div>}
        {pack?.assets.filter(def => stepFields.includes(def.key)).map(def => <div className="card card-pad" key={def.key}><div className="card-heading"><h2>Your {def.pluralLabel.toLowerCase()}</h2><button type="button" className="btn btn-secondary btn-sm" disabled={assets.length >= 20} onClick={() => setAssets([...assets, { assetTypeKey: def.key, name: "", customFields: {} }])}>Add {def.label.toLowerCase()}</button></div>{assets.filter(item => item.assetTypeKey === def.key).map(item => { const index = assets.indexOf(item); return <div className="form-grid" key={index}><PackFields fields={def.fields.filter(field => field.signupVisible)} values={{ ...item.customFields, name: item.name }} prefix={`signup-item-${index}`} labelPrefix={`${def.label} ${index + 1} `} onChange={(key, value) => setAssets(assets.map((entry, i) => i !== index ? entry : key === "name" ? { ...entry, name: String(value) } : { ...entry, customFields: { ...entry.customFields, [key]: value } }))}/><button type="button" className="btn btn-secondary btn-sm" disabled={pack?.intake?.quantity.assetTypeKey === def.key && assets.filter(entry => entry.assetTypeKey === def.key).length <= 1} onClick={() => setAssets(assets.filter((_, i) => i !== index))}>Remove {def.label.toLowerCase()}</button></div>; })}</div>)}
        {pack && <div className="form-grid"><PackFields fields={pack.locationFields.filter(field => field.signupVisible && stepFields.includes(field.key))} values={locationFields} prefix="signup-property" onChange={(key, value) => setLocationFields({ ...locationFields, [key]: value })}/>{step === finalStep - 1 && <div className="field"><label htmlFor="preferred-day">Preferred service day (optional)</label><select id="preferred-day" value={preferredDay} onChange={event => setPreferredDay(event.target.value)}><option value="">No preference</option>{["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"].map(day => <option key={day} value={day.toLowerCase()}>{day}</option>)}</select></div>}</div>}

        {step === finalStep && <div className="stack"><div className="quote-result"><div className="eyebrow">Your next step</div>{eligible && quote?.amountCents != null && !quote.quoteRequired ? <><strong>{money(quote.amountCents)}</strong><p style={{ margin: "4px 0 0", fontSize: ".85rem" }}>{quote.intervalLabel || "Estimated service price"}. We’ll confirm before service begins.</p></> : <><strong>Personal quote</strong><p style={{ margin: "4px 0 0", fontSize: ".85rem" }}>{!eligible ? "Your location needs review. We’ll get back to you with options." : quoteUnavailable ? "We couldn’t calculate a price just now. We’ll review your details and follow up." : "We’ll review your service details and send a clear quote."}</p></>}</div><div className="card card-pad" style={{ boxShadow: "none" }}><div className="detail-list"><dt>Address</dt><dd>{address}, {zip}</dd></div><div className="detail-list"><dt>Service</dt><dd>{selectedService?.name || "Service"} · {frequency.replaceAll("_", " ")}</dd></div><div className="detail-list"><dt>{pack?.assets.map(def => def.pluralLabel).join(", ") || "Service details"}</dt><dd>{assets.map(item => item.name).join(", ")}</dd></div><div className="detail-list"><dt>Contact</dt><dd>{contact.name} · {contact.email}</dd></div></div>{allowDemoPayments && eligible && quote?.amountCents != null && !quote.quoteRequired && <label className="checkbox-row"><input type="checkbox" checked={demoPayment} onChange={(event) => setDemoPayment(event.target.checked)}/>Use a demo payment method for local testing. No real charge will be made.</label>}<label className="checkbox-row"><input type="checkbox" checked={terms} required onChange={(event) => setTerms(event.target.checked)}/>I agree to be contacted about this request and accept the service terms.</label></div>}
        <div className="onboarding-footer">{step > 0 ? <button type="button" className="btn btn-secondary" onClick={() => setStep(step - 1)}>Back</button> : <Link className="btn btn-secondary" href={`/site/${slug}`}>Back to website</Link>}<button type="submit" className="btn btn-primary" disabled={busy}>{busy ? "One moment…" : stepFields.includes("service_address") ? "Check availability" : step === finalStep - 1 ? "See my price" : step === finalStep ? "Send service request" : "Continue"} <Icon name="arrow" size={16}/></button></div>
      </form></>}</div></main></div>;
}
