"use client";

import Link from "next/link";
import { useRef, useState } from "react";
import { api, body, money, unwrapItem } from "./api";
import { Icon, Loading, Notice, useResource } from "./ui";

type Pet = { name: string; size: string };

export default function PublicSignup({ slug }: { slug: string }) {
  const siteResult = useResource<{ item: Record<string, any> }>(`/public/site?slug=${encodeURIComponent(slug)}`, { item: {} });
  const site = unwrapItem(siteResult.data);
  const [step, setStep] = useState(0); const [address, setAddress] = useState(""); const [zip, setZip] = useState(""); const [eligible, setEligible] = useState<boolean | null>(null); const [eligibilityMessage, setEligibilityMessage] = useState("");
  const [contact, setContact] = useState({ name: "", email: "", phone: "" });
  const [serviceId, setServiceId] = useState(""); const [frequency, setFrequency] = useState("weekly"); const [pets, setPets] = useState<Pet[]>([{ name: "", size: "medium" }]); const [yardSize, setYardSize] = useState("medium"); const [gateCode, setGateCode] = useState(""); const [accessNotes, setAccessNotes] = useState(""); const [preferredDay, setPreferredDay] = useState("");
  const [quote, setQuote] = useState<Record<string, any> | null>(null); const [quoteUnavailable, setQuoteUnavailable] = useState(false); const [terms, setTerms] = useState(false); const [demoPayment, setDemoPayment] = useState(false); const [result, setResult] = useState<Record<string, any> | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const idempotencyKey = useRef("");
  const services: Record<string, any>[] = site.services || [];
  const selectedService = services.find((service) => service.id === serviceId || service.key === serviceId);
  async function next(event: React.FormEvent) {
    event.preventDefault(); setError("");
    if (step === 0) { setBusy(true); try { const response = await api<{ item: { eligible?: boolean; message?: string } }>("/public/eligibility", body({ slug, address, zip })); const info = unwrapItem(response); setEligible(Boolean(info.eligible)); setEligibilityMessage(info.message || (info.eligible ? "Great! Your address is in our service area." : "We’ll review your address personally.")); setStep(1); } catch (issue) { setError((issue as Error).message); } finally { setBusy(false); } return; }
    if (step === 1) { setStep(2); return; }
    if (step === 2) { if (!serviceId) { setError("Choose a service to continue."); return; } if (pets.some((pet) => !pet.name.trim())) { setError("Add a name for each pet."); return; } setStep(3); return; }
    if (step === 3) { await getQuote(); return; }
    if (step === 4) { await submit(); }
  }
  async function getQuote() {
    setBusy(true); setError(""); setQuoteUnavailable(false);
    try { const response = await api<{ item: Record<string, any> }>("/public/quote", body({ slug, address, zip, serviceId, serviceKey: selectedService?.key, frequency, petCount: pets.length, pets, yardSize, preferredDay })); setQuote(unwrapItem(response)); }
    catch { setQuoteUnavailable(true); }
    finally { setBusy(false); setStep(4); }
  }
  async function submit() {
    if (!terms) { setError("Please accept the service terms to continue."); return; }
    setBusy(true); setError("");
    if (!idempotencyKey.current) idempotencyKey.current = crypto.randomUUID();
    try { const response = await api<{ item: Record<string, any> }>("/public/signup", body({ slug, address, zip, contact, service: { id: serviceId, key: selectedService?.key, frequency }, pets, yard: { size: yardSize, gateCode, accessNotes }, preferredDay, quoteId: quote?.id, paymentMethod: demoPayment && eligible && quote?.amountCents ? "demo" : undefined, notificationPreferences: { email: true, sms: true }, termsAccepted: terms, termsVersion: site.termsVersion || "v1", idempotencyKey: idempotencyKey.current })); setResult(unwrapItem(response)); setStep(5); }
    catch (issue) { setError((issue as Error).message); }
    finally { setBusy(false); }
  }
  function updatePet(index: number, key: keyof Pet, value: string) { const next = [...pets]; next[index] = { ...next[index], [key]: value }; setPets(next); }
  if (siteResult.loading) return <Loading label="Preparing your signup…"/>;
  if (siteResult.error) return <div className="auth-main" style={{ minHeight: "100vh" }}><div className="auth-box"><h1>Signup unavailable</h1><p>{siteResult.error}</p><Link href={`/site/${slug}`} className="btn btn-secondary">Back to website</Link></div></div>;
  return <div className="signup-page"><header className="signup-header"><Link href={`/site/${slug}`} className="site-brand"><span className="site-brand-icon"><Icon name="spark" size={22}/></span>{site.businessName || "Service team"}</Link></header><main className="signup-shell"><div className="card signup-panel">{step === 5 ? <div className="signup-success"><div className="empty-icon"><Icon name="check" size={27}/></div><div className="eyebrow">Request received</div><h1>{result?.kind === "customer" || result?.status === "active" ? "You’re all set!" : "Thanks, we’ll be in touch."}</h1><p className="subtle">{result?.message || (eligible ? "We’ve received your service details and will confirm your next step soon." : "Your address needs a personal review. Our team will follow up with a quote.")}</p><div className="inline-actions" style={{ justifyContent: "center", marginTop: 22 }}><Link className="btn btn-primary" href="/login">Customer login</Link><Link className="btn btn-secondary" href={`/site/${slug}`}>Back to website</Link></div></div> : <><div className="eyebrow">Get started with {site.businessName || "our team"}</div><h1>{["Where can we help?", "How can we reach you?", "Choose your service", "Tell us about your property", "Review your request"][step]}</h1><p>{["We’ll check that your address is in our service area.", "We’ll use this to confirm service and send updates.", "Pick what works for your household. You can review the details later.", "These details help your technician arrive prepared.", "Check everything below, then send it to our local team."][step]}</p><div className="signup-steps" aria-label={`Step ${step + 1} of 5`}>{Array.from({ length: 5 }, (_, index) => <span key={index} className={index <= step ? "done" : ""}/>)}</div>{error && <div style={{ marginBottom: 16 }}><Notice kind="error" text={error}/></div>}{eligibilityMessage && step > 0 && <div style={{ marginBottom: 15 }}><Notice kind={eligible ? "success" : "info"} text={eligibilityMessage}/></div>}
      <form onSubmit={next}>{step === 0 && <div className="form-grid"><div className="field full"><label htmlFor="signup-address">Street address</label><input id="signup-address" required autoComplete="street-address" value={address} onChange={(event) => setAddress(event.target.value)} placeholder="123 Main Street"/></div><div className="field"><label htmlFor="signup-zip">ZIP code</label><input id="signup-zip" required inputMode="numeric" autoComplete="postal-code" value={zip} onChange={(event) => setZip(event.target.value)} placeholder="30901"/></div></div>}
        {step === 1 && <div className="form-grid"><div className="field full"><label htmlFor="signup-name">Full name</label><input id="signup-name" required autoComplete="name" value={contact.name} onChange={(event) => setContact({ ...contact, name: event.target.value })}/></div><div className="field"><label htmlFor="signup-email">Email</label><input id="signup-email" type="email" required autoComplete="email" value={contact.email} onChange={(event) => setContact({ ...contact, email: event.target.value })}/></div><div className="field"><label htmlFor="signup-phone">Phone</label><input id="signup-phone" type="tel" required autoComplete="tel" value={contact.phone} onChange={(event) => setContact({ ...contact, phone: event.target.value })}/></div></div>}
        {step === 2 && <div className="stack"><div className="form-grid"><div className="field"><label htmlFor="signup-service">Service</label><select id="signup-service" required value={serviceId} onChange={(event) => setServiceId(event.target.value)}><option value="">Choose a service</option>{services.map((service) => <option key={service.id || service.key} value={service.id || service.key}>{service.name}</option>)}</select></div><div className="field"><label htmlFor="signup-frequency">How often?</label><select id="signup-frequency" value={frequency} onChange={(event) => setFrequency(event.target.value)}><option value="twice_weekly">Twice a week</option><option value="weekly">Every week</option><option value="every_two_weeks">Every two weeks</option><option value="every_four_weeks">Every four weeks</option><option value="one_time">Just once</option></select></div></div><div className="card card-pad" style={{ boxShadow: "none" }}><div className="card-heading"><h2>Your pets</h2><button type="button" className="btn btn-secondary btn-sm" onClick={() => setPets([...pets, { name: "", size: "medium" }])}><Icon name="plus" size={14}/> Add pet</button></div>{pets.map((pet, index) => <div className="form-grid" style={{ marginBottom: 14 }} key={index}><div className="field"><label htmlFor={`pet-name-${index}`}>Pet {index + 1} name</label><input id={`pet-name-${index}`} required value={pet.name} onChange={(event) => updatePet(index, "name", event.target.value)}/></div><div className="field"><label htmlFor={`pet-size-${index}`}>Size</label><select id={`pet-size-${index}`} value={pet.size} onChange={(event) => updatePet(index, "size", event.target.value)}><option value="small">Small</option><option value="medium">Medium</option><option value="large">Large</option><option value="extra_large">Extra large</option></select></div>{pets.length > 1 && <button type="button" className="btn btn-danger btn-sm" onClick={() => setPets(pets.filter((_, itemIndex) => itemIndex !== index))}>Remove pet</button>}</div>)}</div></div>}
        {step === 3 && <div className="form-grid"><div className="field"><label htmlFor="yard-size">Yard size</label><select id="yard-size" value={yardSize} onChange={(event) => setYardSize(event.target.value)}><option value="small">Small</option><option value="medium">Medium</option><option value="large">Large</option><option value="extra_large">Extra large</option></select></div><div className="field"><label htmlFor="preferred-day">Preferred service day (optional)</label><select id="preferred-day" value={preferredDay} onChange={(event) => setPreferredDay(event.target.value)}><option value="">No preference</option>{["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"].map((day) => <option key={day} value={day.toLowerCase()}>{day}</option>)}</select></div><div className="field"><label htmlFor="gate-code">Gate code (optional)</label><input id="gate-code" value={gateCode} onChange={(event) => setGateCode(event.target.value)}/><small>Only your assigned service team will see this.</small></div><div className="field full"><label htmlFor="access-notes">Access or safety notes</label><textarea id="access-notes" value={accessNotes} onChange={(event) => setAccessNotes(event.target.value)} placeholder="Gate on the left, friendly dog, preferred entry…"/></div></div>}
        {step === 4 && <div className="stack"><div className="quote-result"><div className="eyebrow">Your next step</div>{eligible && quote?.amountCents != null && !quote.quoteRequired ? <><strong>{money(quote.amountCents)}</strong><p style={{ margin: "4px 0 0", fontSize: ".85rem" }}>{quote.intervalLabel || "Estimated service price"}. We’ll confirm before service begins.</p></> : <><strong>Personal quote</strong><p style={{ margin: "4px 0 0", fontSize: ".85rem" }}>{!eligible ? "Your location needs review. We’ll get back to you with options." : quoteUnavailable ? "We couldn’t calculate a price just now. We’ll review your details and follow up." : "We’ll review your service details and send a clear quote."}</p></>}</div><div className="card card-pad" style={{ boxShadow: "none" }}><div className="detail-list"><dt>Address</dt><dd>{address}, {zip}</dd></div><div className="detail-list"><dt>Service</dt><dd>{selectedService?.name || "Service"} · {frequency.replaceAll("_", " ")}</dd></div><div className="detail-list"><dt>Pets</dt><dd>{pets.map((pet) => pet.name).join(", ")}</dd></div><div className="detail-list"><dt>Contact</dt><dd>{contact.name} · {contact.email}</dd></div></div>{eligible && quote?.amountCents != null && !quote.quoteRequired && <label className="checkbox-row"><input type="checkbox" checked={demoPayment} onChange={(event) => setDemoPayment(event.target.checked)}/>Use a demo payment method for local testing. No real charge will be made.</label>}<label className="checkbox-row"><input type="checkbox" checked={terms} required onChange={(event) => setTerms(event.target.checked)}/>I agree to be contacted about this request and accept the service terms.</label></div>}
        <div className="onboarding-footer">{step > 0 ? <button type="button" className="btn btn-secondary" onClick={() => setStep(step - 1)}>Back</button> : <Link className="btn btn-secondary" href={`/site/${slug}`}>Back to website</Link>}<button type="submit" className="btn btn-primary" disabled={busy}>{busy ? "One moment…" : step === 0 ? "Check availability" : step === 3 ? "See my price" : step === 4 ? "Send service request" : "Continue"} <Icon name="arrow" size={16}/></button></div>
      </form></>}</div></main></div>;
}
