import type { IndustryPack } from "./index.ts";

export const PET_WASTE_REMOVAL_PACK: IndustryPack = {
  key: "pet-waste-removal",
  version: "1.1.0",
  displayName: "Pet Waste Removal",
  customerTypes: ["residential", "commercial"],
  terminology: { customer: "Client", serviceLocation: "Service Address", customerAsset: "Pet", workArea: "Yard / Service Area", job: "Cleanup", servicePlan: "Service Plan", fieldTechnician: "Technician" },
  locationFields: [
    { key: "gate_access_method", label: "Gate access method", type: "text", sensitive: true },
    { key: "gate_code", label: "Gate code", type: "text", sensitive: true },
    { key: "yard_size", label: "Yard size", type: "enum", options: ["small", "medium", "large", "extra_large"], reportable: true },
    { key: "fenced", label: "Fenced yard", type: "boolean" },
    { key: "waste_disposal_location", label: "Waste disposal location", type: "text" },
    { key: "preferred_entry_point", label: "Preferred entry point", type: "text" },
    { key: "access_notes", label: "Access instructions", type: "text", sensitive: true },
    { key: "technician_safety_notes", label: "Technician safety notes", type: "text", sensitive: true },
    { key: "service_zone", label: "Service zone", type: "text", reportable: true },
    { key: "route_day_preference", label: "Preferred service day", type: "text" },
    { key: "notification_preference", label: "Notification preference", type: "enum", options: ["email", "sms", "both", "none"], customerVisible: true },
  ],
  assets: [{ key: "pet", label: "Pet", pluralLabel: "Pets", fields: [
    { key: "name", label: "Name", type: "text", required: true, customerVisible: true },
    { key: "species", label: "Species", type: "enum", options: ["dog", "other"], defaultValue: "dog", customerVisible: true },
    { key: "breed", label: "Breed", type: "text", customerVisible: true },
    { key: "size", label: "Size", type: "enum", options: ["small", "medium", "large", "extra_large"], customerVisible: true },
    { key: "date_of_birth_or_age", label: "Birth date or age", type: "text", customerVisible: true },
    { key: "photo", label: "Photo", type: "media", customerVisible: true },
    { key: "active_at_location", label: "Active at this address", type: "boolean", defaultValue: true, customerVisible: true, reportable: true },
    { key: "safety_flag", label: "Safety warning", type: "boolean", reportable: true },
    { key: "safety_notes", label: "Safety notes", type: "text", sensitive: true },
    { key: "waste_notes", label: "Cleanup notes", type: "text" },
  ] }],
  services: [
    { key: "recurring-cleanup", name: "Recurring Cleanup", kind: "recurring", estimatedMinutes: 20, defaultEnabled: true },
    { key: "one-time-cleanup", name: "One-Time Cleanup", kind: "one_time", estimatedMinutes: 45, defaultEnabled: true },
    { key: "initial-cleanup", name: "Initial Cleanup", kind: "one_time", estimatedMinutes: 45, defaultEnabled: true },
    { key: "commercial-property-cleanup", name: "Commercial Station / Property Cleanup", kind: "recurring", estimatedMinutes: 45 },
    { key: "deodorizer", name: "Deodorizer / Yard Treatment", kind: "add_on", estimatedMinutes: 10 },
    { key: "waste-station", name: "Waste Station Service", kind: "add_on", estimatedMinutes: 15 },
    { key: "additional-yard", name: "Additional Yard / Work Area", kind: "add_on", estimatedMinutes: 15 },
    { key: "reclean", name: "Reclean / Service Recovery", kind: "recovery", estimatedMinutes: 20 },
  ],
  recurrencePresets: [
    { key: "twice-weekly", label: "Twice weekly", rrule: "FREQ=WEEKLY;BYDAY=MO,TH" },
    { key: "weekly", label: "Weekly", rrule: "FREQ=WEEKLY" },
    { key: "every-two-weeks", label: "Every two weeks", rrule: "FREQ=WEEKLY;INTERVAL=2" },
    { key: "every-four-weeks", label: "Every four weeks", rrule: "FREQ=WEEKLY;INTERVAL=4" },
    { key: "custom", label: "Custom schedule", custom: true },
  ],
  formSteps: [
    { key: "address", label: "Where do you need service?", fields: ["service_address", "service_zone"] },
    { key: "contact", label: "How can we reach you?", fields: ["name", "email", "phone"] },
    { key: "service", label: "Choose your service", fields: ["service", "frequency"] },
    { key: "pets", label: "Tell us about your pets", fields: ["pet_count", "pets"] },
    { key: "yard", label: "Tell us about your yard", fields: ["yard_size", "gate_access_method", "access_notes"] },
    { key: "quote", label: "Review your price", fields: ["price_result", "quote_request"] },
    { key: "extras", label: "Add extras", fields: ["add_ons"] },
    { key: "preferences", label: "Service preferences", fields: ["route_day_preference", "notification_preference"] },
    { key: "payment", label: "Payment", fields: ["payment_method_reference"] },
    { key: "finish", label: "Finish signup", fields: ["terms_accepted", "portal_invite"] },
  ],
  jobChecklist: [
    { key: "confirm_property", label: "Confirm the service address", required: true },
    { key: "review_safety", label: "Review access and safety notes", required: true },
    { key: "perform_cleanup", label: "Complete the cleanup", required: true },
    { key: "completion_photo", label: "Add a completion photo when required", required: false },
    { key: "technician_note", label: "Add a note when needed", required: false },
  ],
  noncompletionReasons: [
    { key: "gate_locked", label: "Gate locked or no access", billableByDefault: false },
    { key: "unsafe_animal", label: "Unsafe animal", billableByDefault: false },
    { key: "customer_skip", label: "Customer requested skip", billableByDefault: false },
    { key: "weather", label: "Weather", billableByDefault: false },
    { key: "property_condition", label: "Property condition", billableByDefault: false },
    { key: "technician_issue", label: "Technician issue", billableByDefault: false },
    { key: "address_problem", label: "Could not locate property", billableByDefault: false },
    { key: "other", label: "Other", billableByDefault: false },
  ],
  workflows: {
    cleanup: ["scheduled", "assigned", "dispatched", "en_route", "started", "completed"],
    recovery: ["requested", "review", "needs_return", "scheduled", "completed"],
    signup: ["submitted", "eligibility_checked", "priced_or_review", "plan_or_lead_created"],
    changeRequest: ["submitted", "review", "approved", "rejected"],
  },
  defaultAutomations: [
    { sourceKey: "signup-confirmation", name: "Welcome new clients", description: "Confirm a completed website signup.", event: "site_submission.created", filters: { field: "kind", operator: "equals", value: "customer" }, actions: [{ actionType: "send_email", configuration: { templateKey: "signup-confirmation" } }], enabledByDefault: true },
    { sourceKey: "signup-review", name: "Review new service requests", description: "Alert the office when a website signup needs review.", event: "site_submission.created", filters: { field: "kind", operator: "equals", value: "lead" }, actions: [{ actionType: "notify_staff", configuration: { when: "manual_review" } }], enabledByDefault: true },
    { sourceKey: "cleanup-completed", name: "Cleanup complete", description: "Send the client a completion notice after a cleanup.", event: "job.completed", actions: [{ actionType: "send_sms", configuration: { templateKey: "cleanup-completed" } }], enabledByDefault: true },
    { sourceKey: "payment-failed", name: "Payment needs attention", description: "Notify the client and office after a failed payment.", event: "payment.failed", actions: [{ actionType: "send_email", configuration: { templateKey: "payment-failed" } }, { actionType: "notify_staff", configuration: { reason: "payment_failed" } }], enabledByDefault: true },
    { sourceKey: "payment-receipt", name: "Payment receipt", description: "Email a receipt after a successful payment.", event: "payment.succeeded", actions: [{ actionType: "send_email", configuration: { templateKey: "payment-receipt", customerId: "${customerId}", subject: "Payment received", body: "We received your payment. You can view your receipt in your account." } }], enabledByDefault: false },
    { sourceKey: "pause-request", name: "Review pause requests", description: "Create a review item for a client pause request.", event: "customer_change_request.submitted", filters: { field: "type", operator: "equals", value: "pause" }, actions: [{ actionType: "create_ticket", configuration: { type: "plan_change_review" } }], enabledByDefault: true },
    { sourceKey: "route-published", name: "Service day reminders", description: "Remind each client when their visit is dispatched on a published route.", event: "job.dispatched", actions: [{ actionType: "send_sms", configuration: { templateKey: "service-day-reminder" } }], enabledByDefault: false },
  ],
  reports: [
    { key: "active-clients-by-frequency", name: "Active clients by frequency", coreMetric: "active_customers", dimensions: ["frequency"] },
    { key: "cleanup-outcomes", name: "Cleanup outcomes", coreMetric: "job_outcomes", dimensions: ["service_zone", "technician"] },
    { key: "reclean-rate", name: "Reclean rate", coreMetric: "reclean_rate", dimensions: ["technician"] },
    { key: "route-density", name: "Route density", coreMetric: "route_density", dimensions: ["service_zone"] },
    { key: "service-time-by-pet-count", name: "Service time by pet count", coreMetric: "service_duration", dimensions: ["pet_count", "yard_size"] },
    { key: "tips-by-technician", name: "Tips by technician", coreMetric: "tips", dimensions: ["technician"] },
    { key: "revenue-by-customer-type", name: "Commercial vs residential revenue", coreMetric: "collected", dimensions: ["customer_type"] },
  ],
  pricingTemplates: [
    { key: "cleanup-base", name: "Cleanup base price", stage: "base", inputFields: ["service", "frequency"], effect: "set_base_amount", requiresTenantAmount: true },
    { key: "additional-pet", name: "Additional pet", stage: "quantity", inputFields: ["active_pet_count"], effect: "per_unit", requiresTenantAmount: true },
    { key: "yard-zone", name: "Yard or service zone", stage: "zone", inputFields: ["yard_size", "service_zone"], effect: "add_fixed", requiresTenantAmount: true },
    { key: "add-on", name: "Optional add-on", stage: "add_on", inputFields: ["selected_add_ons"], effect: "add_fixed", requiresTenantAmount: true },
    { key: "promotion", name: "Promotion", stage: "promotion", inputFields: ["coupon_code"], effect: "subtract_percentage", requiresTenantAmount: true },
    { key: "minimum", name: "Minimum visit price", stage: "bounds", inputFields: ["service"], effect: "set_minimum", requiresTenantAmount: true },
  ],
  recommendationQuestions: [
    { key: "uses_field_technicians", prompt: "Do you send technicians or crews to customer properties?", answerType: "boolean" },
    { key: "accepts_online_bookings", prompt: "Do customers book service online?", answerType: "boolean" },
    { key: "prepares_estimates", prompt: "Do you prepare a quote before accepting some service requests?", answerType: "boolean" },
    { key: "multiple_crews", prompt: "Do you dispatch more than one crew at a time?", answerType: "boolean" },
    { key: "many_daily_stops", prompt: "Do you travel between many service stops each day?", answerType: "boolean" },
    { key: "has_paid_staff", prompt: "Do you have paid employees or technicians?", answerType: "boolean" },
    { key: "tracks_employee_hours", prompt: "Do employees clock in and out or record time on jobs?", answerType: "boolean" },
    { key: "tracks_service_supplies", prompt: "Do you keep supplies in stock that you need to track?", answerType: "boolean" },
    { key: "operates_multiple_locations", prompt: "Do you operate more than one business location?", answerType: "boolean" },
  ],
  productCapabilityRecommendations: [
    { featureKey: "recurring_service_management", recommendation: "normally_recommended", rationale: "Most pet waste removal revenue comes from repeat visits on a predictable service schedule." },
    { featureKey: "service_scheduling", recommendation: "normally_recommended", rationale: "A shared schedule helps manage recurring visits, one-time cleanups, skips, and return visits." },
    { featureKey: "payment_collection", recommendation: "normally_recommended", rationale: "Collecting and reconciling payment is part of the regular service workflow." },
    { featureKey: "invoicing", recommendation: "normally_recommended", rationale: "Invoices give customers a clear record of recurring service, one-time cleanups, and payments due." },
    { featureKey: "customer_notifications", recommendation: "normally_recommended", rationale: "Customers value reminders and a notice when their yard has been serviced." },
    { featureKey: "customer_self_service", recommendation: "optional", rationale: "A customer portal can make service changes, pauses, payment, and proof of service easier to manage." },
    {
      featureKey: "estimate_management",
      recommendation: "optional",
      rationale: "Estimate tracking helps when a new property or cleanup needs a quote and customer approval before scheduling.",
      rules: [{ when: { op: "equals", answerKey: "prepares_estimates", value: true }, recommendation: "normally_recommended" }],
    },
    {
      featureKey: "online_booking",
      recommendation: "optional",
      rationale: "Online booking is useful when customers can start service without a manual office conversation.",
      rules: [{ when: { op: "equals", answerKey: "accepts_online_bookings", value: true }, recommendation: "normally_recommended" }],
    },
    {
      featureKey: "website_publishing",
      recommendation: "optional",
      rationale: "A service website can explain the service area, pricing approach, and how new customers get started.",
      rules: [{ when: { op: "equals", answerKey: "accepts_online_bookings", value: true }, recommendation: "normally_recommended" }],
    },
    { featureKey: "automation_workflows", recommendation: "optional", rationale: "Automated signup, service, payment, and customer-change follow-ups reduce repeated office work as volume grows." },
    {
      featureKey: "field_job_tracking",
      recommendation: "optional",
      rationale: "Mobile job details and completion updates help when technicians or crews work at customer properties.",
      rules: [{ when: { op: "equals", answerKey: "uses_field_technicians", value: true }, recommendation: "normally_recommended" }],
    },
    {
      featureKey: "route_planning",
      recommendation: "usually_unnecessary",
      rationale: "Route planning matters most when several crews or many daily stops need to be sequenced across service areas.",
      rules: [{
        when: { op: "any", conditions: [
          { op: "equals", answerKey: "multiple_crews", value: true },
          { op: "equals", answerKey: "many_daily_stops", value: true },
        ] },
        recommendation: "normally_recommended",
      }],
    },
    {
      featureKey: "time_tracking",
      recommendation: "optional",
      rationale: "Time tracking helps owners understand labor and service duration, especially when staff work scheduled shifts.",
      rules: [{ when: { op: "equals", answerKey: "tracks_employee_hours", value: true }, recommendation: "normally_recommended" }],
    },
    {
      featureKey: "payroll_inputs",
      recommendation: "usually_unnecessary",
      rationale: "Payroll inputs help prepare hours, tips, and mileage for payroll when the business has paid staff.",
      rules: [{ when: { op: "equals", answerKey: "has_paid_staff", value: true }, recommendation: "normally_recommended" }],
    },
    {
      featureKey: "inventory_tracking",
      recommendation: "usually_unnecessary",
      rationale: "Inventory tracking is useful when crews carry enough supplies or treatment products to need stock counts.",
      rules: [{ when: { op: "equals", answerKey: "tracks_service_supplies", value: true }, recommendation: "normally_recommended" }],
    },
    {
      featureKey: "multi_location_management",
      recommendation: "usually_unnecessary",
      rationale: "Separate location operations and reporting help when the business serves customers from more than one branch.",
      rules: [{ when: { op: "equals", answerKey: "operates_multiple_locations", value: true }, recommendation: "normally_recommended" }],
    },
    {
      featureKey: "advanced_reporting",
      recommendation: "usually_unnecessary",
      rationale: "Detailed staff, route, and location comparisons become more useful as the business grows beyond a small owner-operated route.",
      rules: [{
        when: { op: "any", conditions: [
          { op: "equals", answerKey: "has_paid_staff", value: true },
          { op: "equals", answerKey: "many_daily_stops", value: true },
          { op: "equals", answerKey: "operates_multiple_locations", value: true },
        ] },
        recommendation: "normally_recommended",
      }],
    },
  ],
  recommendedConnectorCapabilities: ["payments", "sms", "email", "routing", "geocoding", "accounting", "calendar", "storage"],
  inventoryDefaults: [
    { key: "waste-bags", name: "Waste bags", unit: "bag" },
    { key: "deodorizer", name: "Deodorizer / treatment", unit: "container" },
    { key: "gloves", name: "Gloves", unit: "pair" },
    { key: "boot-covers", name: "Boot covers", unit: "pair" },
    { key: "station-liners", name: "Waste-station liners", unit: "liner" },
    { key: "sanitizer", name: "Sanitizer", unit: "container" },
  ],
  website: {
    template: "route-service",
    sections: ["hero", "how_it_works", "services", "pricing", "service_area", "why_us", "faq", "reviews", "signup", "customer_login", "contact"],
    signupSteps: ["address", "contact", "service", "pets", "yard", "quote", "extras", "preferences", "payment", "finish"],
    signupBehavior: "activate_recurring",
    heroHeadline: "A cleaner yard is just a few clicks away",
    heroDescription: "Set up reliable cleanup service for your home or property.",
  },
};
